package com.ciessa.museum.model.legacy;
// Generated Mar 7, 2018 5:59:21 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * Ccrpcpv generated by hbm2java
 */
public class Ccrpcpv implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 396934780497808217L;

	private String pkid;
	private String member;
	private Long cpnucr;
	private Integer cpcuat;
	private Integer cpcuco;
	private Integer cpfega;
	private String cpusid;
	private Integer cpfeve;
	private Integer cpfepa;
	private BigDecimal cptacr;
	private BigDecimal cppuni;
	private BigDecimal cpcomp;
	private BigDecimal cpfeco;
	private BigDecimal cpiva1;
	private BigDecimal cpiva2;
	private BigDecimal cpimen;
	private Long cpdiat;
	private String cpsbtp;
	private String cpcfez;

	public Ccrpcpv() {
	}

	public Ccrpcpv(String pkid) {
		this.pkid = pkid;
	}

	public Ccrpcpv(String pkid, String member, Long cpnucr, Integer cpcuat, Integer cpcuco, Integer cpfega,
			String cpusid, Integer cpfeve, Integer cpfepa, BigDecimal cptacr, BigDecimal cppuni, BigDecimal cpcomp,
			BigDecimal cpfeco, BigDecimal cpiva1, BigDecimal cpiva2, BigDecimal cpimen, Long cpdiat, String cpsbtp,
			String cpcfez) {
		this.pkid = pkid;
		this.member = member;
		this.cpnucr = cpnucr;
		this.cpcuat = cpcuat;
		this.cpcuco = cpcuco;
		this.cpfega = cpfega;
		this.cpusid = cpusid;
		this.cpfeve = cpfeve;
		this.cpfepa = cpfepa;
		this.cptacr = cptacr;
		this.cppuni = cppuni;
		this.cpcomp = cpcomp;
		this.cpfeco = cpfeco;
		this.cpiva1 = cpiva1;
		this.cpiva2 = cpiva2;
		this.cpimen = cpimen;
		this.cpdiat = cpdiat;
		this.cpsbtp = cpsbtp;
		this.cpcfez = cpcfez;
	}

	public String getPkid() {
		return this.pkid;
	}

	public void setPkid(String pkid) {
		this.pkid = pkid;
	}

	public String getMember() {
		return this.member;
	}

	public void setMember(String member) {
		this.member = member;
	}

	public Long getCpnucr() {
		return this.cpnucr;
	}

	public void setCpnucr(Long cpnucr) {
		this.cpnucr = cpnucr;
	}

	public Integer getCpcuat() {
		return this.cpcuat;
	}

	public void setCpcuat(Integer cpcuat) {
		this.cpcuat = cpcuat;
	}

	public Integer getCpcuco() {
		return this.cpcuco;
	}

	public void setCpcuco(Integer cpcuco) {
		this.cpcuco = cpcuco;
	}

	public Integer getCpfega() {
		return this.cpfega;
	}

	public void setCpfega(Integer cpfega) {
		this.cpfega = cpfega;
	}

	public String getCpusid() {
		return this.cpusid;
	}

	public void setCpusid(String cpusid) {
		this.cpusid = cpusid;
	}

	public Integer getCpfeve() {
		return this.cpfeve;
	}

	public void setCpfeve(Integer cpfeve) {
		this.cpfeve = cpfeve;
	}

	public Integer getCpfepa() {
		return this.cpfepa;
	}

	public void setCpfepa(Integer cpfepa) {
		this.cpfepa = cpfepa;
	}

	public BigDecimal getCptacr() {
		return this.cptacr;
	}

	public void setCptacr(BigDecimal cptacr) {
		this.cptacr = cptacr;
	}

	public BigDecimal getCppuni() {
		return this.cppuni;
	}

	public void setCppuni(BigDecimal cppuni) {
		this.cppuni = cppuni;
	}

	public BigDecimal getCpcomp() {
		return this.cpcomp;
	}

	public void setCpcomp(BigDecimal cpcomp) {
		this.cpcomp = cpcomp;
	}

	public BigDecimal getCpfeco() {
		return this.cpfeco;
	}

	public void setCpfeco(BigDecimal cpfeco) {
		this.cpfeco = cpfeco;
	}

	public BigDecimal getCpiva1() {
		return this.cpiva1;
	}

	public void setCpiva1(BigDecimal cpiva1) {
		this.cpiva1 = cpiva1;
	}

	public BigDecimal getCpiva2() {
		return this.cpiva2;
	}

	public void setCpiva2(BigDecimal cpiva2) {
		this.cpiva2 = cpiva2;
	}

	public BigDecimal getCpimen() {
		return this.cpimen;
	}

	public void setCpimen(BigDecimal cpimen) {
		this.cpimen = cpimen;
	}

	public Long getCpdiat() {
		return this.cpdiat;
	}

	public void setCpdiat(Long cpdiat) {
		this.cpdiat = cpdiat;
	}

	public String getCpsbtp() {
		return this.cpsbtp;
	}

	public void setCpsbtp(String cpsbtp) {
		this.cpsbtp = cpsbtp;
	}

	public String getCpcfez() {
		return this.cpcfez;
	}

	public void setCpcfez(String cpcfez) {
		this.cpcfez = cpcfez;
	}

}
