package com.ciessa.museum.model.legacy;
// Generated Dec 8, 2018 1:27:28 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Ccrpmov generated by hbm2java
 */
public class Ccrpmov  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer mvbanc;
     private Integer mvnmov;
     private Long mvnucr;
     private Integer mvdtem;
     private BigDecimal mvimpm;
     private String mvstat;
     private Integer mvcsup;
     private String mvfpcu;
     private Integer mvdtei;
     private Integer mvtmei;
     private String mvopri;
     private Integer mvdtea;
     private Integer mvtmea;
     private String mvopra;
     private String mvcmmo;
     private Integer mvdtep;
     private Integer mvtmep;
     private String mvmoti;

    public Ccrpmov() {
    }

	
    public Ccrpmov(String pkid) {
        this.pkid = pkid;
    }
    public Ccrpmov(String pkid, String member, Integer mvbanc, Integer mvnmov, Long mvnucr, Integer mvdtem, BigDecimal mvimpm, String mvstat, Integer mvcsup, String mvfpcu, Integer mvdtei, Integer mvtmei, String mvopri, Integer mvdtea, Integer mvtmea, String mvopra, String mvcmmo, Integer mvdtep, Integer mvtmep, String mvmoti) {
       this.pkid = pkid;
       this.member = member;
       this.mvbanc = mvbanc;
       this.mvnmov = mvnmov;
       this.mvnucr = mvnucr;
       this.mvdtem = mvdtem;
       this.mvimpm = mvimpm;
       this.mvstat = mvstat;
       this.mvcsup = mvcsup;
       this.mvfpcu = mvfpcu;
       this.mvdtei = mvdtei;
       this.mvtmei = mvtmei;
       this.mvopri = mvopri;
       this.mvdtea = mvdtea;
       this.mvtmea = mvtmea;
       this.mvopra = mvopra;
       this.mvcmmo = mvcmmo;
       this.mvdtep = mvdtep;
       this.mvtmep = mvtmep;
       this.mvmoti = mvmoti;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getMvbanc() {
        return this.mvbanc;
    }
    
    public void setMvbanc(Integer mvbanc) {
        this.mvbanc = mvbanc;
    }
    public Integer getMvnmov() {
        return this.mvnmov;
    }
    
    public void setMvnmov(Integer mvnmov) {
        this.mvnmov = mvnmov;
    }
    public Long getMvnucr() {
        return this.mvnucr;
    }
    
    public void setMvnucr(Long mvnucr) {
        this.mvnucr = mvnucr;
    }
    public Integer getMvdtem() {
        return this.mvdtem;
    }
    
    public void setMvdtem(Integer mvdtem) {
        this.mvdtem = mvdtem;
    }
    public BigDecimal getMvimpm() {
        return this.mvimpm;
    }
    
    public void setMvimpm(BigDecimal mvimpm) {
        this.mvimpm = mvimpm;
    }
    public String getMvstat() {
        return this.mvstat;
    }
    
    public void setMvstat(String mvstat) {
        this.mvstat = mvstat;
    }
    public Integer getMvcsup() {
        return this.mvcsup;
    }
    
    public void setMvcsup(Integer mvcsup) {
        this.mvcsup = mvcsup;
    }
    public String getMvfpcu() {
        return this.mvfpcu;
    }
    
    public void setMvfpcu(String mvfpcu) {
        this.mvfpcu = mvfpcu;
    }
    public Integer getMvdtei() {
        return this.mvdtei;
    }
    
    public void setMvdtei(Integer mvdtei) {
        this.mvdtei = mvdtei;
    }
    public Integer getMvtmei() {
        return this.mvtmei;
    }
    
    public void setMvtmei(Integer mvtmei) {
        this.mvtmei = mvtmei;
    }
    public String getMvopri() {
        return this.mvopri;
    }
    
    public void setMvopri(String mvopri) {
        this.mvopri = mvopri;
    }
    public Integer getMvdtea() {
        return this.mvdtea;
    }
    
    public void setMvdtea(Integer mvdtea) {
        this.mvdtea = mvdtea;
    }
    public Integer getMvtmea() {
        return this.mvtmea;
    }
    
    public void setMvtmea(Integer mvtmea) {
        this.mvtmea = mvtmea;
    }
    public String getMvopra() {
        return this.mvopra;
    }
    
    public void setMvopra(String mvopra) {
        this.mvopra = mvopra;
    }
    public String getMvcmmo() {
        return this.mvcmmo;
    }
    
    public void setMvcmmo(String mvcmmo) {
        this.mvcmmo = mvcmmo;
    }
    public Integer getMvdtep() {
        return this.mvdtep;
    }
    
    public void setMvdtep(Integer mvdtep) {
        this.mvdtep = mvdtep;
    }
    public Integer getMvtmep() {
        return this.mvtmep;
    }
    
    public void setMvtmep(Integer mvtmep) {
        this.mvtmep = mvtmep;
    }
    public String getMvmoti() {
        return this.mvmoti;
    }
    
    public void setMvmoti(String mvmoti) {
        this.mvmoti = mvmoti;
    }




}


