package com.ciessa.museum.model.legacy;
// Generated Jul 30, 2018 8:24:30 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Ccrpscb generated by hbm2java
 */
public class Ccrpscb  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer sbbanc;
     private Long sbnucr;
     private Integer sbncuo;
     private Integer sbsbnc;
     private String sbticu;
     private String sbstcu;
     private Integer sbagcu;
     private Integer sbmgcu;
     private Integer sbdgcu;
     private Integer sbavcu;
     private Integer sbmvcu;
     private Integer sbdvcu;
     private BigDecimal sbtacr;
     private BigDecimal sbvtpo;
     private Long sbibas;
     private Long sbiact;
     private BigDecimal sbimam;
     private BigDecimal sbimba;
     private BigDecimal sbicaj;
     private BigDecimal sbicin;
     private BigDecimal sbvipo;
     private BigDecimal sbisvi;
     private BigDecimal sbicca;
     private BigDecimal sbiise;
     private Integer sbaapc;
     private Integer sbmmpc;
     private Integer sbddpc;
     private Integer sbaaip;
     private Integer sbmmip;
     private Integer sbddip;
     private String sbfpcu;
     private Integer sbcsup;
     private Integer sbdapc;
     private Integer sbarcu;
     private Integer sbmrcu;
     private Integer sbdrcu;
     private BigDecimal sbviaa;
     private BigDecimal sbvima;
     private BigDecimal sbvipa;
     private BigDecimal sbipma;
     private BigDecimal sbicma;
     private BigDecimal sbiipd;
     private BigDecimal sbiicd;
     private BigDecimal sbiipc;
     private BigDecimal sbiicc;
     private BigDecimal sbsdfi;
     private String sbacon;
     private BigDecimal sbcar1;
     private String sbmaav;
     private String sbmaam;
     private String sbusop;
     private String sbusau;
     private Integer sbcono;
     private Integer sbaano;
     private Integer sbmmno;
     private Integer sbddno;
     private Integer sbcomo;
     private BigDecimal sbcoti;
     private BigDecimal sbcopa;
     private BigDecimal sbisau;
     private Integer sbncen;
     private BigDecimal sbi9in;
     private BigDecimal sbi9sv;
     private BigDecimal sbi9ca;
     private BigDecimal sbi9pd;
     private BigDecimal sbi9cd;
     private BigDecimal sbi9pc;
     private BigDecimal sbi9cc;
     private BigDecimal sbi9c1;
     private BigDecimal sbi9cs;
     private BigDecimal sbi8in;
     private BigDecimal sbi8sv;
     private BigDecimal sbi8ca;
     private BigDecimal sbi8pd;
     private BigDecimal sbi8cd;
     private BigDecimal sbi8pc;
     private BigDecimal sbi8cc;
     private BigDecimal sbi8c1;
     private BigDecimal sbi8cs;
     private BigDecimal sbcsau;
     private BigDecimal sbcsvi;
     private BigDecimal sbauac;
     private BigDecimal sbc8cs;
     private BigDecimal sbc9cs;

    public Ccrpscb() {
    }

	
    public Ccrpscb(String pkid) {
        this.pkid = pkid;
    }
    public Ccrpscb(String pkid, String member, Integer sbbanc, Long sbnucr, Integer sbncuo, Integer sbsbnc, String sbticu, String sbstcu, Integer sbagcu, Integer sbmgcu, Integer sbdgcu, Integer sbavcu, Integer sbmvcu, Integer sbdvcu, BigDecimal sbtacr, BigDecimal sbvtpo, Long sbibas, Long sbiact, BigDecimal sbimam, BigDecimal sbimba, BigDecimal sbicaj, BigDecimal sbicin, BigDecimal sbvipo, BigDecimal sbisvi, BigDecimal sbicca, BigDecimal sbiise, Integer sbaapc, Integer sbmmpc, Integer sbddpc, Integer sbaaip, Integer sbmmip, Integer sbddip, String sbfpcu, Integer sbcsup, Integer sbdapc, Integer sbarcu, Integer sbmrcu, Integer sbdrcu, BigDecimal sbviaa, BigDecimal sbvima, BigDecimal sbvipa, BigDecimal sbipma, BigDecimal sbicma, BigDecimal sbiipd, BigDecimal sbiicd, BigDecimal sbiipc, BigDecimal sbiicc, BigDecimal sbsdfi, String sbacon, BigDecimal sbcar1, String sbmaav, String sbmaam, String sbusop, String sbusau, Integer sbcono, Integer sbaano, Integer sbmmno, Integer sbddno, Integer sbcomo, BigDecimal sbcoti, BigDecimal sbcopa, BigDecimal sbisau, Integer sbncen, BigDecimal sbi9in, BigDecimal sbi9sv, BigDecimal sbi9ca, BigDecimal sbi9pd, BigDecimal sbi9cd, BigDecimal sbi9pc, BigDecimal sbi9cc, BigDecimal sbi9c1, BigDecimal sbi9cs, BigDecimal sbi8in, BigDecimal sbi8sv, BigDecimal sbi8ca, BigDecimal sbi8pd, BigDecimal sbi8cd, BigDecimal sbi8pc, BigDecimal sbi8cc, BigDecimal sbi8c1, BigDecimal sbi8cs, BigDecimal sbcsau, BigDecimal sbcsvi, BigDecimal sbauac, BigDecimal sbc8cs, BigDecimal sbc9cs) {
       this.pkid = pkid;
       this.member = member;
       this.sbbanc = sbbanc;
       this.sbnucr = sbnucr;
       this.sbncuo = sbncuo;
       this.sbsbnc = sbsbnc;
       this.sbticu = sbticu;
       this.sbstcu = sbstcu;
       this.sbagcu = sbagcu;
       this.sbmgcu = sbmgcu;
       this.sbdgcu = sbdgcu;
       this.sbavcu = sbavcu;
       this.sbmvcu = sbmvcu;
       this.sbdvcu = sbdvcu;
       this.sbtacr = sbtacr;
       this.sbvtpo = sbvtpo;
       this.sbibas = sbibas;
       this.sbiact = sbiact;
       this.sbimam = sbimam;
       this.sbimba = sbimba;
       this.sbicaj = sbicaj;
       this.sbicin = sbicin;
       this.sbvipo = sbvipo;
       this.sbisvi = sbisvi;
       this.sbicca = sbicca;
       this.sbiise = sbiise;
       this.sbaapc = sbaapc;
       this.sbmmpc = sbmmpc;
       this.sbddpc = sbddpc;
       this.sbaaip = sbaaip;
       this.sbmmip = sbmmip;
       this.sbddip = sbddip;
       this.sbfpcu = sbfpcu;
       this.sbcsup = sbcsup;
       this.sbdapc = sbdapc;
       this.sbarcu = sbarcu;
       this.sbmrcu = sbmrcu;
       this.sbdrcu = sbdrcu;
       this.sbviaa = sbviaa;
       this.sbvima = sbvima;
       this.sbvipa = sbvipa;
       this.sbipma = sbipma;
       this.sbicma = sbicma;
       this.sbiipd = sbiipd;
       this.sbiicd = sbiicd;
       this.sbiipc = sbiipc;
       this.sbiicc = sbiicc;
       this.sbsdfi = sbsdfi;
       this.sbacon = sbacon;
       this.sbcar1 = sbcar1;
       this.sbmaav = sbmaav;
       this.sbmaam = sbmaam;
       this.sbusop = sbusop;
       this.sbusau = sbusau;
       this.sbcono = sbcono;
       this.sbaano = sbaano;
       this.sbmmno = sbmmno;
       this.sbddno = sbddno;
       this.sbcomo = sbcomo;
       this.sbcoti = sbcoti;
       this.sbcopa = sbcopa;
       this.sbisau = sbisau;
       this.sbncen = sbncen;
       this.sbi9in = sbi9in;
       this.sbi9sv = sbi9sv;
       this.sbi9ca = sbi9ca;
       this.sbi9pd = sbi9pd;
       this.sbi9cd = sbi9cd;
       this.sbi9pc = sbi9pc;
       this.sbi9cc = sbi9cc;
       this.sbi9c1 = sbi9c1;
       this.sbi9cs = sbi9cs;
       this.sbi8in = sbi8in;
       this.sbi8sv = sbi8sv;
       this.sbi8ca = sbi8ca;
       this.sbi8pd = sbi8pd;
       this.sbi8cd = sbi8cd;
       this.sbi8pc = sbi8pc;
       this.sbi8cc = sbi8cc;
       this.sbi8c1 = sbi8c1;
       this.sbi8cs = sbi8cs;
       this.sbcsau = sbcsau;
       this.sbcsvi = sbcsvi;
       this.sbauac = sbauac;
       this.sbc8cs = sbc8cs;
       this.sbc9cs = sbc9cs;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getSbbanc() {
        return this.sbbanc;
    }
    
    public void setSbbanc(Integer sbbanc) {
        this.sbbanc = sbbanc;
    }
    public Long getSbnucr() {
        return this.sbnucr;
    }
    
    public void setSbnucr(Long sbnucr) {
        this.sbnucr = sbnucr;
    }
    public Integer getSbncuo() {
        return this.sbncuo;
    }
    
    public void setSbncuo(Integer sbncuo) {
        this.sbncuo = sbncuo;
    }
    public Integer getSbsbnc() {
        return this.sbsbnc;
    }
    
    public void setSbsbnc(Integer sbsbnc) {
        this.sbsbnc = sbsbnc;
    }
    public String getSbticu() {
        return this.sbticu;
    }
    
    public void setSbticu(String sbticu) {
        this.sbticu = sbticu;
    }
    public String getSbstcu() {
        return this.sbstcu;
    }
    
    public void setSbstcu(String sbstcu) {
        this.sbstcu = sbstcu;
    }
    public Integer getSbagcu() {
        return this.sbagcu;
    }
    
    public void setSbagcu(Integer sbagcu) {
        this.sbagcu = sbagcu;
    }
    public Integer getSbmgcu() {
        return this.sbmgcu;
    }
    
    public void setSbmgcu(Integer sbmgcu) {
        this.sbmgcu = sbmgcu;
    }
    public Integer getSbdgcu() {
        return this.sbdgcu;
    }
    
    public void setSbdgcu(Integer sbdgcu) {
        this.sbdgcu = sbdgcu;
    }
    public Integer getSbavcu() {
        return this.sbavcu;
    }
    
    public void setSbavcu(Integer sbavcu) {
        this.sbavcu = sbavcu;
    }
    public Integer getSbmvcu() {
        return this.sbmvcu;
    }
    
    public void setSbmvcu(Integer sbmvcu) {
        this.sbmvcu = sbmvcu;
    }
    public Integer getSbdvcu() {
        return this.sbdvcu;
    }
    
    public void setSbdvcu(Integer sbdvcu) {
        this.sbdvcu = sbdvcu;
    }
    public BigDecimal getSbtacr() {
        return this.sbtacr;
    }
    
    public void setSbtacr(BigDecimal sbtacr) {
        this.sbtacr = sbtacr;
    }
    public BigDecimal getSbvtpo() {
        return this.sbvtpo;
    }
    
    public void setSbvtpo(BigDecimal sbvtpo) {
        this.sbvtpo = sbvtpo;
    }
    public Long getSbibas() {
        return this.sbibas;
    }
    
    public void setSbibas(Long sbibas) {
        this.sbibas = sbibas;
    }
    public Long getSbiact() {
        return this.sbiact;
    }
    
    public void setSbiact(Long sbiact) {
        this.sbiact = sbiact;
    }
    public BigDecimal getSbimam() {
        return this.sbimam;
    }
    
    public void setSbimam(BigDecimal sbimam) {
        this.sbimam = sbimam;
    }
    public BigDecimal getSbimba() {
        return this.sbimba;
    }
    
    public void setSbimba(BigDecimal sbimba) {
        this.sbimba = sbimba;
    }
    public BigDecimal getSbicaj() {
        return this.sbicaj;
    }
    
    public void setSbicaj(BigDecimal sbicaj) {
        this.sbicaj = sbicaj;
    }
    public BigDecimal getSbicin() {
        return this.sbicin;
    }
    
    public void setSbicin(BigDecimal sbicin) {
        this.sbicin = sbicin;
    }
    public BigDecimal getSbvipo() {
        return this.sbvipo;
    }
    
    public void setSbvipo(BigDecimal sbvipo) {
        this.sbvipo = sbvipo;
    }
    public BigDecimal getSbisvi() {
        return this.sbisvi;
    }
    
    public void setSbisvi(BigDecimal sbisvi) {
        this.sbisvi = sbisvi;
    }
    public BigDecimal getSbicca() {
        return this.sbicca;
    }
    
    public void setSbicca(BigDecimal sbicca) {
        this.sbicca = sbicca;
    }
    public BigDecimal getSbiise() {
        return this.sbiise;
    }
    
    public void setSbiise(BigDecimal sbiise) {
        this.sbiise = sbiise;
    }
    public Integer getSbaapc() {
        return this.sbaapc;
    }
    
    public void setSbaapc(Integer sbaapc) {
        this.sbaapc = sbaapc;
    }
    public Integer getSbmmpc() {
        return this.sbmmpc;
    }
    
    public void setSbmmpc(Integer sbmmpc) {
        this.sbmmpc = sbmmpc;
    }
    public Integer getSbddpc() {
        return this.sbddpc;
    }
    
    public void setSbddpc(Integer sbddpc) {
        this.sbddpc = sbddpc;
    }
    public Integer getSbaaip() {
        return this.sbaaip;
    }
    
    public void setSbaaip(Integer sbaaip) {
        this.sbaaip = sbaaip;
    }
    public Integer getSbmmip() {
        return this.sbmmip;
    }
    
    public void setSbmmip(Integer sbmmip) {
        this.sbmmip = sbmmip;
    }
    public Integer getSbddip() {
        return this.sbddip;
    }
    
    public void setSbddip(Integer sbddip) {
        this.sbddip = sbddip;
    }
    public String getSbfpcu() {
        return this.sbfpcu;
    }
    
    public void setSbfpcu(String sbfpcu) {
        this.sbfpcu = sbfpcu;
    }
    public Integer getSbcsup() {
        return this.sbcsup;
    }
    
    public void setSbcsup(Integer sbcsup) {
        this.sbcsup = sbcsup;
    }
    public Integer getSbdapc() {
        return this.sbdapc;
    }
    
    public void setSbdapc(Integer sbdapc) {
        this.sbdapc = sbdapc;
    }
    public Integer getSbarcu() {
        return this.sbarcu;
    }
    
    public void setSbarcu(Integer sbarcu) {
        this.sbarcu = sbarcu;
    }
    public Integer getSbmrcu() {
        return this.sbmrcu;
    }
    
    public void setSbmrcu(Integer sbmrcu) {
        this.sbmrcu = sbmrcu;
    }
    public Integer getSbdrcu() {
        return this.sbdrcu;
    }
    
    public void setSbdrcu(Integer sbdrcu) {
        this.sbdrcu = sbdrcu;
    }
    public BigDecimal getSbviaa() {
        return this.sbviaa;
    }
    
    public void setSbviaa(BigDecimal sbviaa) {
        this.sbviaa = sbviaa;
    }
    public BigDecimal getSbvima() {
        return this.sbvima;
    }
    
    public void setSbvima(BigDecimal sbvima) {
        this.sbvima = sbvima;
    }
    public BigDecimal getSbvipa() {
        return this.sbvipa;
    }
    
    public void setSbvipa(BigDecimal sbvipa) {
        this.sbvipa = sbvipa;
    }
    public BigDecimal getSbipma() {
        return this.sbipma;
    }
    
    public void setSbipma(BigDecimal sbipma) {
        this.sbipma = sbipma;
    }
    public BigDecimal getSbicma() {
        return this.sbicma;
    }
    
    public void setSbicma(BigDecimal sbicma) {
        this.sbicma = sbicma;
    }
    public BigDecimal getSbiipd() {
        return this.sbiipd;
    }
    
    public void setSbiipd(BigDecimal sbiipd) {
        this.sbiipd = sbiipd;
    }
    public BigDecimal getSbiicd() {
        return this.sbiicd;
    }
    
    public void setSbiicd(BigDecimal sbiicd) {
        this.sbiicd = sbiicd;
    }
    public BigDecimal getSbiipc() {
        return this.sbiipc;
    }
    
    public void setSbiipc(BigDecimal sbiipc) {
        this.sbiipc = sbiipc;
    }
    public BigDecimal getSbiicc() {
        return this.sbiicc;
    }
    
    public void setSbiicc(BigDecimal sbiicc) {
        this.sbiicc = sbiicc;
    }
    public BigDecimal getSbsdfi() {
        return this.sbsdfi;
    }
    
    public void setSbsdfi(BigDecimal sbsdfi) {
        this.sbsdfi = sbsdfi;
    }
    public String getSbacon() {
        return this.sbacon;
    }
    
    public void setSbacon(String sbacon) {
        this.sbacon = sbacon;
    }
    public BigDecimal getSbcar1() {
        return this.sbcar1;
    }
    
    public void setSbcar1(BigDecimal sbcar1) {
        this.sbcar1 = sbcar1;
    }
    public String getSbmaav() {
        return this.sbmaav;
    }
    
    public void setSbmaav(String sbmaav) {
        this.sbmaav = sbmaav;
    }
    public String getSbmaam() {
        return this.sbmaam;
    }
    
    public void setSbmaam(String sbmaam) {
        this.sbmaam = sbmaam;
    }
    public String getSbusop() {
        return this.sbusop;
    }
    
    public void setSbusop(String sbusop) {
        this.sbusop = sbusop;
    }
    public String getSbusau() {
        return this.sbusau;
    }
    
    public void setSbusau(String sbusau) {
        this.sbusau = sbusau;
    }
    public Integer getSbcono() {
        return this.sbcono;
    }
    
    public void setSbcono(Integer sbcono) {
        this.sbcono = sbcono;
    }
    public Integer getSbaano() {
        return this.sbaano;
    }
    
    public void setSbaano(Integer sbaano) {
        this.sbaano = sbaano;
    }
    public Integer getSbmmno() {
        return this.sbmmno;
    }
    
    public void setSbmmno(Integer sbmmno) {
        this.sbmmno = sbmmno;
    }
    public Integer getSbddno() {
        return this.sbddno;
    }
    
    public void setSbddno(Integer sbddno) {
        this.sbddno = sbddno;
    }
    public Integer getSbcomo() {
        return this.sbcomo;
    }
    
    public void setSbcomo(Integer sbcomo) {
        this.sbcomo = sbcomo;
    }
    public BigDecimal getSbcoti() {
        return this.sbcoti;
    }
    
    public void setSbcoti(BigDecimal sbcoti) {
        this.sbcoti = sbcoti;
    }
    public BigDecimal getSbcopa() {
        return this.sbcopa;
    }
    
    public void setSbcopa(BigDecimal sbcopa) {
        this.sbcopa = sbcopa;
    }
    public BigDecimal getSbisau() {
        return this.sbisau;
    }
    
    public void setSbisau(BigDecimal sbisau) {
        this.sbisau = sbisau;
    }
    public Integer getSbncen() {
        return this.sbncen;
    }
    
    public void setSbncen(Integer sbncen) {
        this.sbncen = sbncen;
    }
    public BigDecimal getSbi9in() {
        return this.sbi9in;
    }
    
    public void setSbi9in(BigDecimal sbi9in) {
        this.sbi9in = sbi9in;
    }
    public BigDecimal getSbi9sv() {
        return this.sbi9sv;
    }
    
    public void setSbi9sv(BigDecimal sbi9sv) {
        this.sbi9sv = sbi9sv;
    }
    public BigDecimal getSbi9ca() {
        return this.sbi9ca;
    }
    
    public void setSbi9ca(BigDecimal sbi9ca) {
        this.sbi9ca = sbi9ca;
    }
    public BigDecimal getSbi9pd() {
        return this.sbi9pd;
    }
    
    public void setSbi9pd(BigDecimal sbi9pd) {
        this.sbi9pd = sbi9pd;
    }
    public BigDecimal getSbi9cd() {
        return this.sbi9cd;
    }
    
    public void setSbi9cd(BigDecimal sbi9cd) {
        this.sbi9cd = sbi9cd;
    }
    public BigDecimal getSbi9pc() {
        return this.sbi9pc;
    }
    
    public void setSbi9pc(BigDecimal sbi9pc) {
        this.sbi9pc = sbi9pc;
    }
    public BigDecimal getSbi9cc() {
        return this.sbi9cc;
    }
    
    public void setSbi9cc(BigDecimal sbi9cc) {
        this.sbi9cc = sbi9cc;
    }
    public BigDecimal getSbi9c1() {
        return this.sbi9c1;
    }
    
    public void setSbi9c1(BigDecimal sbi9c1) {
        this.sbi9c1 = sbi9c1;
    }
    public BigDecimal getSbi9cs() {
        return this.sbi9cs;
    }
    
    public void setSbi9cs(BigDecimal sbi9cs) {
        this.sbi9cs = sbi9cs;
    }
    public BigDecimal getSbi8in() {
        return this.sbi8in;
    }
    
    public void setSbi8in(BigDecimal sbi8in) {
        this.sbi8in = sbi8in;
    }
    public BigDecimal getSbi8sv() {
        return this.sbi8sv;
    }
    
    public void setSbi8sv(BigDecimal sbi8sv) {
        this.sbi8sv = sbi8sv;
    }
    public BigDecimal getSbi8ca() {
        return this.sbi8ca;
    }
    
    public void setSbi8ca(BigDecimal sbi8ca) {
        this.sbi8ca = sbi8ca;
    }
    public BigDecimal getSbi8pd() {
        return this.sbi8pd;
    }
    
    public void setSbi8pd(BigDecimal sbi8pd) {
        this.sbi8pd = sbi8pd;
    }
    public BigDecimal getSbi8cd() {
        return this.sbi8cd;
    }
    
    public void setSbi8cd(BigDecimal sbi8cd) {
        this.sbi8cd = sbi8cd;
    }
    public BigDecimal getSbi8pc() {
        return this.sbi8pc;
    }
    
    public void setSbi8pc(BigDecimal sbi8pc) {
        this.sbi8pc = sbi8pc;
    }
    public BigDecimal getSbi8cc() {
        return this.sbi8cc;
    }
    
    public void setSbi8cc(BigDecimal sbi8cc) {
        this.sbi8cc = sbi8cc;
    }
    public BigDecimal getSbi8c1() {
        return this.sbi8c1;
    }
    
    public void setSbi8c1(BigDecimal sbi8c1) {
        this.sbi8c1 = sbi8c1;
    }
    public BigDecimal getSbi8cs() {
        return this.sbi8cs;
    }
    
    public void setSbi8cs(BigDecimal sbi8cs) {
        this.sbi8cs = sbi8cs;
    }
    public BigDecimal getSbcsau() {
        return this.sbcsau;
    }
    
    public void setSbcsau(BigDecimal sbcsau) {
        this.sbcsau = sbcsau;
    }
    public BigDecimal getSbcsvi() {
        return this.sbcsvi;
    }
    
    public void setSbcsvi(BigDecimal sbcsvi) {
        this.sbcsvi = sbcsvi;
    }
    public BigDecimal getSbauac() {
        return this.sbauac;
    }
    
    public void setSbauac(BigDecimal sbauac) {
        this.sbauac = sbauac;
    }
    public BigDecimal getSbc8cs() {
        return this.sbc8cs;
    }
    
    public void setSbc8cs(BigDecimal sbc8cs) {
        this.sbc8cs = sbc8cs;
    }
    public BigDecimal getSbc9cs() {
        return this.sbc9cs;
    }
    
    public void setSbc9cs(BigDecimal sbc9cs) {
        this.sbc9cs = sbc9cs;
    }




}


