package com.ciessa.museum.model.legacy;
// Generated Dec 11, 2018 7:50:29 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Ccrpcar generated by hbm2java
 */
public class Ccrpcar  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer rvbanc;
     private Integer rvnmov;
     private Long rvnucr;
     private Integer rvncuo;
     private Integer rvsbnc;
     private Integer rvdtem;
     private Integer rvcsup;
     private String rvfpcu;
     private BigDecimal rvimap;
     private BigDecimal rvimbp;
     private BigDecimal rvicap;
     private BigDecimal rvicip;
     private BigDecimal rvisvp;
     private BigDecimal rviccp;
     private BigDecimal rviisp;
     private BigDecimal rviipp;
     private BigDecimal rviicp;
     private BigDecimal rvcarp;
     private BigDecimal rvisap;
     private BigDecimal rvi9ip;
     private BigDecimal rvi9vp;
     private BigDecimal rvi9ca;
     private BigDecimal rvi9pp;
     private BigDecimal rvi9op;
     private BigDecimal rvi9gp;
     private BigDecimal rvi9sp;
     private BigDecimal rvi8ip;
     private BigDecimal rvi8vp;
     private BigDecimal rvi8ca;
     private BigDecimal rvi8pp;
     private BigDecimal rvi8op;
     private BigDecimal rvi8gp;
     private BigDecimal rvi8sp;

    public Ccrpcar() {
    }

	
    public Ccrpcar(String pkid) {
        this.pkid = pkid;
    }
    public Ccrpcar(String pkid, String member, Integer rvbanc, Integer rvnmov, Long rvnucr, Integer rvncuo, Integer rvsbnc, Integer rvdtem, Integer rvcsup, String rvfpcu, BigDecimal rvimap, BigDecimal rvimbp, BigDecimal rvicap, BigDecimal rvicip, BigDecimal rvisvp, BigDecimal rviccp, BigDecimal rviisp, BigDecimal rviipp, BigDecimal rviicp, BigDecimal rvcarp, BigDecimal rvisap, BigDecimal rvi9ip, BigDecimal rvi9vp, BigDecimal rvi9ca, BigDecimal rvi9pp, BigDecimal rvi9op, BigDecimal rvi9gp, BigDecimal rvi9sp, BigDecimal rvi8ip, BigDecimal rvi8vp, BigDecimal rvi8ca, BigDecimal rvi8pp, BigDecimal rvi8op, BigDecimal rvi8gp, BigDecimal rvi8sp) {
       this.pkid = pkid;
       this.member = member;
       this.rvbanc = rvbanc;
       this.rvnmov = rvnmov;
       this.rvnucr = rvnucr;
       this.rvncuo = rvncuo;
       this.rvsbnc = rvsbnc;
       this.rvdtem = rvdtem;
       this.rvcsup = rvcsup;
       this.rvfpcu = rvfpcu;
       this.rvimap = rvimap;
       this.rvimbp = rvimbp;
       this.rvicap = rvicap;
       this.rvicip = rvicip;
       this.rvisvp = rvisvp;
       this.rviccp = rviccp;
       this.rviisp = rviisp;
       this.rviipp = rviipp;
       this.rviicp = rviicp;
       this.rvcarp = rvcarp;
       this.rvisap = rvisap;
       this.rvi9ip = rvi9ip;
       this.rvi9vp = rvi9vp;
       this.rvi9ca = rvi9ca;
       this.rvi9pp = rvi9pp;
       this.rvi9op = rvi9op;
       this.rvi9gp = rvi9gp;
       this.rvi9sp = rvi9sp;
       this.rvi8ip = rvi8ip;
       this.rvi8vp = rvi8vp;
       this.rvi8ca = rvi8ca;
       this.rvi8pp = rvi8pp;
       this.rvi8op = rvi8op;
       this.rvi8gp = rvi8gp;
       this.rvi8sp = rvi8sp;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getRvbanc() {
        return this.rvbanc;
    }
    
    public void setRvbanc(Integer rvbanc) {
        this.rvbanc = rvbanc;
    }
    public Integer getRvnmov() {
        return this.rvnmov;
    }
    
    public void setRvnmov(Integer rvnmov) {
        this.rvnmov = rvnmov;
    }
    public Long getRvnucr() {
        return this.rvnucr;
    }
    
    public void setRvnucr(Long rvnucr) {
        this.rvnucr = rvnucr;
    }
    public Integer getRvncuo() {
        return this.rvncuo;
    }
    
    public void setRvncuo(Integer rvncuo) {
        this.rvncuo = rvncuo;
    }
    public Integer getRvsbnc() {
        return this.rvsbnc;
    }
    
    public void setRvsbnc(Integer rvsbnc) {
        this.rvsbnc = rvsbnc;
    }
    public Integer getRvdtem() {
        return this.rvdtem;
    }
    
    public void setRvdtem(Integer rvdtem) {
        this.rvdtem = rvdtem;
    }
    public Integer getRvcsup() {
        return this.rvcsup;
    }
    
    public void setRvcsup(Integer rvcsup) {
        this.rvcsup = rvcsup;
    }
    public String getRvfpcu() {
        return this.rvfpcu;
    }
    
    public void setRvfpcu(String rvfpcu) {
        this.rvfpcu = rvfpcu;
    }
    public BigDecimal getRvimap() {
        return this.rvimap;
    }
    
    public void setRvimap(BigDecimal rvimap) {
        this.rvimap = rvimap;
    }
    public BigDecimal getRvimbp() {
        return this.rvimbp;
    }
    
    public void setRvimbp(BigDecimal rvimbp) {
        this.rvimbp = rvimbp;
    }
    public BigDecimal getRvicap() {
        return this.rvicap;
    }
    
    public void setRvicap(BigDecimal rvicap) {
        this.rvicap = rvicap;
    }
    public BigDecimal getRvicip() {
        return this.rvicip;
    }
    
    public void setRvicip(BigDecimal rvicip) {
        this.rvicip = rvicip;
    }
    public BigDecimal getRvisvp() {
        return this.rvisvp;
    }
    
    public void setRvisvp(BigDecimal rvisvp) {
        this.rvisvp = rvisvp;
    }
    public BigDecimal getRviccp() {
        return this.rviccp;
    }
    
    public void setRviccp(BigDecimal rviccp) {
        this.rviccp = rviccp;
    }
    public BigDecimal getRviisp() {
        return this.rviisp;
    }
    
    public void setRviisp(BigDecimal rviisp) {
        this.rviisp = rviisp;
    }
    public BigDecimal getRviipp() {
        return this.rviipp;
    }
    
    public void setRviipp(BigDecimal rviipp) {
        this.rviipp = rviipp;
    }
    public BigDecimal getRviicp() {
        return this.rviicp;
    }
    
    public void setRviicp(BigDecimal rviicp) {
        this.rviicp = rviicp;
    }
    public BigDecimal getRvcarp() {
        return this.rvcarp;
    }
    
    public void setRvcarp(BigDecimal rvcarp) {
        this.rvcarp = rvcarp;
    }
    public BigDecimal getRvisap() {
        return this.rvisap;
    }
    
    public void setRvisap(BigDecimal rvisap) {
        this.rvisap = rvisap;
    }
    public BigDecimal getRvi9ip() {
        return this.rvi9ip;
    }
    
    public void setRvi9ip(BigDecimal rvi9ip) {
        this.rvi9ip = rvi9ip;
    }
    public BigDecimal getRvi9vp() {
        return this.rvi9vp;
    }
    
    public void setRvi9vp(BigDecimal rvi9vp) {
        this.rvi9vp = rvi9vp;
    }
    public BigDecimal getRvi9ca() {
        return this.rvi9ca;
    }
    
    public void setRvi9ca(BigDecimal rvi9ca) {
        this.rvi9ca = rvi9ca;
    }
    public BigDecimal getRvi9pp() {
        return this.rvi9pp;
    }
    
    public void setRvi9pp(BigDecimal rvi9pp) {
        this.rvi9pp = rvi9pp;
    }
    public BigDecimal getRvi9op() {
        return this.rvi9op;
    }
    
    public void setRvi9op(BigDecimal rvi9op) {
        this.rvi9op = rvi9op;
    }
    public BigDecimal getRvi9gp() {
        return this.rvi9gp;
    }
    
    public void setRvi9gp(BigDecimal rvi9gp) {
        this.rvi9gp = rvi9gp;
    }
    public BigDecimal getRvi9sp() {
        return this.rvi9sp;
    }
    
    public void setRvi9sp(BigDecimal rvi9sp) {
        this.rvi9sp = rvi9sp;
    }
    public BigDecimal getRvi8ip() {
        return this.rvi8ip;
    }
    
    public void setRvi8ip(BigDecimal rvi8ip) {
        this.rvi8ip = rvi8ip;
    }
    public BigDecimal getRvi8vp() {
        return this.rvi8vp;
    }
    
    public void setRvi8vp(BigDecimal rvi8vp) {
        this.rvi8vp = rvi8vp;
    }
    public BigDecimal getRvi8ca() {
        return this.rvi8ca;
    }
    
    public void setRvi8ca(BigDecimal rvi8ca) {
        this.rvi8ca = rvi8ca;
    }
    public BigDecimal getRvi8pp() {
        return this.rvi8pp;
    }
    
    public void setRvi8pp(BigDecimal rvi8pp) {
        this.rvi8pp = rvi8pp;
    }
    public BigDecimal getRvi8op() {
        return this.rvi8op;
    }
    
    public void setRvi8op(BigDecimal rvi8op) {
        this.rvi8op = rvi8op;
    }
    public BigDecimal getRvi8gp() {
        return this.rvi8gp;
    }
    
    public void setRvi8gp(BigDecimal rvi8gp) {
        this.rvi8gp = rvi8gp;
    }
    public BigDecimal getRvi8sp() {
        return this.rvi8sp;
    }
    
    public void setRvi8sp(BigDecimal rvi8sp) {
        this.rvi8sp = rvi8sp;
    }




}


