package com.ciessa.museum.model.legacy;
// Generated Mar 7, 2018 5:59:21 PM by Hibernate Tools 3.2.2.GA

/**
 * Ccrpcal generated by hbm2java
 */
public class Ccrpcal implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = -8110435030856695686L;

	private String pkid;
	private String member;
	private Integer año;
	private Integer mes;
	private Integer dia;
	private Integer numdia;
	private String indlab;
	private Integer diaaño;
	private String indban;
	private String indcam;
	private String indbur;
	private Integer nrohab;
	private Integer nrolab;
	private Integer nrocam;
	private Integer nrobur;
	private Integer dfjul;

	public Ccrpcal() {
	}

	public Ccrpcal(String pkid) {
		this.pkid = pkid;
	}

	public Ccrpcal(String pkid, String member, Integer año, Integer mes, Integer dia, Integer numdia, String indlab,
			Integer diaaño, String indban, String indcam, String indbur, Integer nrohab, Integer nrolab, Integer nrocam,
			Integer nrobur, Integer dfjul) {
		this.pkid = pkid;
		this.member = member;
		this.año = año;
		this.mes = mes;
		this.dia = dia;
		this.numdia = numdia;
		this.indlab = indlab;
		this.diaaño = diaaño;
		this.indban = indban;
		this.indcam = indcam;
		this.indbur = indbur;
		this.nrohab = nrohab;
		this.nrolab = nrolab;
		this.nrocam = nrocam;
		this.nrobur = nrobur;
		this.dfjul = dfjul;
	}

	public String getPkid() {
		return this.pkid;
	}

	public void setPkid(String pkid) {
		this.pkid = pkid;
	}

	public String getMember() {
		return this.member;
	}

	public void setMember(String member) {
		this.member = member;
	}

	public Integer getAño() {
		return this.año;
	}

	public void setAño(Integer año) {
		this.año = año;
	}

	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	public Integer getNumdia() {
		return this.numdia;
	}

	public void setNumdia(Integer numdia) {
		this.numdia = numdia;
	}

	public String getIndlab() {
		return this.indlab;
	}

	public void setIndlab(String indlab) {
		this.indlab = indlab;
	}

	public Integer getDiaaño() {
		return this.diaaño;
	}

	public void setDiaaño(Integer diaaño) {
		this.diaaño = diaaño;
	}

	public String getIndban() {
		return this.indban;
	}

	public void setIndban(String indban) {
		this.indban = indban;
	}

	public String getIndcam() {
		return this.indcam;
	}

	public void setIndcam(String indcam) {
		this.indcam = indcam;
	}

	public String getIndbur() {
		return this.indbur;
	}

	public void setIndbur(String indbur) {
		this.indbur = indbur;
	}

	public Integer getNrohab() {
		return this.nrohab;
	}

	public void setNrohab(Integer nrohab) {
		this.nrohab = nrohab;
	}

	public Integer getNrolab() {
		return this.nrolab;
	}

	public void setNrolab(Integer nrolab) {
		this.nrolab = nrolab;
	}

	public Integer getNrocam() {
		return this.nrocam;
	}

	public void setNrocam(Integer nrocam) {
		this.nrocam = nrocam;
	}

	public Integer getNrobur() {
		return this.nrobur;
	}

	public void setNrobur(Integer nrobur) {
		this.nrobur = nrobur;
	}

	public Integer getDfjul() {
		return this.dfjul;
	}

	public void setDfjul(Integer dfjul) {
		this.dfjul = dfjul;
	}

}
