package com.ciessa.museum.model.legacy;
// Generated Aug 28, 2018 8:42:07 PM by Hibernate Tools 3.2.2.GA



/**
 * Ccrpcal generated by hbm2java
 */
public class Ccrpcal  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer ano;
     private Integer mes;
     private Integer dia;
     private Integer numdia;
     private String indlab;
     private Integer diaano;
     private String indban;
     private String indcam;
     private String indbur;
     private Integer nrohab;
     private Integer nrolab;
     private Integer nrocam;
     private Integer nrobur;
     private Integer dfjul;

    public Ccrpcal() {
    }

	
    public Ccrpcal(String pkid) {
        this.pkid = pkid;
    }
    public Ccrpcal(String pkid, String member, Integer ano, Integer mes, Integer dia, Integer numdia, String indlab, Integer diaano, String indban, String indcam, String indbur, Integer nrohab, Integer nrolab, Integer nrocam, Integer nrobur, Integer dfjul) {
       this.pkid = pkid;
       this.member = member;
       this.ano = ano;
       this.mes = mes;
       this.dia = dia;
       this.numdia = numdia;
       this.indlab = indlab;
       this.diaano = diaano;
       this.indban = indban;
       this.indcam = indcam;
       this.indbur = indbur;
       this.nrohab = nrohab;
       this.nrolab = nrolab;
       this.nrocam = nrocam;
       this.nrobur = nrobur;
       this.dfjul = dfjul;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Integer getDia() {
        return this.dia;
    }
    
    public void setDia(Integer dia) {
        this.dia = dia;
    }
    public Integer getNumdia() {
        return this.numdia;
    }
    
    public void setNumdia(Integer numdia) {
        this.numdia = numdia;
    }
    public String getIndlab() {
        return this.indlab;
    }
    
    public void setIndlab(String indlab) {
        this.indlab = indlab;
    }
    public Integer getDiaano() {
        return this.diaano;
    }
    
    public void setDiaano(Integer diaano) {
        this.diaano = diaano;
    }
    public String getIndban() {
        return this.indban;
    }
    
    public void setIndban(String indban) {
        this.indban = indban;
    }
    public String getIndcam() {
        return this.indcam;
    }
    
    public void setIndcam(String indcam) {
        this.indcam = indcam;
    }
    public String getIndbur() {
        return this.indbur;
    }
    
    public void setIndbur(String indbur) {
        this.indbur = indbur;
    }
    public Integer getNrohab() {
        return this.nrohab;
    }
    
    public void setNrohab(Integer nrohab) {
        this.nrohab = nrohab;
    }
    public Integer getNrolab() {
        return this.nrolab;
    }
    
    public void setNrolab(Integer nrolab) {
        this.nrolab = nrolab;
    }
    public Integer getNrocam() {
        return this.nrocam;
    }
    
    public void setNrocam(Integer nrocam) {
        this.nrocam = nrocam;
    }
    public Integer getNrobur() {
        return this.nrobur;
    }
    
    public void setNrobur(Integer nrobur) {
        this.nrobur = nrobur;
    }
    public Integer getDfjul() {
        return this.dfjul;
    }
    
    public void setDfjul(Integer dfjul) {
        this.dfjul = dfjul;
    }




}


