package com.ciessa.museum.model.legacy;
// Generated Jul 13, 2018 12:00:44 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Ccrppro generated by hbm2java
 */
public class Ccrppro  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer orbanc;
     private String orcapi;
     private Integer orline;
     private Integer ortrta;
     private Integer ortrin;
     private Integer orcoaj;
     private Integer orctai;
     private Integer orcina;
     private BigDecimal orica1;
     private BigDecimal orica2;
     private BigDecimal orica3;
     private BigDecimal oricac;
     private String ortipr;
     private String ormmiv;
     private Integer orqdan;
     private String ormica;
     private String ordepr;
     private Integer oraapr;
     private Integer ormmpr;
     private Integer orddpr;
     private String orstpr;
     private Integer oraaep;
     private Integer ormmep;
     private Integer orddep;
     private String ororfo;
     private String orcfou;
     private Integer orcomo;
     private Integer orbkco;
     private Integer orcsel;
     private Integer orcose;
     private Integer orcopc;
     private BigDecimal orpca1;
     private BigDecimal orpca2;
     private BigDecimal orpca3;
     private BigDecimal orpcca;
     private Integer orcoc1;
     private Integer orcoc2;
     private Integer orcoc3;
     private Integer orcoca;
     private Integer ordpdo;
     private Integer ordnac;
     private Integer ordwro;
     private BigDecimal orvtmi;
     private BigDecimal orvtma;
     private Integer orccca;
     private Integer orccin;
     private Integer orccaj;
     private Integer orccic;
     private Integer orccip;
     private Integer orccri;
     private Integer orccra;
     private Integer orccrc;
     private Integer orcrip;
     private Integer orcipo;
     private Integer orcpca;
     private Integer orcpin;
     private Integer orcpaj;
     private Integer orcicp;
     private Integer orcpip;
     private Integer orcpri;
     private Integer orcpra;
     private Integer orcrcp;
     private Integer orcpiu;
     private Integer orcpil;
     private Integer orcnca;
     private Integer orcnin;
     private Integer orcnaj;
     private Integer orcnra;
     private Integer orcnil;
     private Integer orccwo;
     private Integer orccob;
     private Integer orccse;
     private Integer orcigp;
     private Integer orcaig;
     private String orusop;
     private String orusau;
     private Integer ortipo;
     private String oremp;
     private Integer orciv1;
     private Integer orciv2;
     private Integer orciv3;
     private Integer orciv4;
     private Integer orciv5;
     private String ormcol;
     private String ormcoo;
     private String ormcon;
     private Integer orcdca;
     private Integer orcdig;
     private Integer orcdme;
     private Integer orcrwo;
     private Integer orcta1;
     private Integer orcta2;
     private Integer orcta3;
     private String orsbtp;
     private String orreqs;
     private String orprcd;
     private Integer orpvfc;
     private Integer orpvfa;
     private Integer orctsf;
     private Integer orcpzi;
     private Integer orcpzx;
     private String orpdoc;

    public Ccrppro() {
    }

	
    public Ccrppro(String pkid) {
        this.pkid = pkid;
    }
    public Ccrppro(String pkid, String member, Integer orbanc, String orcapi, Integer orline, Integer ortrta, Integer ortrin, Integer orcoaj, Integer orctai, Integer orcina, BigDecimal orica1, BigDecimal orica2, BigDecimal orica3, BigDecimal oricac, String ortipr, String ormmiv, Integer orqdan, String ormica, String ordepr, Integer oraapr, Integer ormmpr, Integer orddpr, String orstpr, Integer oraaep, Integer ormmep, Integer orddep, String ororfo, String orcfou, Integer orcomo, Integer orbkco, Integer orcsel, Integer orcose, Integer orcopc, BigDecimal orpca1, BigDecimal orpca2, BigDecimal orpca3, BigDecimal orpcca, Integer orcoc1, Integer orcoc2, Integer orcoc3, Integer orcoca, Integer ordpdo, Integer ordnac, Integer ordwro, BigDecimal orvtmi, BigDecimal orvtma, Integer orccca, Integer orccin, Integer orccaj, Integer orccic, Integer orccip, Integer orccri, Integer orccra, Integer orccrc, Integer orcrip, Integer orcipo, Integer orcpca, Integer orcpin, Integer orcpaj, Integer orcicp, Integer orcpip, Integer orcpri, Integer orcpra, Integer orcrcp, Integer orcpiu, Integer orcpil, Integer orcnca, Integer orcnin, Integer orcnaj, Integer orcnra, Integer orcnil, Integer orccwo, Integer orccob, Integer orccse, Integer orcigp, Integer orcaig, String orusop, String orusau, Integer ortipo, String oremp, Integer orciv1, Integer orciv2, Integer orciv3, Integer orciv4, Integer orciv5, String ormcol, String ormcoo, String ormcon, Integer orcdca, Integer orcdig, Integer orcdme, Integer orcrwo, Integer orcta1, Integer orcta2, Integer orcta3, String orsbtp, String orreqs, String orprcd, Integer orpvfc, Integer orpvfa, Integer orctsf, Integer orcpzi, Integer orcpzx, String orpdoc) {
       this.pkid = pkid;
       this.member = member;
       this.orbanc = orbanc;
       this.orcapi = orcapi;
       this.orline = orline;
       this.ortrta = ortrta;
       this.ortrin = ortrin;
       this.orcoaj = orcoaj;
       this.orctai = orctai;
       this.orcina = orcina;
       this.orica1 = orica1;
       this.orica2 = orica2;
       this.orica3 = orica3;
       this.oricac = oricac;
       this.ortipr = ortipr;
       this.ormmiv = ormmiv;
       this.orqdan = orqdan;
       this.ormica = ormica;
       this.ordepr = ordepr;
       this.oraapr = oraapr;
       this.ormmpr = ormmpr;
       this.orddpr = orddpr;
       this.orstpr = orstpr;
       this.oraaep = oraaep;
       this.ormmep = ormmep;
       this.orddep = orddep;
       this.ororfo = ororfo;
       this.orcfou = orcfou;
       this.orcomo = orcomo;
       this.orbkco = orbkco;
       this.orcsel = orcsel;
       this.orcose = orcose;
       this.orcopc = orcopc;
       this.orpca1 = orpca1;
       this.orpca2 = orpca2;
       this.orpca3 = orpca3;
       this.orpcca = orpcca;
       this.orcoc1 = orcoc1;
       this.orcoc2 = orcoc2;
       this.orcoc3 = orcoc3;
       this.orcoca = orcoca;
       this.ordpdo = ordpdo;
       this.ordnac = ordnac;
       this.ordwro = ordwro;
       this.orvtmi = orvtmi;
       this.orvtma = orvtma;
       this.orccca = orccca;
       this.orccin = orccin;
       this.orccaj = orccaj;
       this.orccic = orccic;
       this.orccip = orccip;
       this.orccri = orccri;
       this.orccra = orccra;
       this.orccrc = orccrc;
       this.orcrip = orcrip;
       this.orcipo = orcipo;
       this.orcpca = orcpca;
       this.orcpin = orcpin;
       this.orcpaj = orcpaj;
       this.orcicp = orcicp;
       this.orcpip = orcpip;
       this.orcpri = orcpri;
       this.orcpra = orcpra;
       this.orcrcp = orcrcp;
       this.orcpiu = orcpiu;
       this.orcpil = orcpil;
       this.orcnca = orcnca;
       this.orcnin = orcnin;
       this.orcnaj = orcnaj;
       this.orcnra = orcnra;
       this.orcnil = orcnil;
       this.orccwo = orccwo;
       this.orccob = orccob;
       this.orccse = orccse;
       this.orcigp = orcigp;
       this.orcaig = orcaig;
       this.orusop = orusop;
       this.orusau = orusau;
       this.ortipo = ortipo;
       this.oremp = oremp;
       this.orciv1 = orciv1;
       this.orciv2 = orciv2;
       this.orciv3 = orciv3;
       this.orciv4 = orciv4;
       this.orciv5 = orciv5;
       this.ormcol = ormcol;
       this.ormcoo = ormcoo;
       this.ormcon = ormcon;
       this.orcdca = orcdca;
       this.orcdig = orcdig;
       this.orcdme = orcdme;
       this.orcrwo = orcrwo;
       this.orcta1 = orcta1;
       this.orcta2 = orcta2;
       this.orcta3 = orcta3;
       this.orsbtp = orsbtp;
       this.orreqs = orreqs;
       this.orprcd = orprcd;
       this.orpvfc = orpvfc;
       this.orpvfa = orpvfa;
       this.orctsf = orctsf;
       this.orcpzi = orcpzi;
       this.orcpzx = orcpzx;
       this.orpdoc = orpdoc;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getOrbanc() {
        return this.orbanc;
    }
    
    public void setOrbanc(Integer orbanc) {
        this.orbanc = orbanc;
    }
    public String getOrcapi() {
        return this.orcapi;
    }
    
    public void setOrcapi(String orcapi) {
        this.orcapi = orcapi;
    }
    public Integer getOrline() {
        return this.orline;
    }
    
    public void setOrline(Integer orline) {
        this.orline = orline;
    }
    public Integer getOrtrta() {
        return this.ortrta;
    }
    
    public void setOrtrta(Integer ortrta) {
        this.ortrta = ortrta;
    }
    public Integer getOrtrin() {
        return this.ortrin;
    }
    
    public void setOrtrin(Integer ortrin) {
        this.ortrin = ortrin;
    }
    public Integer getOrcoaj() {
        return this.orcoaj;
    }
    
    public void setOrcoaj(Integer orcoaj) {
        this.orcoaj = orcoaj;
    }
    public Integer getOrctai() {
        return this.orctai;
    }
    
    public void setOrctai(Integer orctai) {
        this.orctai = orctai;
    }
    public Integer getOrcina() {
        return this.orcina;
    }
    
    public void setOrcina(Integer orcina) {
        this.orcina = orcina;
    }
    public BigDecimal getOrica1() {
        return this.orica1;
    }
    
    public void setOrica1(BigDecimal orica1) {
        this.orica1 = orica1;
    }
    public BigDecimal getOrica2() {
        return this.orica2;
    }
    
    public void setOrica2(BigDecimal orica2) {
        this.orica2 = orica2;
    }
    public BigDecimal getOrica3() {
        return this.orica3;
    }
    
    public void setOrica3(BigDecimal orica3) {
        this.orica3 = orica3;
    }
    public BigDecimal getOricac() {
        return this.oricac;
    }
    
    public void setOricac(BigDecimal oricac) {
        this.oricac = oricac;
    }
    public String getOrtipr() {
        return this.ortipr;
    }
    
    public void setOrtipr(String ortipr) {
        this.ortipr = ortipr;
    }
    public String getOrmmiv() {
        return this.ormmiv;
    }
    
    public void setOrmmiv(String ormmiv) {
        this.ormmiv = ormmiv;
    }
    public Integer getOrqdan() {
        return this.orqdan;
    }
    
    public void setOrqdan(Integer orqdan) {
        this.orqdan = orqdan;
    }
    public String getOrmica() {
        return this.ormica;
    }
    
    public void setOrmica(String ormica) {
        this.ormica = ormica;
    }
    public String getOrdepr() {
        return this.ordepr;
    }
    
    public void setOrdepr(String ordepr) {
        this.ordepr = ordepr;
    }
    public Integer getOraapr() {
        return this.oraapr;
    }
    
    public void setOraapr(Integer oraapr) {
        this.oraapr = oraapr;
    }
    public Integer getOrmmpr() {
        return this.ormmpr;
    }
    
    public void setOrmmpr(Integer ormmpr) {
        this.ormmpr = ormmpr;
    }
    public Integer getOrddpr() {
        return this.orddpr;
    }
    
    public void setOrddpr(Integer orddpr) {
        this.orddpr = orddpr;
    }
    public String getOrstpr() {
        return this.orstpr;
    }
    
    public void setOrstpr(String orstpr) {
        this.orstpr = orstpr;
    }
    public Integer getOraaep() {
        return this.oraaep;
    }
    
    public void setOraaep(Integer oraaep) {
        this.oraaep = oraaep;
    }
    public Integer getOrmmep() {
        return this.ormmep;
    }
    
    public void setOrmmep(Integer ormmep) {
        this.ormmep = ormmep;
    }
    public Integer getOrddep() {
        return this.orddep;
    }
    
    public void setOrddep(Integer orddep) {
        this.orddep = orddep;
    }
    public String getOrorfo() {
        return this.ororfo;
    }
    
    public void setOrorfo(String ororfo) {
        this.ororfo = ororfo;
    }
    public String getOrcfou() {
        return this.orcfou;
    }
    
    public void setOrcfou(String orcfou) {
        this.orcfou = orcfou;
    }
    public Integer getOrcomo() {
        return this.orcomo;
    }
    
    public void setOrcomo(Integer orcomo) {
        this.orcomo = orcomo;
    }
    public Integer getOrbkco() {
        return this.orbkco;
    }
    
    public void setOrbkco(Integer orbkco) {
        this.orbkco = orbkco;
    }
    public Integer getOrcsel() {
        return this.orcsel;
    }
    
    public void setOrcsel(Integer orcsel) {
        this.orcsel = orcsel;
    }
    public Integer getOrcose() {
        return this.orcose;
    }
    
    public void setOrcose(Integer orcose) {
        this.orcose = orcose;
    }
    public Integer getOrcopc() {
        return this.orcopc;
    }
    
    public void setOrcopc(Integer orcopc) {
        this.orcopc = orcopc;
    }
    public BigDecimal getOrpca1() {
        return this.orpca1;
    }
    
    public void setOrpca1(BigDecimal orpca1) {
        this.orpca1 = orpca1;
    }
    public BigDecimal getOrpca2() {
        return this.orpca2;
    }
    
    public void setOrpca2(BigDecimal orpca2) {
        this.orpca2 = orpca2;
    }
    public BigDecimal getOrpca3() {
        return this.orpca3;
    }
    
    public void setOrpca3(BigDecimal orpca3) {
        this.orpca3 = orpca3;
    }
    public BigDecimal getOrpcca() {
        return this.orpcca;
    }
    
    public void setOrpcca(BigDecimal orpcca) {
        this.orpcca = orpcca;
    }
    public Integer getOrcoc1() {
        return this.orcoc1;
    }
    
    public void setOrcoc1(Integer orcoc1) {
        this.orcoc1 = orcoc1;
    }
    public Integer getOrcoc2() {
        return this.orcoc2;
    }
    
    public void setOrcoc2(Integer orcoc2) {
        this.orcoc2 = orcoc2;
    }
    public Integer getOrcoc3() {
        return this.orcoc3;
    }
    
    public void setOrcoc3(Integer orcoc3) {
        this.orcoc3 = orcoc3;
    }
    public Integer getOrcoca() {
        return this.orcoca;
    }
    
    public void setOrcoca(Integer orcoca) {
        this.orcoca = orcoca;
    }
    public Integer getOrdpdo() {
        return this.ordpdo;
    }
    
    public void setOrdpdo(Integer ordpdo) {
        this.ordpdo = ordpdo;
    }
    public Integer getOrdnac() {
        return this.ordnac;
    }
    
    public void setOrdnac(Integer ordnac) {
        this.ordnac = ordnac;
    }
    public Integer getOrdwro() {
        return this.ordwro;
    }
    
    public void setOrdwro(Integer ordwro) {
        this.ordwro = ordwro;
    }
    public BigDecimal getOrvtmi() {
        return this.orvtmi;
    }
    
    public void setOrvtmi(BigDecimal orvtmi) {
        this.orvtmi = orvtmi;
    }
    public BigDecimal getOrvtma() {
        return this.orvtma;
    }
    
    public void setOrvtma(BigDecimal orvtma) {
        this.orvtma = orvtma;
    }
    public Integer getOrccca() {
        return this.orccca;
    }
    
    public void setOrccca(Integer orccca) {
        this.orccca = orccca;
    }
    public Integer getOrccin() {
        return this.orccin;
    }
    
    public void setOrccin(Integer orccin) {
        this.orccin = orccin;
    }
    public Integer getOrccaj() {
        return this.orccaj;
    }
    
    public void setOrccaj(Integer orccaj) {
        this.orccaj = orccaj;
    }
    public Integer getOrccic() {
        return this.orccic;
    }
    
    public void setOrccic(Integer orccic) {
        this.orccic = orccic;
    }
    public Integer getOrccip() {
        return this.orccip;
    }
    
    public void setOrccip(Integer orccip) {
        this.orccip = orccip;
    }
    public Integer getOrccri() {
        return this.orccri;
    }
    
    public void setOrccri(Integer orccri) {
        this.orccri = orccri;
    }
    public Integer getOrccra() {
        return this.orccra;
    }
    
    public void setOrccra(Integer orccra) {
        this.orccra = orccra;
    }
    public Integer getOrccrc() {
        return this.orccrc;
    }
    
    public void setOrccrc(Integer orccrc) {
        this.orccrc = orccrc;
    }
    public Integer getOrcrip() {
        return this.orcrip;
    }
    
    public void setOrcrip(Integer orcrip) {
        this.orcrip = orcrip;
    }
    public Integer getOrcipo() {
        return this.orcipo;
    }
    
    public void setOrcipo(Integer orcipo) {
        this.orcipo = orcipo;
    }
    public Integer getOrcpca() {
        return this.orcpca;
    }
    
    public void setOrcpca(Integer orcpca) {
        this.orcpca = orcpca;
    }
    public Integer getOrcpin() {
        return this.orcpin;
    }
    
    public void setOrcpin(Integer orcpin) {
        this.orcpin = orcpin;
    }
    public Integer getOrcpaj() {
        return this.orcpaj;
    }
    
    public void setOrcpaj(Integer orcpaj) {
        this.orcpaj = orcpaj;
    }
    public Integer getOrcicp() {
        return this.orcicp;
    }
    
    public void setOrcicp(Integer orcicp) {
        this.orcicp = orcicp;
    }
    public Integer getOrcpip() {
        return this.orcpip;
    }
    
    public void setOrcpip(Integer orcpip) {
        this.orcpip = orcpip;
    }
    public Integer getOrcpri() {
        return this.orcpri;
    }
    
    public void setOrcpri(Integer orcpri) {
        this.orcpri = orcpri;
    }
    public Integer getOrcpra() {
        return this.orcpra;
    }
    
    public void setOrcpra(Integer orcpra) {
        this.orcpra = orcpra;
    }
    public Integer getOrcrcp() {
        return this.orcrcp;
    }
    
    public void setOrcrcp(Integer orcrcp) {
        this.orcrcp = orcrcp;
    }
    public Integer getOrcpiu() {
        return this.orcpiu;
    }
    
    public void setOrcpiu(Integer orcpiu) {
        this.orcpiu = orcpiu;
    }
    public Integer getOrcpil() {
        return this.orcpil;
    }
    
    public void setOrcpil(Integer orcpil) {
        this.orcpil = orcpil;
    }
    public Integer getOrcnca() {
        return this.orcnca;
    }
    
    public void setOrcnca(Integer orcnca) {
        this.orcnca = orcnca;
    }
    public Integer getOrcnin() {
        return this.orcnin;
    }
    
    public void setOrcnin(Integer orcnin) {
        this.orcnin = orcnin;
    }
    public Integer getOrcnaj() {
        return this.orcnaj;
    }
    
    public void setOrcnaj(Integer orcnaj) {
        this.orcnaj = orcnaj;
    }
    public Integer getOrcnra() {
        return this.orcnra;
    }
    
    public void setOrcnra(Integer orcnra) {
        this.orcnra = orcnra;
    }
    public Integer getOrcnil() {
        return this.orcnil;
    }
    
    public void setOrcnil(Integer orcnil) {
        this.orcnil = orcnil;
    }
    public Integer getOrccwo() {
        return this.orccwo;
    }
    
    public void setOrccwo(Integer orccwo) {
        this.orccwo = orccwo;
    }
    public Integer getOrccob() {
        return this.orccob;
    }
    
    public void setOrccob(Integer orccob) {
        this.orccob = orccob;
    }
    public Integer getOrccse() {
        return this.orccse;
    }
    
    public void setOrccse(Integer orccse) {
        this.orccse = orccse;
    }
    public Integer getOrcigp() {
        return this.orcigp;
    }
    
    public void setOrcigp(Integer orcigp) {
        this.orcigp = orcigp;
    }
    public Integer getOrcaig() {
        return this.orcaig;
    }
    
    public void setOrcaig(Integer orcaig) {
        this.orcaig = orcaig;
    }
    public String getOrusop() {
        return this.orusop;
    }
    
    public void setOrusop(String orusop) {
        this.orusop = orusop;
    }
    public String getOrusau() {
        return this.orusau;
    }
    
    public void setOrusau(String orusau) {
        this.orusau = orusau;
    }
    public Integer getOrtipo() {
        return this.ortipo;
    }
    
    public void setOrtipo(Integer ortipo) {
        this.ortipo = ortipo;
    }
    public String getOremp() {
        return this.oremp;
    }
    
    public void setOremp(String oremp) {
        this.oremp = oremp;
    }
    public Integer getOrciv1() {
        return this.orciv1;
    }
    
    public void setOrciv1(Integer orciv1) {
        this.orciv1 = orciv1;
    }
    public Integer getOrciv2() {
        return this.orciv2;
    }
    
    public void setOrciv2(Integer orciv2) {
        this.orciv2 = orciv2;
    }
    public Integer getOrciv3() {
        return this.orciv3;
    }
    
    public void setOrciv3(Integer orciv3) {
        this.orciv3 = orciv3;
    }
    public Integer getOrciv4() {
        return this.orciv4;
    }
    
    public void setOrciv4(Integer orciv4) {
        this.orciv4 = orciv4;
    }
    public Integer getOrciv5() {
        return this.orciv5;
    }
    
    public void setOrciv5(Integer orciv5) {
        this.orciv5 = orciv5;
    }
    public String getOrmcol() {
        return this.ormcol;
    }
    
    public void setOrmcol(String ormcol) {
        this.ormcol = ormcol;
    }
    public String getOrmcoo() {
        return this.ormcoo;
    }
    
    public void setOrmcoo(String ormcoo) {
        this.ormcoo = ormcoo;
    }
    public String getOrmcon() {
        return this.ormcon;
    }
    
    public void setOrmcon(String ormcon) {
        this.ormcon = ormcon;
    }
    public Integer getOrcdca() {
        return this.orcdca;
    }
    
    public void setOrcdca(Integer orcdca) {
        this.orcdca = orcdca;
    }
    public Integer getOrcdig() {
        return this.orcdig;
    }
    
    public void setOrcdig(Integer orcdig) {
        this.orcdig = orcdig;
    }
    public Integer getOrcdme() {
        return this.orcdme;
    }
    
    public void setOrcdme(Integer orcdme) {
        this.orcdme = orcdme;
    }
    public Integer getOrcrwo() {
        return this.orcrwo;
    }
    
    public void setOrcrwo(Integer orcrwo) {
        this.orcrwo = orcrwo;
    }
    public Integer getOrcta1() {
        return this.orcta1;
    }
    
    public void setOrcta1(Integer orcta1) {
        this.orcta1 = orcta1;
    }
    public Integer getOrcta2() {
        return this.orcta2;
    }
    
    public void setOrcta2(Integer orcta2) {
        this.orcta2 = orcta2;
    }
    public Integer getOrcta3() {
        return this.orcta3;
    }
    
    public void setOrcta3(Integer orcta3) {
        this.orcta3 = orcta3;
    }
    public String getOrsbtp() {
        return this.orsbtp;
    }
    
    public void setOrsbtp(String orsbtp) {
        this.orsbtp = orsbtp;
    }
    public String getOrreqs() {
        return this.orreqs;
    }
    
    public void setOrreqs(String orreqs) {
        this.orreqs = orreqs;
    }
    public String getOrprcd() {
        return this.orprcd;
    }
    
    public void setOrprcd(String orprcd) {
        this.orprcd = orprcd;
    }
    public Integer getOrpvfc() {
        return this.orpvfc;
    }
    
    public void setOrpvfc(Integer orpvfc) {
        this.orpvfc = orpvfc;
    }
    public Integer getOrpvfa() {
        return this.orpvfa;
    }
    
    public void setOrpvfa(Integer orpvfa) {
        this.orpvfa = orpvfa;
    }
    public Integer getOrctsf() {
        return this.orctsf;
    }
    
    public void setOrctsf(Integer orctsf) {
        this.orctsf = orctsf;
    }
    public Integer getOrcpzi() {
        return this.orcpzi;
    }
    
    public void setOrcpzi(Integer orcpzi) {
        this.orcpzi = orcpzi;
    }
    public Integer getOrcpzx() {
        return this.orcpzx;
    }
    
    public void setOrcpzx(Integer orcpzx) {
        this.orcpzx = orcpzx;
    }
    public String getOrpdoc() {
        return this.orpdoc;
    }
    
    public void setOrpdoc(String orpdoc) {
        this.orpdoc = orpdoc;
    }




}


