package com.ciessa.museum.model.legacy;
// Generated Sep 13, 2018 8:37:56 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Ccrpsce generated by hbm2java
 */
public class Ccrpsce  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer scbanc;
     private Long scnucr;
     private Integer scncuo;
     private Integer scsbnc;
     private Integer scccon;
     private BigDecimal sciimp;
     private BigDecimal sciimb;
     private BigDecimal sci8im;
     private BigDecimal sci9im;
     private BigDecimal scalic;

    public Ccrpsce() {
    }

	
    public Ccrpsce(String pkid) {
        this.pkid = pkid;
    }
    public Ccrpsce(String pkid, String member, Integer scbanc, Long scnucr, Integer scncuo, Integer scsbnc, Integer scccon, BigDecimal sciimp, BigDecimal sciimb, BigDecimal sci8im, BigDecimal sci9im, BigDecimal scalic) {
       this.pkid = pkid;
       this.member = member;
       this.scbanc = scbanc;
       this.scnucr = scnucr;
       this.scncuo = scncuo;
       this.scsbnc = scsbnc;
       this.scccon = scccon;
       this.sciimp = sciimp;
       this.sciimb = sciimb;
       this.sci8im = sci8im;
       this.sci9im = sci9im;
       this.scalic = scalic;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getScbanc() {
        return this.scbanc;
    }
    
    public void setScbanc(Integer scbanc) {
        this.scbanc = scbanc;
    }
    public Long getScnucr() {
        return this.scnucr;
    }
    
    public void setScnucr(Long scnucr) {
        this.scnucr = scnucr;
    }
    public Integer getScncuo() {
        return this.scncuo;
    }
    
    public void setScncuo(Integer scncuo) {
        this.scncuo = scncuo;
    }
    public Integer getScsbnc() {
        return this.scsbnc;
    }
    
    public void setScsbnc(Integer scsbnc) {
        this.scsbnc = scsbnc;
    }
    public Integer getScccon() {
        return this.scccon;
    }
    
    public void setScccon(Integer scccon) {
        this.scccon = scccon;
    }
    public BigDecimal getSciimp() {
        return this.sciimp;
    }
    
    public void setSciimp(BigDecimal sciimp) {
        this.sciimp = sciimp;
    }
    public BigDecimal getSciimb() {
        return this.sciimb;
    }
    
    public void setSciimb(BigDecimal sciimb) {
        this.sciimb = sciimb;
    }
    public BigDecimal getSci8im() {
        return this.sci8im;
    }
    
    public void setSci8im(BigDecimal sci8im) {
        this.sci8im = sci8im;
    }
    public BigDecimal getSci9im() {
        return this.sci9im;
    }
    
    public void setSci9im(BigDecimal sci9im) {
        this.sci9im = sci9im;
    }
    public BigDecimal getScalic() {
        return this.scalic;
    }
    
    public void setScalic(BigDecimal scalic) {
        this.scalic = scalic;
    }




}


