package com.ciessa.museum.model.legacy;
// Generated Dec 11, 2018 7:50:29 PM by Hibernate Tools 3.2.2.GA



/**
 * Ccupgin generated by hbm2java
 */
public class Ccupgin  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String giempp;
     private String giidgi;
     private String gistat;
     private String gidegi;
     private Integer gifal8;
     private String givusr;
     private String gistnm;
     private Integer gistrn;
     private String gistyn;
     private String giadcm;
     private String gicity;
     private String gistan;
     private Integer gizpcd;
     private Integer giqmbf;
     private Integer giqmbl;
     private Integer giqchd;
     private Integer giqcjf;
     private Integer giqott;
     private Integer gimdte;
     private Integer gimtme;
     private String gimusr;
     private String gimtrm;
     private Integer giadte;
     private Integer giatme;
     private String giausr;
     private String giatrm;
     private Long girmcn;
     private String giciin;
     private String gibtrf;
     private String gibocp;
     private String gicone;
     private String giccoe;
     private Long gip1pn;
     private String giadic;
     private String giembo;

    public Ccupgin() {
    }

	
    public Ccupgin(String pkid) {
        this.pkid = pkid;
    }
    public Ccupgin(String pkid, String member, String giempp, String giidgi, String gistat, String gidegi, Integer gifal8, String givusr, String gistnm, Integer gistrn, String gistyn, String giadcm, String gicity, String gistan, Integer gizpcd, Integer giqmbf, Integer giqmbl, Integer giqchd, Integer giqcjf, Integer giqott, Integer gimdte, Integer gimtme, String gimusr, String gimtrm, Integer giadte, Integer giatme, String giausr, String giatrm, Long girmcn, String giciin, String gibtrf, String gibocp, String gicone, String giccoe, Long gip1pn, String giadic, String giembo) {
       this.pkid = pkid;
       this.member = member;
       this.giempp = giempp;
       this.giidgi = giidgi;
       this.gistat = gistat;
       this.gidegi = gidegi;
       this.gifal8 = gifal8;
       this.givusr = givusr;
       this.gistnm = gistnm;
       this.gistrn = gistrn;
       this.gistyn = gistyn;
       this.giadcm = giadcm;
       this.gicity = gicity;
       this.gistan = gistan;
       this.gizpcd = gizpcd;
       this.giqmbf = giqmbf;
       this.giqmbl = giqmbl;
       this.giqchd = giqchd;
       this.giqcjf = giqcjf;
       this.giqott = giqott;
       this.gimdte = gimdte;
       this.gimtme = gimtme;
       this.gimusr = gimusr;
       this.gimtrm = gimtrm;
       this.giadte = giadte;
       this.giatme = giatme;
       this.giausr = giausr;
       this.giatrm = giatrm;
       this.girmcn = girmcn;
       this.giciin = giciin;
       this.gibtrf = gibtrf;
       this.gibocp = gibocp;
       this.gicone = gicone;
       this.giccoe = giccoe;
       this.gip1pn = gip1pn;
       this.giadic = giadic;
       this.giembo = giembo;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getGiempp() {
        return this.giempp;
    }
    
    public void setGiempp(String giempp) {
        this.giempp = giempp;
    }
    public String getGiidgi() {
        return this.giidgi;
    }
    
    public void setGiidgi(String giidgi) {
        this.giidgi = giidgi;
    }
    public String getGistat() {
        return this.gistat;
    }
    
    public void setGistat(String gistat) {
        this.gistat = gistat;
    }
    public String getGidegi() {
        return this.gidegi;
    }
    
    public void setGidegi(String gidegi) {
        this.gidegi = gidegi;
    }
    public Integer getGifal8() {
        return this.gifal8;
    }
    
    public void setGifal8(Integer gifal8) {
        this.gifal8 = gifal8;
    }
    public String getGivusr() {
        return this.givusr;
    }
    
    public void setGivusr(String givusr) {
        this.givusr = givusr;
    }
    public String getGistnm() {
        return this.gistnm;
    }
    
    public void setGistnm(String gistnm) {
        this.gistnm = gistnm;
    }
    public Integer getGistrn() {
        return this.gistrn;
    }
    
    public void setGistrn(Integer gistrn) {
        this.gistrn = gistrn;
    }
    public String getGistyn() {
        return this.gistyn;
    }
    
    public void setGistyn(String gistyn) {
        this.gistyn = gistyn;
    }
    public String getGiadcm() {
        return this.giadcm;
    }
    
    public void setGiadcm(String giadcm) {
        this.giadcm = giadcm;
    }
    public String getGicity() {
        return this.gicity;
    }
    
    public void setGicity(String gicity) {
        this.gicity = gicity;
    }
    public String getGistan() {
        return this.gistan;
    }
    
    public void setGistan(String gistan) {
        this.gistan = gistan;
    }
    public Integer getGizpcd() {
        return this.gizpcd;
    }
    
    public void setGizpcd(Integer gizpcd) {
        this.gizpcd = gizpcd;
    }
    public Integer getGiqmbf() {
        return this.giqmbf;
    }
    
    public void setGiqmbf(Integer giqmbf) {
        this.giqmbf = giqmbf;
    }
    public Integer getGiqmbl() {
        return this.giqmbl;
    }
    
    public void setGiqmbl(Integer giqmbl) {
        this.giqmbl = giqmbl;
    }
    public Integer getGiqchd() {
        return this.giqchd;
    }
    
    public void setGiqchd(Integer giqchd) {
        this.giqchd = giqchd;
    }
    public Integer getGiqcjf() {
        return this.giqcjf;
    }
    
    public void setGiqcjf(Integer giqcjf) {
        this.giqcjf = giqcjf;
    }
    public Integer getGiqott() {
        return this.giqott;
    }
    
    public void setGiqott(Integer giqott) {
        this.giqott = giqott;
    }
    public Integer getGimdte() {
        return this.gimdte;
    }
    
    public void setGimdte(Integer gimdte) {
        this.gimdte = gimdte;
    }
    public Integer getGimtme() {
        return this.gimtme;
    }
    
    public void setGimtme(Integer gimtme) {
        this.gimtme = gimtme;
    }
    public String getGimusr() {
        return this.gimusr;
    }
    
    public void setGimusr(String gimusr) {
        this.gimusr = gimusr;
    }
    public String getGimtrm() {
        return this.gimtrm;
    }
    
    public void setGimtrm(String gimtrm) {
        this.gimtrm = gimtrm;
    }
    public Integer getGiadte() {
        return this.giadte;
    }
    
    public void setGiadte(Integer giadte) {
        this.giadte = giadte;
    }
    public Integer getGiatme() {
        return this.giatme;
    }
    
    public void setGiatme(Integer giatme) {
        this.giatme = giatme;
    }
    public String getGiausr() {
        return this.giausr;
    }
    
    public void setGiausr(String giausr) {
        this.giausr = giausr;
    }
    public String getGiatrm() {
        return this.giatrm;
    }
    
    public void setGiatrm(String giatrm) {
        this.giatrm = giatrm;
    }
    public Long getGirmcn() {
        return this.girmcn;
    }
    
    public void setGirmcn(Long girmcn) {
        this.girmcn = girmcn;
    }
    public String getGiciin() {
        return this.giciin;
    }
    
    public void setGiciin(String giciin) {
        this.giciin = giciin;
    }
    public String getGibtrf() {
        return this.gibtrf;
    }
    
    public void setGibtrf(String gibtrf) {
        this.gibtrf = gibtrf;
    }
    public String getGibocp() {
        return this.gibocp;
    }
    
    public void setGibocp(String gibocp) {
        this.gibocp = gibocp;
    }
    public String getGicone() {
        return this.gicone;
    }
    
    public void setGicone(String gicone) {
        this.gicone = gicone;
    }
    public String getGiccoe() {
        return this.giccoe;
    }
    
    public void setGiccoe(String giccoe) {
        this.giccoe = giccoe;
    }
    public Long getGip1pn() {
        return this.gip1pn;
    }
    
    public void setGip1pn(Long gip1pn) {
        this.gip1pn = gip1pn;
    }
    public String getGiadic() {
        return this.giadic;
    }
    
    public void setGiadic(String giadic) {
        this.giadic = giadic;
    }
    public String getGiembo() {
        return this.giembo;
    }
    
    public void setGiembo(String giembo) {
        this.giembo = giembo;
    }




}


