package com.ciessa.museum.model.legacy;
// Generated Jun 27, 2018 10:26:04 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Cfp001210 generated by hbm2java
 */
public class Cfp001210  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String cfbk;
     private String cfrec;
     private String cfadsg;
     private String cftnbr;
     private String cffil8;
     private String cfindr;
     private String cfstat;
     private String cftnme;
     private String cftlin;
     private String cfads2;
     private String cfpers;
     private String cftafg;
     private String cflp;
     private String cfmail;
     private String cfclov;
     private String cfsig;
     private String cfsiga;
     private String cfspin;
     private String cfodl;
     private String cfdorf;
     private Integer cfdord;
     private Integer cfbdmo;
     private Integer cfnrwd;
     private String cfstct;
     private String cfstcd;
     private Integer cfstcy;
     private String cfrege;
     private String cfclst;
     private String cfnoac;
     private String cfscty;
     private Integer cfsccd;
     private String cfsc;
     private String cfscpr;
     private Integer cfscfr;
     private Integer cfdint;
     private String cfin;
     private String cfinpr;
     private Integer cfinfr;
     private String cfidsp;
     private String cfthst;
     private String cfencc;
     private String cfencd;
     private String cfpbfg;
     private String citodc;
     private Integer cicurc;
     private String cicapc;
     private Integer ciacap;
     private BigDecimal ciacsp;
     private Integer citodp;
     private BigDecimal citosp;
     private BigDecimal cimodr;
     private Integer cicpol;
     private BigDecimal ciwhpc;
     private String cimffi;
     private Integer cidcpn;
     private String citoab;
     private String citoyr;
     private String ciacab;
     private String ciacyr;
     private BigDecimal cfnsfr;
     private BigDecimal cfnsfp;
     private BigDecimal cfretc;
     private BigDecimal cicpvr;
     private BigDecimal cidcpv;

    public Cfp001210() {
    }

	
    public Cfp001210(String pkid) {
        this.pkid = pkid;
    }
    public Cfp001210(String pkid, String member, String cfbk, String cfrec, String cfadsg, String cftnbr, String cffil8, String cfindr, String cfstat, String cftnme, String cftlin, String cfads2, String cfpers, String cftafg, String cflp, String cfmail, String cfclov, String cfsig, String cfsiga, String cfspin, String cfodl, String cfdorf, Integer cfdord, Integer cfbdmo, Integer cfnrwd, String cfstct, String cfstcd, Integer cfstcy, String cfrege, String cfclst, String cfnoac, String cfscty, Integer cfsccd, String cfsc, String cfscpr, Integer cfscfr, Integer cfdint, String cfin, String cfinpr, Integer cfinfr, String cfidsp, String cfthst, String cfencc, String cfencd, String cfpbfg, String citodc, Integer cicurc, String cicapc, Integer ciacap, BigDecimal ciacsp, Integer citodp, BigDecimal citosp, BigDecimal cimodr, Integer cicpol, BigDecimal ciwhpc, String cimffi, Integer cidcpn, String citoab, String citoyr, String ciacab, String ciacyr, BigDecimal cfnsfr, BigDecimal cfnsfp, BigDecimal cfretc, BigDecimal cicpvr, BigDecimal cidcpv) {
       this.pkid = pkid;
       this.member = member;
       this.cfbk = cfbk;
       this.cfrec = cfrec;
       this.cfadsg = cfadsg;
       this.cftnbr = cftnbr;
       this.cffil8 = cffil8;
       this.cfindr = cfindr;
       this.cfstat = cfstat;
       this.cftnme = cftnme;
       this.cftlin = cftlin;
       this.cfads2 = cfads2;
       this.cfpers = cfpers;
       this.cftafg = cftafg;
       this.cflp = cflp;
       this.cfmail = cfmail;
       this.cfclov = cfclov;
       this.cfsig = cfsig;
       this.cfsiga = cfsiga;
       this.cfspin = cfspin;
       this.cfodl = cfodl;
       this.cfdorf = cfdorf;
       this.cfdord = cfdord;
       this.cfbdmo = cfbdmo;
       this.cfnrwd = cfnrwd;
       this.cfstct = cfstct;
       this.cfstcd = cfstcd;
       this.cfstcy = cfstcy;
       this.cfrege = cfrege;
       this.cfclst = cfclst;
       this.cfnoac = cfnoac;
       this.cfscty = cfscty;
       this.cfsccd = cfsccd;
       this.cfsc = cfsc;
       this.cfscpr = cfscpr;
       this.cfscfr = cfscfr;
       this.cfdint = cfdint;
       this.cfin = cfin;
       this.cfinpr = cfinpr;
       this.cfinfr = cfinfr;
       this.cfidsp = cfidsp;
       this.cfthst = cfthst;
       this.cfencc = cfencc;
       this.cfencd = cfencd;
       this.cfpbfg = cfpbfg;
       this.citodc = citodc;
       this.cicurc = cicurc;
       this.cicapc = cicapc;
       this.ciacap = ciacap;
       this.ciacsp = ciacsp;
       this.citodp = citodp;
       this.citosp = citosp;
       this.cimodr = cimodr;
       this.cicpol = cicpol;
       this.ciwhpc = ciwhpc;
       this.cimffi = cimffi;
       this.cidcpn = cidcpn;
       this.citoab = citoab;
       this.citoyr = citoyr;
       this.ciacab = ciacab;
       this.ciacyr = ciacyr;
       this.cfnsfr = cfnsfr;
       this.cfnsfp = cfnsfp;
       this.cfretc = cfretc;
       this.cicpvr = cicpvr;
       this.cidcpv = cidcpv;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getCfbk() {
        return this.cfbk;
    }
    
    public void setCfbk(String cfbk) {
        this.cfbk = cfbk;
    }
    public String getCfrec() {
        return this.cfrec;
    }
    
    public void setCfrec(String cfrec) {
        this.cfrec = cfrec;
    }
    public String getCfadsg() {
        return this.cfadsg;
    }
    
    public void setCfadsg(String cfadsg) {
        this.cfadsg = cfadsg;
    }
    public String getCftnbr() {
        return this.cftnbr;
    }
    
    public void setCftnbr(String cftnbr) {
        this.cftnbr = cftnbr;
    }
    public String getCffil8() {
        return this.cffil8;
    }
    
    public void setCffil8(String cffil8) {
        this.cffil8 = cffil8;
    }
    public String getCfindr() {
        return this.cfindr;
    }
    
    public void setCfindr(String cfindr) {
        this.cfindr = cfindr;
    }
    public String getCfstat() {
        return this.cfstat;
    }
    
    public void setCfstat(String cfstat) {
        this.cfstat = cfstat;
    }
    public String getCftnme() {
        return this.cftnme;
    }
    
    public void setCftnme(String cftnme) {
        this.cftnme = cftnme;
    }
    public String getCftlin() {
        return this.cftlin;
    }
    
    public void setCftlin(String cftlin) {
        this.cftlin = cftlin;
    }
    public String getCfads2() {
        return this.cfads2;
    }
    
    public void setCfads2(String cfads2) {
        this.cfads2 = cfads2;
    }
    public String getCfpers() {
        return this.cfpers;
    }
    
    public void setCfpers(String cfpers) {
        this.cfpers = cfpers;
    }
    public String getCftafg() {
        return this.cftafg;
    }
    
    public void setCftafg(String cftafg) {
        this.cftafg = cftafg;
    }
    public String getCflp() {
        return this.cflp;
    }
    
    public void setCflp(String cflp) {
        this.cflp = cflp;
    }
    public String getCfmail() {
        return this.cfmail;
    }
    
    public void setCfmail(String cfmail) {
        this.cfmail = cfmail;
    }
    public String getCfclov() {
        return this.cfclov;
    }
    
    public void setCfclov(String cfclov) {
        this.cfclov = cfclov;
    }
    public String getCfsig() {
        return this.cfsig;
    }
    
    public void setCfsig(String cfsig) {
        this.cfsig = cfsig;
    }
    public String getCfsiga() {
        return this.cfsiga;
    }
    
    public void setCfsiga(String cfsiga) {
        this.cfsiga = cfsiga;
    }
    public String getCfspin() {
        return this.cfspin;
    }
    
    public void setCfspin(String cfspin) {
        this.cfspin = cfspin;
    }
    public String getCfodl() {
        return this.cfodl;
    }
    
    public void setCfodl(String cfodl) {
        this.cfodl = cfodl;
    }
    public String getCfdorf() {
        return this.cfdorf;
    }
    
    public void setCfdorf(String cfdorf) {
        this.cfdorf = cfdorf;
    }
    public Integer getCfdord() {
        return this.cfdord;
    }
    
    public void setCfdord(Integer cfdord) {
        this.cfdord = cfdord;
    }
    public Integer getCfbdmo() {
        return this.cfbdmo;
    }
    
    public void setCfbdmo(Integer cfbdmo) {
        this.cfbdmo = cfbdmo;
    }
    public Integer getCfnrwd() {
        return this.cfnrwd;
    }
    
    public void setCfnrwd(Integer cfnrwd) {
        this.cfnrwd = cfnrwd;
    }
    public String getCfstct() {
        return this.cfstct;
    }
    
    public void setCfstct(String cfstct) {
        this.cfstct = cfstct;
    }
    public String getCfstcd() {
        return this.cfstcd;
    }
    
    public void setCfstcd(String cfstcd) {
        this.cfstcd = cfstcd;
    }
    public Integer getCfstcy() {
        return this.cfstcy;
    }
    
    public void setCfstcy(Integer cfstcy) {
        this.cfstcy = cfstcy;
    }
    public String getCfrege() {
        return this.cfrege;
    }
    
    public void setCfrege(String cfrege) {
        this.cfrege = cfrege;
    }
    public String getCfclst() {
        return this.cfclst;
    }
    
    public void setCfclst(String cfclst) {
        this.cfclst = cfclst;
    }
    public String getCfnoac() {
        return this.cfnoac;
    }
    
    public void setCfnoac(String cfnoac) {
        this.cfnoac = cfnoac;
    }
    public String getCfscty() {
        return this.cfscty;
    }
    
    public void setCfscty(String cfscty) {
        this.cfscty = cfscty;
    }
    public Integer getCfsccd() {
        return this.cfsccd;
    }
    
    public void setCfsccd(Integer cfsccd) {
        this.cfsccd = cfsccd;
    }
    public String getCfsc() {
        return this.cfsc;
    }
    
    public void setCfsc(String cfsc) {
        this.cfsc = cfsc;
    }
    public String getCfscpr() {
        return this.cfscpr;
    }
    
    public void setCfscpr(String cfscpr) {
        this.cfscpr = cfscpr;
    }
    public Integer getCfscfr() {
        return this.cfscfr;
    }
    
    public void setCfscfr(Integer cfscfr) {
        this.cfscfr = cfscfr;
    }
    public Integer getCfdint() {
        return this.cfdint;
    }
    
    public void setCfdint(Integer cfdint) {
        this.cfdint = cfdint;
    }
    public String getCfin() {
        return this.cfin;
    }
    
    public void setCfin(String cfin) {
        this.cfin = cfin;
    }
    public String getCfinpr() {
        return this.cfinpr;
    }
    
    public void setCfinpr(String cfinpr) {
        this.cfinpr = cfinpr;
    }
    public Integer getCfinfr() {
        return this.cfinfr;
    }
    
    public void setCfinfr(Integer cfinfr) {
        this.cfinfr = cfinfr;
    }
    public String getCfidsp() {
        return this.cfidsp;
    }
    
    public void setCfidsp(String cfidsp) {
        this.cfidsp = cfidsp;
    }
    public String getCfthst() {
        return this.cfthst;
    }
    
    public void setCfthst(String cfthst) {
        this.cfthst = cfthst;
    }
    public String getCfencc() {
        return this.cfencc;
    }
    
    public void setCfencc(String cfencc) {
        this.cfencc = cfencc;
    }
    public String getCfencd() {
        return this.cfencd;
    }
    
    public void setCfencd(String cfencd) {
        this.cfencd = cfencd;
    }
    public String getCfpbfg() {
        return this.cfpbfg;
    }
    
    public void setCfpbfg(String cfpbfg) {
        this.cfpbfg = cfpbfg;
    }
    public String getCitodc() {
        return this.citodc;
    }
    
    public void setCitodc(String citodc) {
        this.citodc = citodc;
    }
    public Integer getCicurc() {
        return this.cicurc;
    }
    
    public void setCicurc(Integer cicurc) {
        this.cicurc = cicurc;
    }
    public String getCicapc() {
        return this.cicapc;
    }
    
    public void setCicapc(String cicapc) {
        this.cicapc = cicapc;
    }
    public Integer getCiacap() {
        return this.ciacap;
    }
    
    public void setCiacap(Integer ciacap) {
        this.ciacap = ciacap;
    }
    public BigDecimal getCiacsp() {
        return this.ciacsp;
    }
    
    public void setCiacsp(BigDecimal ciacsp) {
        this.ciacsp = ciacsp;
    }
    public Integer getCitodp() {
        return this.citodp;
    }
    
    public void setCitodp(Integer citodp) {
        this.citodp = citodp;
    }
    public BigDecimal getCitosp() {
        return this.citosp;
    }
    
    public void setCitosp(BigDecimal citosp) {
        this.citosp = citosp;
    }
    public BigDecimal getCimodr() {
        return this.cimodr;
    }
    
    public void setCimodr(BigDecimal cimodr) {
        this.cimodr = cimodr;
    }
    public Integer getCicpol() {
        return this.cicpol;
    }
    
    public void setCicpol(Integer cicpol) {
        this.cicpol = cicpol;
    }
    public BigDecimal getCiwhpc() {
        return this.ciwhpc;
    }
    
    public void setCiwhpc(BigDecimal ciwhpc) {
        this.ciwhpc = ciwhpc;
    }
    public String getCimffi() {
        return this.cimffi;
    }
    
    public void setCimffi(String cimffi) {
        this.cimffi = cimffi;
    }
    public Integer getCidcpn() {
        return this.cidcpn;
    }
    
    public void setCidcpn(Integer cidcpn) {
        this.cidcpn = cidcpn;
    }
    public String getCitoab() {
        return this.citoab;
    }
    
    public void setCitoab(String citoab) {
        this.citoab = citoab;
    }
    public String getCitoyr() {
        return this.citoyr;
    }
    
    public void setCitoyr(String citoyr) {
        this.citoyr = citoyr;
    }
    public String getCiacab() {
        return this.ciacab;
    }
    
    public void setCiacab(String ciacab) {
        this.ciacab = ciacab;
    }
    public String getCiacyr() {
        return this.ciacyr;
    }
    
    public void setCiacyr(String ciacyr) {
        this.ciacyr = ciacyr;
    }
    public BigDecimal getCfnsfr() {
        return this.cfnsfr;
    }
    
    public void setCfnsfr(BigDecimal cfnsfr) {
        this.cfnsfr = cfnsfr;
    }
    public BigDecimal getCfnsfp() {
        return this.cfnsfp;
    }
    
    public void setCfnsfp(BigDecimal cfnsfp) {
        this.cfnsfp = cfnsfp;
    }
    public BigDecimal getCfretc() {
        return this.cfretc;
    }
    
    public void setCfretc(BigDecimal cfretc) {
        this.cfretc = cfretc;
    }
    public BigDecimal getCicpvr() {
        return this.cicpvr;
    }
    
    public void setCicpvr(BigDecimal cicpvr) {
        this.cicpvr = cicpvr;
    }
    public BigDecimal getCidcpv() {
        return this.cidcpv;
    }
    
    public void setCidcpv(BigDecimal cidcpv) {
        this.cidcpv = cidcpv;
    }




}


