package com.ciessa.museum.model.legacy;
// Generated Dec 11, 2018 7:50:29 PM by Hibernate Tools 3.2.2.GA



/**
 * Cfp001207 generated by hbm2java
 */
public class Cfp001207  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String cfbco;
     private String cfreg;
     private Long cflim1;
     private Long cflim2;
     private Long cflim3;
     private Long cflim4;
     private Long cflim5;
     private Long cflim6;
     private Long cflim7;
     private Long cflim8;
     private Long cflim9;
     private String cfiva1;
     private String cfiva2;
     private String cfiva3;
     private String cfiva4;
     private String cfiva5;
     private String cfiva6;

    public Cfp001207() {
    }

	
    public Cfp001207(String pkid) {
        this.pkid = pkid;
    }
    public Cfp001207(String pkid, String member, String cfbco, String cfreg, Long cflim1, Long cflim2, Long cflim3, Long cflim4, Long cflim5, Long cflim6, Long cflim7, Long cflim8, Long cflim9, String cfiva1, String cfiva2, String cfiva3, String cfiva4, String cfiva5, String cfiva6) {
       this.pkid = pkid;
       this.member = member;
       this.cfbco = cfbco;
       this.cfreg = cfreg;
       this.cflim1 = cflim1;
       this.cflim2 = cflim2;
       this.cflim3 = cflim3;
       this.cflim4 = cflim4;
       this.cflim5 = cflim5;
       this.cflim6 = cflim6;
       this.cflim7 = cflim7;
       this.cflim8 = cflim8;
       this.cflim9 = cflim9;
       this.cfiva1 = cfiva1;
       this.cfiva2 = cfiva2;
       this.cfiva3 = cfiva3;
       this.cfiva4 = cfiva4;
       this.cfiva5 = cfiva5;
       this.cfiva6 = cfiva6;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getCfbco() {
        return this.cfbco;
    }
    
    public void setCfbco(String cfbco) {
        this.cfbco = cfbco;
    }
    public String getCfreg() {
        return this.cfreg;
    }
    
    public void setCfreg(String cfreg) {
        this.cfreg = cfreg;
    }
    public Long getCflim1() {
        return this.cflim1;
    }
    
    public void setCflim1(Long cflim1) {
        this.cflim1 = cflim1;
    }
    public Long getCflim2() {
        return this.cflim2;
    }
    
    public void setCflim2(Long cflim2) {
        this.cflim2 = cflim2;
    }
    public Long getCflim3() {
        return this.cflim3;
    }
    
    public void setCflim3(Long cflim3) {
        this.cflim3 = cflim3;
    }
    public Long getCflim4() {
        return this.cflim4;
    }
    
    public void setCflim4(Long cflim4) {
        this.cflim4 = cflim4;
    }
    public Long getCflim5() {
        return this.cflim5;
    }
    
    public void setCflim5(Long cflim5) {
        this.cflim5 = cflim5;
    }
    public Long getCflim6() {
        return this.cflim6;
    }
    
    public void setCflim6(Long cflim6) {
        this.cflim6 = cflim6;
    }
    public Long getCflim7() {
        return this.cflim7;
    }
    
    public void setCflim7(Long cflim7) {
        this.cflim7 = cflim7;
    }
    public Long getCflim8() {
        return this.cflim8;
    }
    
    public void setCflim8(Long cflim8) {
        this.cflim8 = cflim8;
    }
    public Long getCflim9() {
        return this.cflim9;
    }
    
    public void setCflim9(Long cflim9) {
        this.cflim9 = cflim9;
    }
    public String getCfiva1() {
        return this.cfiva1;
    }
    
    public void setCfiva1(String cfiva1) {
        this.cfiva1 = cfiva1;
    }
    public String getCfiva2() {
        return this.cfiva2;
    }
    
    public void setCfiva2(String cfiva2) {
        this.cfiva2 = cfiva2;
    }
    public String getCfiva3() {
        return this.cfiva3;
    }
    
    public void setCfiva3(String cfiva3) {
        this.cfiva3 = cfiva3;
    }
    public String getCfiva4() {
        return this.cfiva4;
    }
    
    public void setCfiva4(String cfiva4) {
        this.cfiva4 = cfiva4;
    }
    public String getCfiva5() {
        return this.cfiva5;
    }
    
    public void setCfiva5(String cfiva5) {
        this.cfiva5 = cfiva5;
    }
    public String getCfiva6() {
        return this.cfiva6;
    }
    
    public void setCfiva6(String cfiva6) {
        this.cfiva6 = cfiva6;
    }




}


