package com.ciessa.museum.model.legacy;
// Generated Jan 28, 2019 1:33:59 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Cfp001205 generated by hbm2java
 */
public class Cfp001205  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String cfbco;
     private String cfreg;
     private String cfinnr;
     private String cffil3;
     private String cfindr;
     private String cfstat;
     private String cfinds;
     private String cfpinc;
     private String cfpnty;
     private String cfpacb;
     private String cfpyrb;
     private String cfpten;
     private BigDecimal cfprsv;
     private Integer cfpmba;
     private String cfpmbf;
     private BigDecimal cfpmap;
     private BigDecimal cfpmbp;
     private BigDecimal cfpmnr;
     private Long cfpmnb;
     private Long cfpmna;
     private Long cfpb1;
     private Long cfpb2;
     private Long cfpb3;
     private Long cfpb4;
     private String cfpi;
     private String cftrfg;

    public Cfp001205() {
    }

	
    public Cfp001205(String pkid) {
        this.pkid = pkid;
    }
    public Cfp001205(String pkid, String member, String cfbco, String cfreg, String cfinnr, String cffil3, String cfindr, String cfstat, String cfinds, String cfpinc, String cfpnty, String cfpacb, String cfpyrb, String cfpten, BigDecimal cfprsv, Integer cfpmba, String cfpmbf, BigDecimal cfpmap, BigDecimal cfpmbp, BigDecimal cfpmnr, Long cfpmnb, Long cfpmna, Long cfpb1, Long cfpb2, Long cfpb3, Long cfpb4, String cfpi, String cftrfg) {
       this.pkid = pkid;
       this.member = member;
       this.cfbco = cfbco;
       this.cfreg = cfreg;
       this.cfinnr = cfinnr;
       this.cffil3 = cffil3;
       this.cfindr = cfindr;
       this.cfstat = cfstat;
       this.cfinds = cfinds;
       this.cfpinc = cfpinc;
       this.cfpnty = cfpnty;
       this.cfpacb = cfpacb;
       this.cfpyrb = cfpyrb;
       this.cfpten = cfpten;
       this.cfprsv = cfprsv;
       this.cfpmba = cfpmba;
       this.cfpmbf = cfpmbf;
       this.cfpmap = cfpmap;
       this.cfpmbp = cfpmbp;
       this.cfpmnr = cfpmnr;
       this.cfpmnb = cfpmnb;
       this.cfpmna = cfpmna;
       this.cfpb1 = cfpb1;
       this.cfpb2 = cfpb2;
       this.cfpb3 = cfpb3;
       this.cfpb4 = cfpb4;
       this.cfpi = cfpi;
       this.cftrfg = cftrfg;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getCfbco() {
        return this.cfbco;
    }
    
    public void setCfbco(String cfbco) {
        this.cfbco = cfbco;
    }
    public String getCfreg() {
        return this.cfreg;
    }
    
    public void setCfreg(String cfreg) {
        this.cfreg = cfreg;
    }
    public String getCfinnr() {
        return this.cfinnr;
    }
    
    public void setCfinnr(String cfinnr) {
        this.cfinnr = cfinnr;
    }
    public String getCffil3() {
        return this.cffil3;
    }
    
    public void setCffil3(String cffil3) {
        this.cffil3 = cffil3;
    }
    public String getCfindr() {
        return this.cfindr;
    }
    
    public void setCfindr(String cfindr) {
        this.cfindr = cfindr;
    }
    public String getCfstat() {
        return this.cfstat;
    }
    
    public void setCfstat(String cfstat) {
        this.cfstat = cfstat;
    }
    public String getCfinds() {
        return this.cfinds;
    }
    
    public void setCfinds(String cfinds) {
        this.cfinds = cfinds;
    }
    public String getCfpinc() {
        return this.cfpinc;
    }
    
    public void setCfpinc(String cfpinc) {
        this.cfpinc = cfpinc;
    }
    public String getCfpnty() {
        return this.cfpnty;
    }
    
    public void setCfpnty(String cfpnty) {
        this.cfpnty = cfpnty;
    }
    public String getCfpacb() {
        return this.cfpacb;
    }
    
    public void setCfpacb(String cfpacb) {
        this.cfpacb = cfpacb;
    }
    public String getCfpyrb() {
        return this.cfpyrb;
    }
    
    public void setCfpyrb(String cfpyrb) {
        this.cfpyrb = cfpyrb;
    }
    public String getCfpten() {
        return this.cfpten;
    }
    
    public void setCfpten(String cfpten) {
        this.cfpten = cfpten;
    }
    public BigDecimal getCfprsv() {
        return this.cfprsv;
    }
    
    public void setCfprsv(BigDecimal cfprsv) {
        this.cfprsv = cfprsv;
    }
    public Integer getCfpmba() {
        return this.cfpmba;
    }
    
    public void setCfpmba(Integer cfpmba) {
        this.cfpmba = cfpmba;
    }
    public String getCfpmbf() {
        return this.cfpmbf;
    }
    
    public void setCfpmbf(String cfpmbf) {
        this.cfpmbf = cfpmbf;
    }
    public BigDecimal getCfpmap() {
        return this.cfpmap;
    }
    
    public void setCfpmap(BigDecimal cfpmap) {
        this.cfpmap = cfpmap;
    }
    public BigDecimal getCfpmbp() {
        return this.cfpmbp;
    }
    
    public void setCfpmbp(BigDecimal cfpmbp) {
        this.cfpmbp = cfpmbp;
    }
    public BigDecimal getCfpmnr() {
        return this.cfpmnr;
    }
    
    public void setCfpmnr(BigDecimal cfpmnr) {
        this.cfpmnr = cfpmnr;
    }
    public Long getCfpmnb() {
        return this.cfpmnb;
    }
    
    public void setCfpmnb(Long cfpmnb) {
        this.cfpmnb = cfpmnb;
    }
    public Long getCfpmna() {
        return this.cfpmna;
    }
    
    public void setCfpmna(Long cfpmna) {
        this.cfpmna = cfpmna;
    }
    public Long getCfpb1() {
        return this.cfpb1;
    }
    
    public void setCfpb1(Long cfpb1) {
        this.cfpb1 = cfpb1;
    }
    public Long getCfpb2() {
        return this.cfpb2;
    }
    
    public void setCfpb2(Long cfpb2) {
        this.cfpb2 = cfpb2;
    }
    public Long getCfpb3() {
        return this.cfpb3;
    }
    
    public void setCfpb3(Long cfpb3) {
        this.cfpb3 = cfpb3;
    }
    public Long getCfpb4() {
        return this.cfpb4;
    }
    
    public void setCfpb4(Long cfpb4) {
        this.cfpb4 = cfpb4;
    }
    public String getCfpi() {
        return this.cfpi;
    }
    
    public void setCfpi(String cfpi) {
        this.cfpi = cfpi;
    }
    public String getCftrfg() {
        return this.cftrfg;
    }
    
    public void setCftrfg(String cftrfg) {
        this.cftrfg = cftrfg;
    }




}


