package com.ciessa.museum.model.legacy;
// Generated Sep 10, 2018 9:32:23 PM by Hibernate Tools 3.2.2.GA



/**
 * Cfp001220 generated by hbm2java
 */
public class Cfp001220  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String cfbco;
     private String cfreg;
     private String cfctr;
     private String cfcte;
     private String cfdco;
     private String cfcmn;
     private String cfcgl;
     private String depost;
     private String withdw;
     private String cfdla;
     private String citit;
     private String nrefo;
     private String canop;

    public Cfp001220() {
    }

	
    public Cfp001220(String pkid) {
        this.pkid = pkid;
    }
    public Cfp001220(String pkid, String member, String cfbco, String cfreg, String cfctr, String cfcte, String cfdco, String cfcmn, String cfcgl, String depost, String withdw, String cfdla, String citit, String nrefo, String canop) {
       this.pkid = pkid;
       this.member = member;
       this.cfbco = cfbco;
       this.cfreg = cfreg;
       this.cfctr = cfctr;
       this.cfcte = cfcte;
       this.cfdco = cfdco;
       this.cfcmn = cfcmn;
       this.cfcgl = cfcgl;
       this.depost = depost;
       this.withdw = withdw;
       this.cfdla = cfdla;
       this.citit = citit;
       this.nrefo = nrefo;
       this.canop = canop;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getCfbco() {
        return this.cfbco;
    }
    
    public void setCfbco(String cfbco) {
        this.cfbco = cfbco;
    }
    public String getCfreg() {
        return this.cfreg;
    }
    
    public void setCfreg(String cfreg) {
        this.cfreg = cfreg;
    }
    public String getCfctr() {
        return this.cfctr;
    }
    
    public void setCfctr(String cfctr) {
        this.cfctr = cfctr;
    }
    public String getCfcte() {
        return this.cfcte;
    }
    
    public void setCfcte(String cfcte) {
        this.cfcte = cfcte;
    }
    public String getCfdco() {
        return this.cfdco;
    }
    
    public void setCfdco(String cfdco) {
        this.cfdco = cfdco;
    }
    public String getCfcmn() {
        return this.cfcmn;
    }
    
    public void setCfcmn(String cfcmn) {
        this.cfcmn = cfcmn;
    }
    public String getCfcgl() {
        return this.cfcgl;
    }
    
    public void setCfcgl(String cfcgl) {
        this.cfcgl = cfcgl;
    }
    public String getDepost() {
        return this.depost;
    }
    
    public void setDepost(String depost) {
        this.depost = depost;
    }
    public String getWithdw() {
        return this.withdw;
    }
    
    public void setWithdw(String withdw) {
        this.withdw = withdw;
    }
    public String getCfdla() {
        return this.cfdla;
    }
    
    public void setCfdla(String cfdla) {
        this.cfdla = cfdla;
    }
    public String getCitit() {
        return this.citit;
    }
    
    public void setCitit(String citit) {
        this.citit = citit;
    }
    public String getNrefo() {
        return this.nrefo;
    }
    
    public void setNrefo(String nrefo) {
        this.nrefo = nrefo;
    }
    public String getCanop() {
        return this.canop;
    }
    
    public void setCanop(String canop) {
        this.canop = canop;
    }




}


