package com.ciessa.museum.model.legacy;
// Generated Oct 22, 2018 9:28:33 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Compcmo generated by hbm2java
 */
public class Compcmo  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Long huacct;
     private Integer huampr;
     private String hugrpp;
     private String hustat;
     private Integer huanmc;
     private Integer hubrch;
     private Integer hudivi;
     private Integer hucode;
     private BigDecimal husafm;
     private BigDecimal husprm;
     private BigDecimal huupra;
     private Integer humdbt;
     private Integer humcrt;
     private Integer hudexe;
     private BigDecimal husdbt;
     private BigDecimal huscrd;
     private Integer hucace;
     private BigDecimal husace;
     private Integer hucacs;
     private BigDecimal husacs;
     private BigDecimal huugac;
     private String hudpri;
     private Integer huprov;
     private Integer husmes;
     private String huarea;

    public Compcmo() {
    }

	
    public Compcmo(String pkid) {
        this.pkid = pkid;
    }
    public Compcmo(String pkid, String member, Long huacct, Integer huampr, String hugrpp, String hustat, Integer huanmc, Integer hubrch, Integer hudivi, Integer hucode, BigDecimal husafm, BigDecimal husprm, BigDecimal huupra, Integer humdbt, Integer humcrt, Integer hudexe, BigDecimal husdbt, BigDecimal huscrd, Integer hucace, BigDecimal husace, Integer hucacs, BigDecimal husacs, BigDecimal huugac, String hudpri, Integer huprov, Integer husmes, String huarea) {
       this.pkid = pkid;
       this.member = member;
       this.huacct = huacct;
       this.huampr = huampr;
       this.hugrpp = hugrpp;
       this.hustat = hustat;
       this.huanmc = huanmc;
       this.hubrch = hubrch;
       this.hudivi = hudivi;
       this.hucode = hucode;
       this.husafm = husafm;
       this.husprm = husprm;
       this.huupra = huupra;
       this.humdbt = humdbt;
       this.humcrt = humcrt;
       this.hudexe = hudexe;
       this.husdbt = husdbt;
       this.huscrd = huscrd;
       this.hucace = hucace;
       this.husace = husace;
       this.hucacs = hucacs;
       this.husacs = husacs;
       this.huugac = huugac;
       this.hudpri = hudpri;
       this.huprov = huprov;
       this.husmes = husmes;
       this.huarea = huarea;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Long getHuacct() {
        return this.huacct;
    }
    
    public void setHuacct(Long huacct) {
        this.huacct = huacct;
    }
    public Integer getHuampr() {
        return this.huampr;
    }
    
    public void setHuampr(Integer huampr) {
        this.huampr = huampr;
    }
    public String getHugrpp() {
        return this.hugrpp;
    }
    
    public void setHugrpp(String hugrpp) {
        this.hugrpp = hugrpp;
    }
    public String getHustat() {
        return this.hustat;
    }
    
    public void setHustat(String hustat) {
        this.hustat = hustat;
    }
    public Integer getHuanmc() {
        return this.huanmc;
    }
    
    public void setHuanmc(Integer huanmc) {
        this.huanmc = huanmc;
    }
    public Integer getHubrch() {
        return this.hubrch;
    }
    
    public void setHubrch(Integer hubrch) {
        this.hubrch = hubrch;
    }
    public Integer getHudivi() {
        return this.hudivi;
    }
    
    public void setHudivi(Integer hudivi) {
        this.hudivi = hudivi;
    }
    public Integer getHucode() {
        return this.hucode;
    }
    
    public void setHucode(Integer hucode) {
        this.hucode = hucode;
    }
    public BigDecimal getHusafm() {
        return this.husafm;
    }
    
    public void setHusafm(BigDecimal husafm) {
        this.husafm = husafm;
    }
    public BigDecimal getHusprm() {
        return this.husprm;
    }
    
    public void setHusprm(BigDecimal husprm) {
        this.husprm = husprm;
    }
    public BigDecimal getHuupra() {
        return this.huupra;
    }
    
    public void setHuupra(BigDecimal huupra) {
        this.huupra = huupra;
    }
    public Integer getHumdbt() {
        return this.humdbt;
    }
    
    public void setHumdbt(Integer humdbt) {
        this.humdbt = humdbt;
    }
    public Integer getHumcrt() {
        return this.humcrt;
    }
    
    public void setHumcrt(Integer humcrt) {
        this.humcrt = humcrt;
    }
    public Integer getHudexe() {
        return this.hudexe;
    }
    
    public void setHudexe(Integer hudexe) {
        this.hudexe = hudexe;
    }
    public BigDecimal getHusdbt() {
        return this.husdbt;
    }
    
    public void setHusdbt(BigDecimal husdbt) {
        this.husdbt = husdbt;
    }
    public BigDecimal getHuscrd() {
        return this.huscrd;
    }
    
    public void setHuscrd(BigDecimal huscrd) {
        this.huscrd = huscrd;
    }
    public Integer getHucace() {
        return this.hucace;
    }
    
    public void setHucace(Integer hucace) {
        this.hucace = hucace;
    }
    public BigDecimal getHusace() {
        return this.husace;
    }
    
    public void setHusace(BigDecimal husace) {
        this.husace = husace;
    }
    public Integer getHucacs() {
        return this.hucacs;
    }
    
    public void setHucacs(Integer hucacs) {
        this.hucacs = hucacs;
    }
    public BigDecimal getHusacs() {
        return this.husacs;
    }
    
    public void setHusacs(BigDecimal husacs) {
        this.husacs = husacs;
    }
    public BigDecimal getHuugac() {
        return this.huugac;
    }
    
    public void setHuugac(BigDecimal huugac) {
        this.huugac = huugac;
    }
    public String getHudpri() {
        return this.hudpri;
    }
    
    public void setHudpri(String hudpri) {
        this.hudpri = hudpri;
    }
    public Integer getHuprov() {
        return this.huprov;
    }
    
    public void setHuprov(Integer huprov) {
        this.huprov = huprov;
    }
    public Integer getHusmes() {
        return this.husmes;
    }
    
    public void setHusmes(Integer husmes) {
        this.husmes = husmes;
    }
    public String getHuarea() {
        return this.huarea;
    }
    
    public void setHuarea(String huarea) {
        this.huarea = huarea;
    }




}


