package com.ciessa.museum.model.legacy;
// Generated Jul 30, 2018 8:24:30 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Cumast generated by hbm2java
 */
public class Cumast  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer cubk;
     private String cunbr;
     private String custat;
     private String cuna1;
     private String cuna2;
     private String cuna3;
     private String cuna4;
     private String cuna5;
     private String cuna6;
     private Integer cuzip;
     private Integer cuzip2;
     private String cushrt;
     private Long cussnr;
     private String cussty;
     private Long cuhmph;
     private Long cubuph;
     private String cupoff;
     private String cusoff;
     private Integer cuopdt;
     private String cutype;
     private Integer cusic;
     private String cusex;
     private String curace;
     private String cuown;
     private Integer cuyrem;
     private Integer cuinc;
     private String cusrin;
     private Integer cubdte;
     private Integer cudep;
     private String cuctc;
     private String cuctct;
     private String cucira;
     private Integer cumnbr;
     private String cuntid;
     private String cuusr1;
     private String cuclnk;
     private String cuusr3;
     private String cucdch;
     private String cucdcn;
     private Integer cucdcd;
     private String cucmch;
     private String cucmnr;
     private Integer cucmcd;
     private String cucvsh;
     private String cucvcn;
     private Integer cucvcd;
     private String cucath;
     private String cucatn;
     private Integer cucatd;
     private String cuclng;
     private Integer cucccd;
     private Integer culglr;
     private BigDecimal cucwhp;
     private String cucpsp;
     private String cuctxn;
     private Integer cucprf;
     private String cushky;
     private Integer cuitld;
     private String cupstl;
     private String blk26;

    public Cumast() {
    }

	
    public Cumast(String pkid) {
        this.pkid = pkid;
    }
    public Cumast(String pkid, String member, Integer cubk, String cunbr, String custat, String cuna1, String cuna2, String cuna3, String cuna4, String cuna5, String cuna6, Integer cuzip, Integer cuzip2, String cushrt, Long cussnr, String cussty, Long cuhmph, Long cubuph, String cupoff, String cusoff, Integer cuopdt, String cutype, Integer cusic, String cusex, String curace, String cuown, Integer cuyrem, Integer cuinc, String cusrin, Integer cubdte, Integer cudep, String cuctc, String cuctct, String cucira, Integer cumnbr, String cuntid, String cuusr1, String cuclnk, String cuusr3, String cucdch, String cucdcn, Integer cucdcd, String cucmch, String cucmnr, Integer cucmcd, String cucvsh, String cucvcn, Integer cucvcd, String cucath, String cucatn, Integer cucatd, String cuclng, Integer cucccd, Integer culglr, BigDecimal cucwhp, String cucpsp, String cuctxn, Integer cucprf, String cushky, Integer cuitld, String cupstl, String blk26) {
       this.pkid = pkid;
       this.member = member;
       this.cubk = cubk;
       this.cunbr = cunbr;
       this.custat = custat;
       this.cuna1 = cuna1;
       this.cuna2 = cuna2;
       this.cuna3 = cuna3;
       this.cuna4 = cuna4;
       this.cuna5 = cuna5;
       this.cuna6 = cuna6;
       this.cuzip = cuzip;
       this.cuzip2 = cuzip2;
       this.cushrt = cushrt;
       this.cussnr = cussnr;
       this.cussty = cussty;
       this.cuhmph = cuhmph;
       this.cubuph = cubuph;
       this.cupoff = cupoff;
       this.cusoff = cusoff;
       this.cuopdt = cuopdt;
       this.cutype = cutype;
       this.cusic = cusic;
       this.cusex = cusex;
       this.curace = curace;
       this.cuown = cuown;
       this.cuyrem = cuyrem;
       this.cuinc = cuinc;
       this.cusrin = cusrin;
       this.cubdte = cubdte;
       this.cudep = cudep;
       this.cuctc = cuctc;
       this.cuctct = cuctct;
       this.cucira = cucira;
       this.cumnbr = cumnbr;
       this.cuntid = cuntid;
       this.cuusr1 = cuusr1;
       this.cuclnk = cuclnk;
       this.cuusr3 = cuusr3;
       this.cucdch = cucdch;
       this.cucdcn = cucdcn;
       this.cucdcd = cucdcd;
       this.cucmch = cucmch;
       this.cucmnr = cucmnr;
       this.cucmcd = cucmcd;
       this.cucvsh = cucvsh;
       this.cucvcn = cucvcn;
       this.cucvcd = cucvcd;
       this.cucath = cucath;
       this.cucatn = cucatn;
       this.cucatd = cucatd;
       this.cuclng = cuclng;
       this.cucccd = cucccd;
       this.culglr = culglr;
       this.cucwhp = cucwhp;
       this.cucpsp = cucpsp;
       this.cuctxn = cuctxn;
       this.cucprf = cucprf;
       this.cushky = cushky;
       this.cuitld = cuitld;
       this.cupstl = cupstl;
       this.blk26 = blk26;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getCubk() {
        return this.cubk;
    }
    
    public void setCubk(Integer cubk) {
        this.cubk = cubk;
    }
    public String getCunbr() {
        return this.cunbr;
    }
    
    public void setCunbr(String cunbr) {
        this.cunbr = cunbr;
    }
    public String getCustat() {
        return this.custat;
    }
    
    public void setCustat(String custat) {
        this.custat = custat;
    }
    public String getCuna1() {
        return this.cuna1;
    }
    
    public void setCuna1(String cuna1) {
        this.cuna1 = cuna1;
    }
    public String getCuna2() {
        return this.cuna2;
    }
    
    public void setCuna2(String cuna2) {
        this.cuna2 = cuna2;
    }
    public String getCuna3() {
        return this.cuna3;
    }
    
    public void setCuna3(String cuna3) {
        this.cuna3 = cuna3;
    }
    public String getCuna4() {
        return this.cuna4;
    }
    
    public void setCuna4(String cuna4) {
        this.cuna4 = cuna4;
    }
    public String getCuna5() {
        return this.cuna5;
    }
    
    public void setCuna5(String cuna5) {
        this.cuna5 = cuna5;
    }
    public String getCuna6() {
        return this.cuna6;
    }
    
    public void setCuna6(String cuna6) {
        this.cuna6 = cuna6;
    }
    public Integer getCuzip() {
        return this.cuzip;
    }
    
    public void setCuzip(Integer cuzip) {
        this.cuzip = cuzip;
    }
    public Integer getCuzip2() {
        return this.cuzip2;
    }
    
    public void setCuzip2(Integer cuzip2) {
        this.cuzip2 = cuzip2;
    }
    public String getCushrt() {
        return this.cushrt;
    }
    
    public void setCushrt(String cushrt) {
        this.cushrt = cushrt;
    }
    public Long getCussnr() {
        return this.cussnr;
    }
    
    public void setCussnr(Long cussnr) {
        this.cussnr = cussnr;
    }
    public String getCussty() {
        return this.cussty;
    }
    
    public void setCussty(String cussty) {
        this.cussty = cussty;
    }
    public Long getCuhmph() {
        return this.cuhmph;
    }
    
    public void setCuhmph(Long cuhmph) {
        this.cuhmph = cuhmph;
    }
    public Long getCubuph() {
        return this.cubuph;
    }
    
    public void setCubuph(Long cubuph) {
        this.cubuph = cubuph;
    }
    public String getCupoff() {
        return this.cupoff;
    }
    
    public void setCupoff(String cupoff) {
        this.cupoff = cupoff;
    }
    public String getCusoff() {
        return this.cusoff;
    }
    
    public void setCusoff(String cusoff) {
        this.cusoff = cusoff;
    }
    public Integer getCuopdt() {
        return this.cuopdt;
    }
    
    public void setCuopdt(Integer cuopdt) {
        this.cuopdt = cuopdt;
    }
    public String getCutype() {
        return this.cutype;
    }
    
    public void setCutype(String cutype) {
        this.cutype = cutype;
    }
    public Integer getCusic() {
        return this.cusic;
    }
    
    public void setCusic(Integer cusic) {
        this.cusic = cusic;
    }
    public String getCusex() {
        return this.cusex;
    }
    
    public void setCusex(String cusex) {
        this.cusex = cusex;
    }
    public String getCurace() {
        return this.curace;
    }
    
    public void setCurace(String curace) {
        this.curace = curace;
    }
    public String getCuown() {
        return this.cuown;
    }
    
    public void setCuown(String cuown) {
        this.cuown = cuown;
    }
    public Integer getCuyrem() {
        return this.cuyrem;
    }
    
    public void setCuyrem(Integer cuyrem) {
        this.cuyrem = cuyrem;
    }
    public Integer getCuinc() {
        return this.cuinc;
    }
    
    public void setCuinc(Integer cuinc) {
        this.cuinc = cuinc;
    }
    public String getCusrin() {
        return this.cusrin;
    }
    
    public void setCusrin(String cusrin) {
        this.cusrin = cusrin;
    }
    public Integer getCubdte() {
        return this.cubdte;
    }
    
    public void setCubdte(Integer cubdte) {
        this.cubdte = cubdte;
    }
    public Integer getCudep() {
        return this.cudep;
    }
    
    public void setCudep(Integer cudep) {
        this.cudep = cudep;
    }
    public String getCuctc() {
        return this.cuctc;
    }
    
    public void setCuctc(String cuctc) {
        this.cuctc = cuctc;
    }
    public String getCuctct() {
        return this.cuctct;
    }
    
    public void setCuctct(String cuctct) {
        this.cuctct = cuctct;
    }
    public String getCucira() {
        return this.cucira;
    }
    
    public void setCucira(String cucira) {
        this.cucira = cucira;
    }
    public Integer getCumnbr() {
        return this.cumnbr;
    }
    
    public void setCumnbr(Integer cumnbr) {
        this.cumnbr = cumnbr;
    }
    public String getCuntid() {
        return this.cuntid;
    }
    
    public void setCuntid(String cuntid) {
        this.cuntid = cuntid;
    }
    public String getCuusr1() {
        return this.cuusr1;
    }
    
    public void setCuusr1(String cuusr1) {
        this.cuusr1 = cuusr1;
    }
    public String getCuclnk() {
        return this.cuclnk;
    }
    
    public void setCuclnk(String cuclnk) {
        this.cuclnk = cuclnk;
    }
    public String getCuusr3() {
        return this.cuusr3;
    }
    
    public void setCuusr3(String cuusr3) {
        this.cuusr3 = cuusr3;
    }
    public String getCucdch() {
        return this.cucdch;
    }
    
    public void setCucdch(String cucdch) {
        this.cucdch = cucdch;
    }
    public String getCucdcn() {
        return this.cucdcn;
    }
    
    public void setCucdcn(String cucdcn) {
        this.cucdcn = cucdcn;
    }
    public Integer getCucdcd() {
        return this.cucdcd;
    }
    
    public void setCucdcd(Integer cucdcd) {
        this.cucdcd = cucdcd;
    }
    public String getCucmch() {
        return this.cucmch;
    }
    
    public void setCucmch(String cucmch) {
        this.cucmch = cucmch;
    }
    public String getCucmnr() {
        return this.cucmnr;
    }
    
    public void setCucmnr(String cucmnr) {
        this.cucmnr = cucmnr;
    }
    public Integer getCucmcd() {
        return this.cucmcd;
    }
    
    public void setCucmcd(Integer cucmcd) {
        this.cucmcd = cucmcd;
    }
    public String getCucvsh() {
        return this.cucvsh;
    }
    
    public void setCucvsh(String cucvsh) {
        this.cucvsh = cucvsh;
    }
    public String getCucvcn() {
        return this.cucvcn;
    }
    
    public void setCucvcn(String cucvcn) {
        this.cucvcn = cucvcn;
    }
    public Integer getCucvcd() {
        return this.cucvcd;
    }
    
    public void setCucvcd(Integer cucvcd) {
        this.cucvcd = cucvcd;
    }
    public String getCucath() {
        return this.cucath;
    }
    
    public void setCucath(String cucath) {
        this.cucath = cucath;
    }
    public String getCucatn() {
        return this.cucatn;
    }
    
    public void setCucatn(String cucatn) {
        this.cucatn = cucatn;
    }
    public Integer getCucatd() {
        return this.cucatd;
    }
    
    public void setCucatd(Integer cucatd) {
        this.cucatd = cucatd;
    }
    public String getCuclng() {
        return this.cuclng;
    }
    
    public void setCuclng(String cuclng) {
        this.cuclng = cuclng;
    }
    public Integer getCucccd() {
        return this.cucccd;
    }
    
    public void setCucccd(Integer cucccd) {
        this.cucccd = cucccd;
    }
    public Integer getCulglr() {
        return this.culglr;
    }
    
    public void setCulglr(Integer culglr) {
        this.culglr = culglr;
    }
    public BigDecimal getCucwhp() {
        return this.cucwhp;
    }
    
    public void setCucwhp(BigDecimal cucwhp) {
        this.cucwhp = cucwhp;
    }
    public String getCucpsp() {
        return this.cucpsp;
    }
    
    public void setCucpsp(String cucpsp) {
        this.cucpsp = cucpsp;
    }
    public String getCuctxn() {
        return this.cuctxn;
    }
    
    public void setCuctxn(String cuctxn) {
        this.cuctxn = cuctxn;
    }
    public Integer getCucprf() {
        return this.cucprf;
    }
    
    public void setCucprf(Integer cucprf) {
        this.cucprf = cucprf;
    }
    public String getCushky() {
        return this.cushky;
    }
    
    public void setCushky(String cushky) {
        this.cushky = cushky;
    }
    public Integer getCuitld() {
        return this.cuitld;
    }
    
    public void setCuitld(Integer cuitld) {
        this.cuitld = cuitld;
    }
    public String getCupstl() {
        return this.cupstl;
    }
    
    public void setCupstl(String cupstl) {
        this.cupstl = cupstl;
    }
    public String getBlk26() {
        return this.blk26;
    }
    
    public void setBlk26(String blk26) {
        this.blk26 = blk26;
    }




}


