package com.ciessa.museum.model.legacy;
// Generated Jul 30, 2018 8:24:30 PM by Hibernate Tools 3.2.2.GA



/**
 * Cuxrf1 generated by hbm2java
 */
public class Cuxrf1  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer cuxbk;
     private String cuxrec;
     private String cux1cs;
     private Integer cux1ap;
     private Integer cux1ty;
     private Long cux1ac;
     private String cuxrel;
     private Integer cuxbrc;
     private String cuxsts;
     private Integer cuxfch;

    public Cuxrf1() {
    }

	
    public Cuxrf1(String pkid) {
        this.pkid = pkid;
    }
    public Cuxrf1(String pkid, String member, Integer cuxbk, String cuxrec, String cux1cs, Integer cux1ap, Integer cux1ty, Long cux1ac, String cuxrel, Integer cuxbrc, String cuxsts, Integer cuxfch) {
       this.pkid = pkid;
       this.member = member;
       this.cuxbk = cuxbk;
       this.cuxrec = cuxrec;
       this.cux1cs = cux1cs;
       this.cux1ap = cux1ap;
       this.cux1ty = cux1ty;
       this.cux1ac = cux1ac;
       this.cuxrel = cuxrel;
       this.cuxbrc = cuxbrc;
       this.cuxsts = cuxsts;
       this.cuxfch = cuxfch;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getCuxbk() {
        return this.cuxbk;
    }
    
    public void setCuxbk(Integer cuxbk) {
        this.cuxbk = cuxbk;
    }
    public String getCuxrec() {
        return this.cuxrec;
    }
    
    public void setCuxrec(String cuxrec) {
        this.cuxrec = cuxrec;
    }
    public String getCux1cs() {
        return this.cux1cs;
    }
    
    public void setCux1cs(String cux1cs) {
        this.cux1cs = cux1cs;
    }
    public Integer getCux1ap() {
        return this.cux1ap;
    }
    
    public void setCux1ap(Integer cux1ap) {
        this.cux1ap = cux1ap;
    }
    public Integer getCux1ty() {
        return this.cux1ty;
    }
    
    public void setCux1ty(Integer cux1ty) {
        this.cux1ty = cux1ty;
    }
    public Long getCux1ac() {
        return this.cux1ac;
    }
    
    public void setCux1ac(Long cux1ac) {
        this.cux1ac = cux1ac;
    }
    public String getCuxrel() {
        return this.cuxrel;
    }
    
    public void setCuxrel(String cuxrel) {
        this.cuxrel = cuxrel;
    }
    public Integer getCuxbrc() {
        return this.cuxbrc;
    }
    
    public void setCuxbrc(Integer cuxbrc) {
        this.cuxbrc = cuxbrc;
    }
    public String getCuxsts() {
        return this.cuxsts;
    }
    
    public void setCuxsts(String cuxsts) {
        this.cuxsts = cuxsts;
    }
    public Integer getCuxfch() {
        return this.cuxfch;
    }
    
    public void setCuxfch(Integer cuxfch) {
        this.cuxfch = cuxfch;
    }




}


