package com.ciessa.museum.model.legacy;
// Generated May 28, 2018 9:18:53 PM by Hibernate Tools 3.2.2.GA



/**
 * Grmcda generated by hbm2java
 */
public class Grmcda  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Long ryrmcn;
     private String rystat;
     private Integer rybrcd;
     private Integer ryaqdt;
     private String rycpcn;
     private String ryciin;
     private Integer rystcd;
     private Integer rylssd;
     private String ryrgno;
     private Integer ryrgdt;
     private Integer rybsfv;
     private Integer rycoyb;
     private String ryciri;
     private String ryivas;
     private Integer ryyiva;
     private String rycutx;
     private Long rygrin;
     private Integer ryygri;
     private Integer rydpnn;
     private String ryriin;
     private Integer ryanrd;
     private Integer rylsnd;
     private Long rylsns;
     private Integer ryylsn;
     private Integer rylsyd;
     private Long rylsys;
     private Integer ryylsy;
     private Integer rylsad;
     private Long rylsas;
     private Integer ryylsa;
     private Integer rylsld;
     private Long rylsls;
     private Integer ryylsl;
     private Integer rybccd;
     private Integer rycoct;
     private Integer ryfisc;
     private Integer ryyfis;
     private String rycres;
     private String ryempy;
     private String ryecgi;
     private String ryecgo;
     private String ryacde;
     private String ryauti;
     private String ryausr;
     private Integer ryadte;
     private Integer ryatme;

    public Grmcda() {
    }

	
    public Grmcda(String pkid) {
        this.pkid = pkid;
    }
    public Grmcda(String pkid, String member, Long ryrmcn, String rystat, Integer rybrcd, Integer ryaqdt, String rycpcn, String ryciin, Integer rystcd, Integer rylssd, String ryrgno, Integer ryrgdt, Integer rybsfv, Integer rycoyb, String ryciri, String ryivas, Integer ryyiva, String rycutx, Long rygrin, Integer ryygri, Integer rydpnn, String ryriin, Integer ryanrd, Integer rylsnd, Long rylsns, Integer ryylsn, Integer rylsyd, Long rylsys, Integer ryylsy, Integer rylsad, Long rylsas, Integer ryylsa, Integer rylsld, Long rylsls, Integer ryylsl, Integer rybccd, Integer rycoct, Integer ryfisc, Integer ryyfis, String rycres, String ryempy, String ryecgi, String ryecgo, String ryacde, String ryauti, String ryausr, Integer ryadte, Integer ryatme) {
       this.pkid = pkid;
       this.member = member;
       this.ryrmcn = ryrmcn;
       this.rystat = rystat;
       this.rybrcd = rybrcd;
       this.ryaqdt = ryaqdt;
       this.rycpcn = rycpcn;
       this.ryciin = ryciin;
       this.rystcd = rystcd;
       this.rylssd = rylssd;
       this.ryrgno = ryrgno;
       this.ryrgdt = ryrgdt;
       this.rybsfv = rybsfv;
       this.rycoyb = rycoyb;
       this.ryciri = ryciri;
       this.ryivas = ryivas;
       this.ryyiva = ryyiva;
       this.rycutx = rycutx;
       this.rygrin = rygrin;
       this.ryygri = ryygri;
       this.rydpnn = rydpnn;
       this.ryriin = ryriin;
       this.ryanrd = ryanrd;
       this.rylsnd = rylsnd;
       this.rylsns = rylsns;
       this.ryylsn = ryylsn;
       this.rylsyd = rylsyd;
       this.rylsys = rylsys;
       this.ryylsy = ryylsy;
       this.rylsad = rylsad;
       this.rylsas = rylsas;
       this.ryylsa = ryylsa;
       this.rylsld = rylsld;
       this.rylsls = rylsls;
       this.ryylsl = ryylsl;
       this.rybccd = rybccd;
       this.rycoct = rycoct;
       this.ryfisc = ryfisc;
       this.ryyfis = ryyfis;
       this.rycres = rycres;
       this.ryempy = ryempy;
       this.ryecgi = ryecgi;
       this.ryecgo = ryecgo;
       this.ryacde = ryacde;
       this.ryauti = ryauti;
       this.ryausr = ryausr;
       this.ryadte = ryadte;
       this.ryatme = ryatme;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Long getRyrmcn() {
        return this.ryrmcn;
    }
    
    public void setRyrmcn(Long ryrmcn) {
        this.ryrmcn = ryrmcn;
    }
    public String getRystat() {
        return this.rystat;
    }
    
    public void setRystat(String rystat) {
        this.rystat = rystat;
    }
    public Integer getRybrcd() {
        return this.rybrcd;
    }
    
    public void setRybrcd(Integer rybrcd) {
        this.rybrcd = rybrcd;
    }
    public Integer getRyaqdt() {
        return this.ryaqdt;
    }
    
    public void setRyaqdt(Integer ryaqdt) {
        this.ryaqdt = ryaqdt;
    }
    public String getRycpcn() {
        return this.rycpcn;
    }
    
    public void setRycpcn(String rycpcn) {
        this.rycpcn = rycpcn;
    }
    public String getRyciin() {
        return this.ryciin;
    }
    
    public void setRyciin(String ryciin) {
        this.ryciin = ryciin;
    }
    public Integer getRystcd() {
        return this.rystcd;
    }
    
    public void setRystcd(Integer rystcd) {
        this.rystcd = rystcd;
    }
    public Integer getRylssd() {
        return this.rylssd;
    }
    
    public void setRylssd(Integer rylssd) {
        this.rylssd = rylssd;
    }
    public String getRyrgno() {
        return this.ryrgno;
    }
    
    public void setRyrgno(String ryrgno) {
        this.ryrgno = ryrgno;
    }
    public Integer getRyrgdt() {
        return this.ryrgdt;
    }
    
    public void setRyrgdt(Integer ryrgdt) {
        this.ryrgdt = ryrgdt;
    }
    public Integer getRybsfv() {
        return this.rybsfv;
    }
    
    public void setRybsfv(Integer rybsfv) {
        this.rybsfv = rybsfv;
    }
    public Integer getRycoyb() {
        return this.rycoyb;
    }
    
    public void setRycoyb(Integer rycoyb) {
        this.rycoyb = rycoyb;
    }
    public String getRyciri() {
        return this.ryciri;
    }
    
    public void setRyciri(String ryciri) {
        this.ryciri = ryciri;
    }
    public String getRyivas() {
        return this.ryivas;
    }
    
    public void setRyivas(String ryivas) {
        this.ryivas = ryivas;
    }
    public Integer getRyyiva() {
        return this.ryyiva;
    }
    
    public void setRyyiva(Integer ryyiva) {
        this.ryyiva = ryyiva;
    }
    public String getRycutx() {
        return this.rycutx;
    }
    
    public void setRycutx(String rycutx) {
        this.rycutx = rycutx;
    }
    public Long getRygrin() {
        return this.rygrin;
    }
    
    public void setRygrin(Long rygrin) {
        this.rygrin = rygrin;
    }
    public Integer getRyygri() {
        return this.ryygri;
    }
    
    public void setRyygri(Integer ryygri) {
        this.ryygri = ryygri;
    }
    public Integer getRydpnn() {
        return this.rydpnn;
    }
    
    public void setRydpnn(Integer rydpnn) {
        this.rydpnn = rydpnn;
    }
    public String getRyriin() {
        return this.ryriin;
    }
    
    public void setRyriin(String ryriin) {
        this.ryriin = ryriin;
    }
    public Integer getRyanrd() {
        return this.ryanrd;
    }
    
    public void setRyanrd(Integer ryanrd) {
        this.ryanrd = ryanrd;
    }
    public Integer getRylsnd() {
        return this.rylsnd;
    }
    
    public void setRylsnd(Integer rylsnd) {
        this.rylsnd = rylsnd;
    }
    public Long getRylsns() {
        return this.rylsns;
    }
    
    public void setRylsns(Long rylsns) {
        this.rylsns = rylsns;
    }
    public Integer getRyylsn() {
        return this.ryylsn;
    }
    
    public void setRyylsn(Integer ryylsn) {
        this.ryylsn = ryylsn;
    }
    public Integer getRylsyd() {
        return this.rylsyd;
    }
    
    public void setRylsyd(Integer rylsyd) {
        this.rylsyd = rylsyd;
    }
    public Long getRylsys() {
        return this.rylsys;
    }
    
    public void setRylsys(Long rylsys) {
        this.rylsys = rylsys;
    }
    public Integer getRyylsy() {
        return this.ryylsy;
    }
    
    public void setRyylsy(Integer ryylsy) {
        this.ryylsy = ryylsy;
    }
    public Integer getRylsad() {
        return this.rylsad;
    }
    
    public void setRylsad(Integer rylsad) {
        this.rylsad = rylsad;
    }
    public Long getRylsas() {
        return this.rylsas;
    }
    
    public void setRylsas(Long rylsas) {
        this.rylsas = rylsas;
    }
    public Integer getRyylsa() {
        return this.ryylsa;
    }
    
    public void setRyylsa(Integer ryylsa) {
        this.ryylsa = ryylsa;
    }
    public Integer getRylsld() {
        return this.rylsld;
    }
    
    public void setRylsld(Integer rylsld) {
        this.rylsld = rylsld;
    }
    public Long getRylsls() {
        return this.rylsls;
    }
    
    public void setRylsls(Long rylsls) {
        this.rylsls = rylsls;
    }
    public Integer getRyylsl() {
        return this.ryylsl;
    }
    
    public void setRyylsl(Integer ryylsl) {
        this.ryylsl = ryylsl;
    }
    public Integer getRybccd() {
        return this.rybccd;
    }
    
    public void setRybccd(Integer rybccd) {
        this.rybccd = rybccd;
    }
    public Integer getRycoct() {
        return this.rycoct;
    }
    
    public void setRycoct(Integer rycoct) {
        this.rycoct = rycoct;
    }
    public Integer getRyfisc() {
        return this.ryfisc;
    }
    
    public void setRyfisc(Integer ryfisc) {
        this.ryfisc = ryfisc;
    }
    public Integer getRyyfis() {
        return this.ryyfis;
    }
    
    public void setRyyfis(Integer ryyfis) {
        this.ryyfis = ryyfis;
    }
    public String getRycres() {
        return this.rycres;
    }
    
    public void setRycres(String rycres) {
        this.rycres = rycres;
    }
    public String getRyempy() {
        return this.ryempy;
    }
    
    public void setRyempy(String ryempy) {
        this.ryempy = ryempy;
    }
    public String getRyecgi() {
        return this.ryecgi;
    }
    
    public void setRyecgi(String ryecgi) {
        this.ryecgi = ryecgi;
    }
    public String getRyecgo() {
        return this.ryecgo;
    }
    
    public void setRyecgo(String ryecgo) {
        this.ryecgo = ryecgo;
    }
    public String getRyacde() {
        return this.ryacde;
    }
    
    public void setRyacde(String ryacde) {
        this.ryacde = ryacde;
    }
    public String getRyauti() {
        return this.ryauti;
    }
    
    public void setRyauti(String ryauti) {
        this.ryauti = ryauti;
    }
    public String getRyausr() {
        return this.ryausr;
    }
    
    public void setRyausr(String ryausr) {
        this.ryausr = ryausr;
    }
    public Integer getRyadte() {
        return this.ryadte;
    }
    
    public void setRyadte(Integer ryadte) {
        this.ryadte = ryadte;
    }
    public Integer getRyatme() {
        return this.ryatme;
    }
    
    public void setRyatme(Integer ryatme) {
        this.ryatme = ryatme;
    }




}


