package com.ciessa.museum.model.legacy;
// Generated Dec 11, 2018 7:50:29 PM by Hibernate Tools 3.2.2.GA



/**
 * Grmcus generated by hbm2java
 */
public class Grmcus  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Long rbrmcn;
     private String rbaico;
     private String rbaitm;
     private String rbciin;
     private String rbculs;
     private String rbcupi;
     private String rbcuty;
     private Integer rbddln;
     private Integer rbidcn;
     private String rbppno;
     private String rbdngi;
     private Integer rbcurd;
     private Integer rbcuri;
     private Integer rbcurn;
     private String rbacde;
     private String rbstat;
     private Integer rbpkco;
     private String rbstpk;
     private String rbshrn;
     private Integer rbsgcd;
     private String rbstsg;
     private String rbtdlc;

    public Grmcus() {
    }

	
    public Grmcus(String pkid) {
        this.pkid = pkid;
    }
    public Grmcus(String pkid, String member, Long rbrmcn, String rbaico, String rbaitm, String rbciin, String rbculs, String rbcupi, String rbcuty, Integer rbddln, Integer rbidcn, String rbppno, String rbdngi, Integer rbcurd, Integer rbcuri, Integer rbcurn, String rbacde, String rbstat, Integer rbpkco, String rbstpk, String rbshrn, Integer rbsgcd, String rbstsg, String rbtdlc) {
       this.pkid = pkid;
       this.member = member;
       this.rbrmcn = rbrmcn;
       this.rbaico = rbaico;
       this.rbaitm = rbaitm;
       this.rbciin = rbciin;
       this.rbculs = rbculs;
       this.rbcupi = rbcupi;
       this.rbcuty = rbcuty;
       this.rbddln = rbddln;
       this.rbidcn = rbidcn;
       this.rbppno = rbppno;
       this.rbdngi = rbdngi;
       this.rbcurd = rbcurd;
       this.rbcuri = rbcuri;
       this.rbcurn = rbcurn;
       this.rbacde = rbacde;
       this.rbstat = rbstat;
       this.rbpkco = rbpkco;
       this.rbstpk = rbstpk;
       this.rbshrn = rbshrn;
       this.rbsgcd = rbsgcd;
       this.rbstsg = rbstsg;
       this.rbtdlc = rbtdlc;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Long getRbrmcn() {
        return this.rbrmcn;
    }
    
    public void setRbrmcn(Long rbrmcn) {
        this.rbrmcn = rbrmcn;
    }
    public String getRbaico() {
        return this.rbaico;
    }
    
    public void setRbaico(String rbaico) {
        this.rbaico = rbaico;
    }
    public String getRbaitm() {
        return this.rbaitm;
    }
    
    public void setRbaitm(String rbaitm) {
        this.rbaitm = rbaitm;
    }
    public String getRbciin() {
        return this.rbciin;
    }
    
    public void setRbciin(String rbciin) {
        this.rbciin = rbciin;
    }
    public String getRbculs() {
        return this.rbculs;
    }
    
    public void setRbculs(String rbculs) {
        this.rbculs = rbculs;
    }
    public String getRbcupi() {
        return this.rbcupi;
    }
    
    public void setRbcupi(String rbcupi) {
        this.rbcupi = rbcupi;
    }
    public String getRbcuty() {
        return this.rbcuty;
    }
    
    public void setRbcuty(String rbcuty) {
        this.rbcuty = rbcuty;
    }
    public Integer getRbddln() {
        return this.rbddln;
    }
    
    public void setRbddln(Integer rbddln) {
        this.rbddln = rbddln;
    }
    public Integer getRbidcn() {
        return this.rbidcn;
    }
    
    public void setRbidcn(Integer rbidcn) {
        this.rbidcn = rbidcn;
    }
    public String getRbppno() {
        return this.rbppno;
    }
    
    public void setRbppno(String rbppno) {
        this.rbppno = rbppno;
    }
    public String getRbdngi() {
        return this.rbdngi;
    }
    
    public void setRbdngi(String rbdngi) {
        this.rbdngi = rbdngi;
    }
    public Integer getRbcurd() {
        return this.rbcurd;
    }
    
    public void setRbcurd(Integer rbcurd) {
        this.rbcurd = rbcurd;
    }
    public Integer getRbcuri() {
        return this.rbcuri;
    }
    
    public void setRbcuri(Integer rbcuri) {
        this.rbcuri = rbcuri;
    }
    public Integer getRbcurn() {
        return this.rbcurn;
    }
    
    public void setRbcurn(Integer rbcurn) {
        this.rbcurn = rbcurn;
    }
    public String getRbacde() {
        return this.rbacde;
    }
    
    public void setRbacde(String rbacde) {
        this.rbacde = rbacde;
    }
    public String getRbstat() {
        return this.rbstat;
    }
    
    public void setRbstat(String rbstat) {
        this.rbstat = rbstat;
    }
    public Integer getRbpkco() {
        return this.rbpkco;
    }
    
    public void setRbpkco(Integer rbpkco) {
        this.rbpkco = rbpkco;
    }
    public String getRbstpk() {
        return this.rbstpk;
    }
    
    public void setRbstpk(String rbstpk) {
        this.rbstpk = rbstpk;
    }
    public String getRbshrn() {
        return this.rbshrn;
    }
    
    public void setRbshrn(String rbshrn) {
        this.rbshrn = rbshrn;
    }
    public Integer getRbsgcd() {
        return this.rbsgcd;
    }
    
    public void setRbsgcd(Integer rbsgcd) {
        this.rbsgcd = rbsgcd;
    }
    public String getRbstsg() {
        return this.rbstsg;
    }
    
    public void setRbstsg(String rbstsg) {
        this.rbstsg = rbstsg;
    }
    public String getRbtdlc() {
        return this.rbtdlc;
    }
    
    public void setRbtdlc(String rbtdlc) {
        this.rbtdlc = rbtdlc;
    }




}


