package com.ciessa.museum.model.legacy;
// Generated Sep 10, 2018 9:32:23 PM by Hibernate Tools 3.2.2.GA



/**
 * Grmida generated by hbm2java
 */
public class Grmida  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Long rirmcn;
     private String ristat;
     private Integer ribrcd;
     private Integer riaqdt;
     private String rilsnm;
     private String rifsnm;
     private String rispmn;
     private String ridcty;
     private Integer riddln;
     private Integer riidcn;
     private String riidcc;
     private Integer riidcv;
     private String rippno;
     private Integer rippis;
     private String riciin;
     private String riciri;
     private Integer riczsv;
     private Integer ribhdt;
     private Integer ribhpl;
     private Integer risexv;
     private Integer rimrsv;
     private Integer riymrs;
     private Integer riclnq;
     private Integer riyclq;
     private Integer ricldq;
     private Long rispri;
     private String rifmfn;
     private String rimnmt;
     private String riempi;
     private Integer riemhn;
     private String riempy;
     private Integer riyemy;
     private Integer rifisc;
     private Integer riyfis;
     private String riivas;
     private Integer riyiva;
     private Integer ribccd;
     private String ricutx;
     private Integer riyctx;
     private String rilcpi;
     private String rimacn;
     private Integer ribsfv;
     private String ridpri;
     private String ripost;
     private Integer riposv;
     private Integer rimayw;
     private String riprof;
     private Integer riprov;
     private Integer riymac;
     private Long rimags;
     private Long rimvgs;
     private Integer riymag;
     private String ricuvp;
     private String ricuph;
     private String riacde;
     private String riauti;
     private String riausr;
     private Integer riadte;
     private Integer riatme;
     private String riidct;
     private Integer riaccd;

    public Grmida() {
    }

	
    public Grmida(String pkid) {
        this.pkid = pkid;
    }
    public Grmida(String pkid, String member, Long rirmcn, String ristat, Integer ribrcd, Integer riaqdt, String rilsnm, String rifsnm, String rispmn, String ridcty, Integer riddln, Integer riidcn, String riidcc, Integer riidcv, String rippno, Integer rippis, String riciin, String riciri, Integer riczsv, Integer ribhdt, Integer ribhpl, Integer risexv, Integer rimrsv, Integer riymrs, Integer riclnq, Integer riyclq, Integer ricldq, Long rispri, String rifmfn, String rimnmt, String riempi, Integer riemhn, String riempy, Integer riyemy, Integer rifisc, Integer riyfis, String riivas, Integer riyiva, Integer ribccd, String ricutx, Integer riyctx, String rilcpi, String rimacn, Integer ribsfv, String ridpri, String ripost, Integer riposv, Integer rimayw, String riprof, Integer riprov, Integer riymac, Long rimags, Long rimvgs, Integer riymag, String ricuvp, String ricuph, String riacde, String riauti, String riausr, Integer riadte, Integer riatme, String riidct, Integer riaccd) {
       this.pkid = pkid;
       this.member = member;
       this.rirmcn = rirmcn;
       this.ristat = ristat;
       this.ribrcd = ribrcd;
       this.riaqdt = riaqdt;
       this.rilsnm = rilsnm;
       this.rifsnm = rifsnm;
       this.rispmn = rispmn;
       this.ridcty = ridcty;
       this.riddln = riddln;
       this.riidcn = riidcn;
       this.riidcc = riidcc;
       this.riidcv = riidcv;
       this.rippno = rippno;
       this.rippis = rippis;
       this.riciin = riciin;
       this.riciri = riciri;
       this.riczsv = riczsv;
       this.ribhdt = ribhdt;
       this.ribhpl = ribhpl;
       this.risexv = risexv;
       this.rimrsv = rimrsv;
       this.riymrs = riymrs;
       this.riclnq = riclnq;
       this.riyclq = riyclq;
       this.ricldq = ricldq;
       this.rispri = rispri;
       this.rifmfn = rifmfn;
       this.rimnmt = rimnmt;
       this.riempi = riempi;
       this.riemhn = riemhn;
       this.riempy = riempy;
       this.riyemy = riyemy;
       this.rifisc = rifisc;
       this.riyfis = riyfis;
       this.riivas = riivas;
       this.riyiva = riyiva;
       this.ribccd = ribccd;
       this.ricutx = ricutx;
       this.riyctx = riyctx;
       this.rilcpi = rilcpi;
       this.rimacn = rimacn;
       this.ribsfv = ribsfv;
       this.ridpri = ridpri;
       this.ripost = ripost;
       this.riposv = riposv;
       this.rimayw = rimayw;
       this.riprof = riprof;
       this.riprov = riprov;
       this.riymac = riymac;
       this.rimags = rimags;
       this.rimvgs = rimvgs;
       this.riymag = riymag;
       this.ricuvp = ricuvp;
       this.ricuph = ricuph;
       this.riacde = riacde;
       this.riauti = riauti;
       this.riausr = riausr;
       this.riadte = riadte;
       this.riatme = riatme;
       this.riidct = riidct;
       this.riaccd = riaccd;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Long getRirmcn() {
        return this.rirmcn;
    }
    
    public void setRirmcn(Long rirmcn) {
        this.rirmcn = rirmcn;
    }
    public String getRistat() {
        return this.ristat;
    }
    
    public void setRistat(String ristat) {
        this.ristat = ristat;
    }
    public Integer getRibrcd() {
        return this.ribrcd;
    }
    
    public void setRibrcd(Integer ribrcd) {
        this.ribrcd = ribrcd;
    }
    public Integer getRiaqdt() {
        return this.riaqdt;
    }
    
    public void setRiaqdt(Integer riaqdt) {
        this.riaqdt = riaqdt;
    }
    public String getRilsnm() {
        return this.rilsnm;
    }
    
    public void setRilsnm(String rilsnm) {
        this.rilsnm = rilsnm;
    }
    public String getRifsnm() {
        return this.rifsnm;
    }
    
    public void setRifsnm(String rifsnm) {
        this.rifsnm = rifsnm;
    }
    public String getRispmn() {
        return this.rispmn;
    }
    
    public void setRispmn(String rispmn) {
        this.rispmn = rispmn;
    }
    public String getRidcty() {
        return this.ridcty;
    }
    
    public void setRidcty(String ridcty) {
        this.ridcty = ridcty;
    }
    public Integer getRiddln() {
        return this.riddln;
    }
    
    public void setRiddln(Integer riddln) {
        this.riddln = riddln;
    }
    public Integer getRiidcn() {
        return this.riidcn;
    }
    
    public void setRiidcn(Integer riidcn) {
        this.riidcn = riidcn;
    }
    public String getRiidcc() {
        return this.riidcc;
    }
    
    public void setRiidcc(String riidcc) {
        this.riidcc = riidcc;
    }
    public Integer getRiidcv() {
        return this.riidcv;
    }
    
    public void setRiidcv(Integer riidcv) {
        this.riidcv = riidcv;
    }
    public String getRippno() {
        return this.rippno;
    }
    
    public void setRippno(String rippno) {
        this.rippno = rippno;
    }
    public Integer getRippis() {
        return this.rippis;
    }
    
    public void setRippis(Integer rippis) {
        this.rippis = rippis;
    }
    public String getRiciin() {
        return this.riciin;
    }
    
    public void setRiciin(String riciin) {
        this.riciin = riciin;
    }
    public String getRiciri() {
        return this.riciri;
    }
    
    public void setRiciri(String riciri) {
        this.riciri = riciri;
    }
    public Integer getRiczsv() {
        return this.riczsv;
    }
    
    public void setRiczsv(Integer riczsv) {
        this.riczsv = riczsv;
    }
    public Integer getRibhdt() {
        return this.ribhdt;
    }
    
    public void setRibhdt(Integer ribhdt) {
        this.ribhdt = ribhdt;
    }
    public Integer getRibhpl() {
        return this.ribhpl;
    }
    
    public void setRibhpl(Integer ribhpl) {
        this.ribhpl = ribhpl;
    }
    public Integer getRisexv() {
        return this.risexv;
    }
    
    public void setRisexv(Integer risexv) {
        this.risexv = risexv;
    }
    public Integer getRimrsv() {
        return this.rimrsv;
    }
    
    public void setRimrsv(Integer rimrsv) {
        this.rimrsv = rimrsv;
    }
    public Integer getRiymrs() {
        return this.riymrs;
    }
    
    public void setRiymrs(Integer riymrs) {
        this.riymrs = riymrs;
    }
    public Integer getRiclnq() {
        return this.riclnq;
    }
    
    public void setRiclnq(Integer riclnq) {
        this.riclnq = riclnq;
    }
    public Integer getRiyclq() {
        return this.riyclq;
    }
    
    public void setRiyclq(Integer riyclq) {
        this.riyclq = riyclq;
    }
    public Integer getRicldq() {
        return this.ricldq;
    }
    
    public void setRicldq(Integer ricldq) {
        this.ricldq = ricldq;
    }
    public Long getRispri() {
        return this.rispri;
    }
    
    public void setRispri(Long rispri) {
        this.rispri = rispri;
    }
    public String getRifmfn() {
        return this.rifmfn;
    }
    
    public void setRifmfn(String rifmfn) {
        this.rifmfn = rifmfn;
    }
    public String getRimnmt() {
        return this.rimnmt;
    }
    
    public void setRimnmt(String rimnmt) {
        this.rimnmt = rimnmt;
    }
    public String getRiempi() {
        return this.riempi;
    }
    
    public void setRiempi(String riempi) {
        this.riempi = riempi;
    }
    public Integer getRiemhn() {
        return this.riemhn;
    }
    
    public void setRiemhn(Integer riemhn) {
        this.riemhn = riemhn;
    }
    public String getRiempy() {
        return this.riempy;
    }
    
    public void setRiempy(String riempy) {
        this.riempy = riempy;
    }
    public Integer getRiyemy() {
        return this.riyemy;
    }
    
    public void setRiyemy(Integer riyemy) {
        this.riyemy = riyemy;
    }
    public Integer getRifisc() {
        return this.rifisc;
    }
    
    public void setRifisc(Integer rifisc) {
        this.rifisc = rifisc;
    }
    public Integer getRiyfis() {
        return this.riyfis;
    }
    
    public void setRiyfis(Integer riyfis) {
        this.riyfis = riyfis;
    }
    public String getRiivas() {
        return this.riivas;
    }
    
    public void setRiivas(String riivas) {
        this.riivas = riivas;
    }
    public Integer getRiyiva() {
        return this.riyiva;
    }
    
    public void setRiyiva(Integer riyiva) {
        this.riyiva = riyiva;
    }
    public Integer getRibccd() {
        return this.ribccd;
    }
    
    public void setRibccd(Integer ribccd) {
        this.ribccd = ribccd;
    }
    public String getRicutx() {
        return this.ricutx;
    }
    
    public void setRicutx(String ricutx) {
        this.ricutx = ricutx;
    }
    public Integer getRiyctx() {
        return this.riyctx;
    }
    
    public void setRiyctx(Integer riyctx) {
        this.riyctx = riyctx;
    }
    public String getRilcpi() {
        return this.rilcpi;
    }
    
    public void setRilcpi(String rilcpi) {
        this.rilcpi = rilcpi;
    }
    public String getRimacn() {
        return this.rimacn;
    }
    
    public void setRimacn(String rimacn) {
        this.rimacn = rimacn;
    }
    public Integer getRibsfv() {
        return this.ribsfv;
    }
    
    public void setRibsfv(Integer ribsfv) {
        this.ribsfv = ribsfv;
    }
    public String getRidpri() {
        return this.ridpri;
    }
    
    public void setRidpri(String ridpri) {
        this.ridpri = ridpri;
    }
    public String getRipost() {
        return this.ripost;
    }
    
    public void setRipost(String ripost) {
        this.ripost = ripost;
    }
    public Integer getRiposv() {
        return this.riposv;
    }
    
    public void setRiposv(Integer riposv) {
        this.riposv = riposv;
    }
    public Integer getRimayw() {
        return this.rimayw;
    }
    
    public void setRimayw(Integer rimayw) {
        this.rimayw = rimayw;
    }
    public String getRiprof() {
        return this.riprof;
    }
    
    public void setRiprof(String riprof) {
        this.riprof = riprof;
    }
    public Integer getRiprov() {
        return this.riprov;
    }
    
    public void setRiprov(Integer riprov) {
        this.riprov = riprov;
    }
    public Integer getRiymac() {
        return this.riymac;
    }
    
    public void setRiymac(Integer riymac) {
        this.riymac = riymac;
    }
    public Long getRimags() {
        return this.rimags;
    }
    
    public void setRimags(Long rimags) {
        this.rimags = rimags;
    }
    public Long getRimvgs() {
        return this.rimvgs;
    }
    
    public void setRimvgs(Long rimvgs) {
        this.rimvgs = rimvgs;
    }
    public Integer getRiymag() {
        return this.riymag;
    }
    
    public void setRiymag(Integer riymag) {
        this.riymag = riymag;
    }
    public String getRicuvp() {
        return this.ricuvp;
    }
    
    public void setRicuvp(String ricuvp) {
        this.ricuvp = ricuvp;
    }
    public String getRicuph() {
        return this.ricuph;
    }
    
    public void setRicuph(String ricuph) {
        this.ricuph = ricuph;
    }
    public String getRiacde() {
        return this.riacde;
    }
    
    public void setRiacde(String riacde) {
        this.riacde = riacde;
    }
    public String getRiauti() {
        return this.riauti;
    }
    
    public void setRiauti(String riauti) {
        this.riauti = riauti;
    }
    public String getRiausr() {
        return this.riausr;
    }
    
    public void setRiausr(String riausr) {
        this.riausr = riausr;
    }
    public Integer getRiadte() {
        return this.riadte;
    }
    
    public void setRiadte(Integer riadte) {
        this.riadte = riadte;
    }
    public Integer getRiatme() {
        return this.riatme;
    }
    
    public void setRiatme(Integer riatme) {
        this.riatme = riatme;
    }
    public String getRiidct() {
        return this.riidct;
    }
    
    public void setRiidct(String riidct) {
        this.riidct = riidct;
    }
    public Integer getRiaccd() {
        return this.riaccd;
    }
    
    public void setRiaccd(Integer riaccd) {
        this.riaccd = riaccd;
    }




}


