package com.ciessa.museum.model.legacy;
// Generated Dec 8, 2018 1:27:28 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Saldom generated by hbm2java
 */
public class Saldom  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer cbank;
     private Integer ccta;
     private Long ncta;
     private Integer cbranc;
     private Integer cdivi;
     private Integer daasal;
     private Integer dmmsal;
     private String ssaxdi;
     private BigDecimal ssaman;
     private BigDecimal sinaan;
     private BigDecimal snuaan;
     private Integer dsadeu;
     private Integer dexaca;
     private Integer dexpto;
     private Integer dsapen;
     private Integer dsana;
     private Integer dsawo;
     private Integer dspdeu;
     private Integer depaca;
     private Integer deppto;
     private Integer dsppen;
     private Integer dspna;
     private Integer dspwo;
     private BigDecimal slpbac;
     private BigDecimal slpabl;
     private BigDecimal slpdes;
     private BigDecimal slpaba;
     private BigDecimal slpexc;
     private BigDecimal slpdde;
     private BigDecimal slpdex;
     private BigDecimal slpna;
     private BigDecimal slpwo;
     private BigDecimal slabac;
     private BigDecimal slaabl;
     private BigDecimal slades;
     private BigDecimal slaaba;
     private BigDecimal slaexc;
     private BigDecimal sladde;
     private BigDecimal sladex;
     private BigDecimal slana;
     private BigDecimal slawo;
     private BigDecimal nmabac;
     private BigDecimal nmaabl;
     private BigDecimal nmades;
     private BigDecimal nmaaba;
     private BigDecimal nmaexc;
     private BigDecimal nmadde;
     private BigDecimal nmadex;
     private BigDecimal nmana;
     private BigDecimal nmawo;
     private Integer diexna;
     private Integer ultpro;

    public Saldom() {
    }

	
    public Saldom(String pkid) {
        this.pkid = pkid;
    }
    public Saldom(String pkid, String member, Integer cbank, Integer ccta, Long ncta, Integer cbranc, Integer cdivi, Integer daasal, Integer dmmsal, String ssaxdi, BigDecimal ssaman, BigDecimal sinaan, BigDecimal snuaan, Integer dsadeu, Integer dexaca, Integer dexpto, Integer dsapen, Integer dsana, Integer dsawo, Integer dspdeu, Integer depaca, Integer deppto, Integer dsppen, Integer dspna, Integer dspwo, BigDecimal slpbac, BigDecimal slpabl, BigDecimal slpdes, BigDecimal slpaba, BigDecimal slpexc, BigDecimal slpdde, BigDecimal slpdex, BigDecimal slpna, BigDecimal slpwo, BigDecimal slabac, BigDecimal slaabl, BigDecimal slades, BigDecimal slaaba, BigDecimal slaexc, BigDecimal sladde, BigDecimal sladex, BigDecimal slana, BigDecimal slawo, BigDecimal nmabac, BigDecimal nmaabl, BigDecimal nmades, BigDecimal nmaaba, BigDecimal nmaexc, BigDecimal nmadde, BigDecimal nmadex, BigDecimal nmana, BigDecimal nmawo, Integer diexna, Integer ultpro) {
       this.pkid = pkid;
       this.member = member;
       this.cbank = cbank;
       this.ccta = ccta;
       this.ncta = ncta;
       this.cbranc = cbranc;
       this.cdivi = cdivi;
       this.daasal = daasal;
       this.dmmsal = dmmsal;
       this.ssaxdi = ssaxdi;
       this.ssaman = ssaman;
       this.sinaan = sinaan;
       this.snuaan = snuaan;
       this.dsadeu = dsadeu;
       this.dexaca = dexaca;
       this.dexpto = dexpto;
       this.dsapen = dsapen;
       this.dsana = dsana;
       this.dsawo = dsawo;
       this.dspdeu = dspdeu;
       this.depaca = depaca;
       this.deppto = deppto;
       this.dsppen = dsppen;
       this.dspna = dspna;
       this.dspwo = dspwo;
       this.slpbac = slpbac;
       this.slpabl = slpabl;
       this.slpdes = slpdes;
       this.slpaba = slpaba;
       this.slpexc = slpexc;
       this.slpdde = slpdde;
       this.slpdex = slpdex;
       this.slpna = slpna;
       this.slpwo = slpwo;
       this.slabac = slabac;
       this.slaabl = slaabl;
       this.slades = slades;
       this.slaaba = slaaba;
       this.slaexc = slaexc;
       this.sladde = sladde;
       this.sladex = sladex;
       this.slana = slana;
       this.slawo = slawo;
       this.nmabac = nmabac;
       this.nmaabl = nmaabl;
       this.nmades = nmades;
       this.nmaaba = nmaaba;
       this.nmaexc = nmaexc;
       this.nmadde = nmadde;
       this.nmadex = nmadex;
       this.nmana = nmana;
       this.nmawo = nmawo;
       this.diexna = diexna;
       this.ultpro = ultpro;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getCbank() {
        return this.cbank;
    }
    
    public void setCbank(Integer cbank) {
        this.cbank = cbank;
    }
    public Integer getCcta() {
        return this.ccta;
    }
    
    public void setCcta(Integer ccta) {
        this.ccta = ccta;
    }
    public Long getNcta() {
        return this.ncta;
    }
    
    public void setNcta(Long ncta) {
        this.ncta = ncta;
    }
    public Integer getCbranc() {
        return this.cbranc;
    }
    
    public void setCbranc(Integer cbranc) {
        this.cbranc = cbranc;
    }
    public Integer getCdivi() {
        return this.cdivi;
    }
    
    public void setCdivi(Integer cdivi) {
        this.cdivi = cdivi;
    }
    public Integer getDaasal() {
        return this.daasal;
    }
    
    public void setDaasal(Integer daasal) {
        this.daasal = daasal;
    }
    public Integer getDmmsal() {
        return this.dmmsal;
    }
    
    public void setDmmsal(Integer dmmsal) {
        this.dmmsal = dmmsal;
    }
    public String getSsaxdi() {
        return this.ssaxdi;
    }
    
    public void setSsaxdi(String ssaxdi) {
        this.ssaxdi = ssaxdi;
    }
    public BigDecimal getSsaman() {
        return this.ssaman;
    }
    
    public void setSsaman(BigDecimal ssaman) {
        this.ssaman = ssaman;
    }
    public BigDecimal getSinaan() {
        return this.sinaan;
    }
    
    public void setSinaan(BigDecimal sinaan) {
        this.sinaan = sinaan;
    }
    public BigDecimal getSnuaan() {
        return this.snuaan;
    }
    
    public void setSnuaan(BigDecimal snuaan) {
        this.snuaan = snuaan;
    }
    public Integer getDsadeu() {
        return this.dsadeu;
    }
    
    public void setDsadeu(Integer dsadeu) {
        this.dsadeu = dsadeu;
    }
    public Integer getDexaca() {
        return this.dexaca;
    }
    
    public void setDexaca(Integer dexaca) {
        this.dexaca = dexaca;
    }
    public Integer getDexpto() {
        return this.dexpto;
    }
    
    public void setDexpto(Integer dexpto) {
        this.dexpto = dexpto;
    }
    public Integer getDsapen() {
        return this.dsapen;
    }
    
    public void setDsapen(Integer dsapen) {
        this.dsapen = dsapen;
    }
    public Integer getDsana() {
        return this.dsana;
    }
    
    public void setDsana(Integer dsana) {
        this.dsana = dsana;
    }
    public Integer getDsawo() {
        return this.dsawo;
    }
    
    public void setDsawo(Integer dsawo) {
        this.dsawo = dsawo;
    }
    public Integer getDspdeu() {
        return this.dspdeu;
    }
    
    public void setDspdeu(Integer dspdeu) {
        this.dspdeu = dspdeu;
    }
    public Integer getDepaca() {
        return this.depaca;
    }
    
    public void setDepaca(Integer depaca) {
        this.depaca = depaca;
    }
    public Integer getDeppto() {
        return this.deppto;
    }
    
    public void setDeppto(Integer deppto) {
        this.deppto = deppto;
    }
    public Integer getDsppen() {
        return this.dsppen;
    }
    
    public void setDsppen(Integer dsppen) {
        this.dsppen = dsppen;
    }
    public Integer getDspna() {
        return this.dspna;
    }
    
    public void setDspna(Integer dspna) {
        this.dspna = dspna;
    }
    public Integer getDspwo() {
        return this.dspwo;
    }
    
    public void setDspwo(Integer dspwo) {
        this.dspwo = dspwo;
    }
    public BigDecimal getSlpbac() {
        return this.slpbac;
    }
    
    public void setSlpbac(BigDecimal slpbac) {
        this.slpbac = slpbac;
    }
    public BigDecimal getSlpabl() {
        return this.slpabl;
    }
    
    public void setSlpabl(BigDecimal slpabl) {
        this.slpabl = slpabl;
    }
    public BigDecimal getSlpdes() {
        return this.slpdes;
    }
    
    public void setSlpdes(BigDecimal slpdes) {
        this.slpdes = slpdes;
    }
    public BigDecimal getSlpaba() {
        return this.slpaba;
    }
    
    public void setSlpaba(BigDecimal slpaba) {
        this.slpaba = slpaba;
    }
    public BigDecimal getSlpexc() {
        return this.slpexc;
    }
    
    public void setSlpexc(BigDecimal slpexc) {
        this.slpexc = slpexc;
    }
    public BigDecimal getSlpdde() {
        return this.slpdde;
    }
    
    public void setSlpdde(BigDecimal slpdde) {
        this.slpdde = slpdde;
    }
    public BigDecimal getSlpdex() {
        return this.slpdex;
    }
    
    public void setSlpdex(BigDecimal slpdex) {
        this.slpdex = slpdex;
    }
    public BigDecimal getSlpna() {
        return this.slpna;
    }
    
    public void setSlpna(BigDecimal slpna) {
        this.slpna = slpna;
    }
    public BigDecimal getSlpwo() {
        return this.slpwo;
    }
    
    public void setSlpwo(BigDecimal slpwo) {
        this.slpwo = slpwo;
    }
    public BigDecimal getSlabac() {
        return this.slabac;
    }
    
    public void setSlabac(BigDecimal slabac) {
        this.slabac = slabac;
    }
    public BigDecimal getSlaabl() {
        return this.slaabl;
    }
    
    public void setSlaabl(BigDecimal slaabl) {
        this.slaabl = slaabl;
    }
    public BigDecimal getSlades() {
        return this.slades;
    }
    
    public void setSlades(BigDecimal slades) {
        this.slades = slades;
    }
    public BigDecimal getSlaaba() {
        return this.slaaba;
    }
    
    public void setSlaaba(BigDecimal slaaba) {
        this.slaaba = slaaba;
    }
    public BigDecimal getSlaexc() {
        return this.slaexc;
    }
    
    public void setSlaexc(BigDecimal slaexc) {
        this.slaexc = slaexc;
    }
    public BigDecimal getSladde() {
        return this.sladde;
    }
    
    public void setSladde(BigDecimal sladde) {
        this.sladde = sladde;
    }
    public BigDecimal getSladex() {
        return this.sladex;
    }
    
    public void setSladex(BigDecimal sladex) {
        this.sladex = sladex;
    }
    public BigDecimal getSlana() {
        return this.slana;
    }
    
    public void setSlana(BigDecimal slana) {
        this.slana = slana;
    }
    public BigDecimal getSlawo() {
        return this.slawo;
    }
    
    public void setSlawo(BigDecimal slawo) {
        this.slawo = slawo;
    }
    public BigDecimal getNmabac() {
        return this.nmabac;
    }
    
    public void setNmabac(BigDecimal nmabac) {
        this.nmabac = nmabac;
    }
    public BigDecimal getNmaabl() {
        return this.nmaabl;
    }
    
    public void setNmaabl(BigDecimal nmaabl) {
        this.nmaabl = nmaabl;
    }
    public BigDecimal getNmades() {
        return this.nmades;
    }
    
    public void setNmades(BigDecimal nmades) {
        this.nmades = nmades;
    }
    public BigDecimal getNmaaba() {
        return this.nmaaba;
    }
    
    public void setNmaaba(BigDecimal nmaaba) {
        this.nmaaba = nmaaba;
    }
    public BigDecimal getNmaexc() {
        return this.nmaexc;
    }
    
    public void setNmaexc(BigDecimal nmaexc) {
        this.nmaexc = nmaexc;
    }
    public BigDecimal getNmadde() {
        return this.nmadde;
    }
    
    public void setNmadde(BigDecimal nmadde) {
        this.nmadde = nmadde;
    }
    public BigDecimal getNmadex() {
        return this.nmadex;
    }
    
    public void setNmadex(BigDecimal nmadex) {
        this.nmadex = nmadex;
    }
    public BigDecimal getNmana() {
        return this.nmana;
    }
    
    public void setNmana(BigDecimal nmana) {
        this.nmana = nmana;
    }
    public BigDecimal getNmawo() {
        return this.nmawo;
    }
    
    public void setNmawo(BigDecimal nmawo) {
        this.nmawo = nmawo;
    }
    public Integer getDiexna() {
        return this.diexna;
    }
    
    public void setDiexna(Integer diexna) {
        this.diexna = diexna;
    }
    public Integer getUltpro() {
        return this.ultpro;
    }
    
    public void setUltpro(Integer ultpro) {
        this.ultpro = ultpro;
    }




}


