package com.ciessa.museum.model.legacy;
// Generated Jan 28, 2019 1:33:59 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Tap014 generated by hbm2java
 */
public class Tap014  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer dmbk;
     private Integer dmtyp;
     private Long dmacct;
     private Integer dmtodf;
     private Integer dodate;
     private Integer dotie;
     private Integer dodatc;
     private Integer doindx;
     private BigDecimal doavar;
     private String doacb;
     private String doyrb;
     private String docapc;
     private String dooffa;
     private BigDecimal dooint;
     private Integer dorvtm;
     private Integer dorvld;
     private Integer doamdt;
     private Integer dolamd;
     private Integer doamnd;
     private Integer doamnx;
     private Long doaamt;
     private String doawvi;
     private String dobits;
     private BigDecimal docbal;
     private Integer dolrdt;
     private BigDecimal dotacc;
     private BigDecimal dopacc;
     private BigDecimal doyacc;
     private BigDecimal domacc;
     private Integer doaccr;
     private Integer doacc5;
     private BigDecimal dotipd;
     private BigDecimal dopipd;
     private BigDecimal doyipd;
     private BigDecimal doaggi;
     private BigDecimal domxbl;
     private BigDecimal dohbal;
     private BigDecimal doipdy;
     private BigDecimal dotacw;
     private BigDecimal dopacw;
     private BigDecimal doyacw;
     private BigDecimal domacw;
     private BigDecimal docpin;
     private BigDecimal docppv;
     private BigDecimal docpmt;
     private BigDecimal docpyt;
     private Integer docpln;
     private BigDecimal dobpbl;
     private Integer dobpdt;
     private BigDecimal dobprt;
     private String dopwvr;
     private Long dopamt;
     private BigDecimal doaggp;
     private BigDecimal domaxl;
     private BigDecimal dowkrt;
     private String copid;
     private Integer ddingr;
     private Integer dmingr;
     private Integer dyingr;
     private String cautid;
     private Integer ddauto;
     private Integer dmauto;
     private Integer dyauto;
     private String xstatu;
     private String xstaut;
     private String xliqin;
     private String xalta;
     private String xvenci;
     private String xsegur;
     private String xcomis;
     private Long dolima;
     private Long dolido;

    public Tap014() {
    }

	
    public Tap014(String pkid) {
        this.pkid = pkid;
    }
    public Tap014(String pkid, String member, Integer dmbk, Integer dmtyp, Long dmacct, Integer dmtodf, Integer dodate, Integer dotie, Integer dodatc, Integer doindx, BigDecimal doavar, String doacb, String doyrb, String docapc, String dooffa, BigDecimal dooint, Integer dorvtm, Integer dorvld, Integer doamdt, Integer dolamd, Integer doamnd, Integer doamnx, Long doaamt, String doawvi, String dobits, BigDecimal docbal, Integer dolrdt, BigDecimal dotacc, BigDecimal dopacc, BigDecimal doyacc, BigDecimal domacc, Integer doaccr, Integer doacc5, BigDecimal dotipd, BigDecimal dopipd, BigDecimal doyipd, BigDecimal doaggi, BigDecimal domxbl, BigDecimal dohbal, BigDecimal doipdy, BigDecimal dotacw, BigDecimal dopacw, BigDecimal doyacw, BigDecimal domacw, BigDecimal docpin, BigDecimal docppv, BigDecimal docpmt, BigDecimal docpyt, Integer docpln, BigDecimal dobpbl, Integer dobpdt, BigDecimal dobprt, String dopwvr, Long dopamt, BigDecimal doaggp, BigDecimal domaxl, BigDecimal dowkrt, String copid, Integer ddingr, Integer dmingr, Integer dyingr, String cautid, Integer ddauto, Integer dmauto, Integer dyauto, String xstatu, String xstaut, String xliqin, String xalta, String xvenci, String xsegur, String xcomis, Long dolima, Long dolido) {
       this.pkid = pkid;
       this.member = member;
       this.dmbk = dmbk;
       this.dmtyp = dmtyp;
       this.dmacct = dmacct;
       this.dmtodf = dmtodf;
       this.dodate = dodate;
       this.dotie = dotie;
       this.dodatc = dodatc;
       this.doindx = doindx;
       this.doavar = doavar;
       this.doacb = doacb;
       this.doyrb = doyrb;
       this.docapc = docapc;
       this.dooffa = dooffa;
       this.dooint = dooint;
       this.dorvtm = dorvtm;
       this.dorvld = dorvld;
       this.doamdt = doamdt;
       this.dolamd = dolamd;
       this.doamnd = doamnd;
       this.doamnx = doamnx;
       this.doaamt = doaamt;
       this.doawvi = doawvi;
       this.dobits = dobits;
       this.docbal = docbal;
       this.dolrdt = dolrdt;
       this.dotacc = dotacc;
       this.dopacc = dopacc;
       this.doyacc = doyacc;
       this.domacc = domacc;
       this.doaccr = doaccr;
       this.doacc5 = doacc5;
       this.dotipd = dotipd;
       this.dopipd = dopipd;
       this.doyipd = doyipd;
       this.doaggi = doaggi;
       this.domxbl = domxbl;
       this.dohbal = dohbal;
       this.doipdy = doipdy;
       this.dotacw = dotacw;
       this.dopacw = dopacw;
       this.doyacw = doyacw;
       this.domacw = domacw;
       this.docpin = docpin;
       this.docppv = docppv;
       this.docpmt = docpmt;
       this.docpyt = docpyt;
       this.docpln = docpln;
       this.dobpbl = dobpbl;
       this.dobpdt = dobpdt;
       this.dobprt = dobprt;
       this.dopwvr = dopwvr;
       this.dopamt = dopamt;
       this.doaggp = doaggp;
       this.domaxl = domaxl;
       this.dowkrt = dowkrt;
       this.copid = copid;
       this.ddingr = ddingr;
       this.dmingr = dmingr;
       this.dyingr = dyingr;
       this.cautid = cautid;
       this.ddauto = ddauto;
       this.dmauto = dmauto;
       this.dyauto = dyauto;
       this.xstatu = xstatu;
       this.xstaut = xstaut;
       this.xliqin = xliqin;
       this.xalta = xalta;
       this.xvenci = xvenci;
       this.xsegur = xsegur;
       this.xcomis = xcomis;
       this.dolima = dolima;
       this.dolido = dolido;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getDmbk() {
        return this.dmbk;
    }
    
    public void setDmbk(Integer dmbk) {
        this.dmbk = dmbk;
    }
    public Integer getDmtyp() {
        return this.dmtyp;
    }
    
    public void setDmtyp(Integer dmtyp) {
        this.dmtyp = dmtyp;
    }
    public Long getDmacct() {
        return this.dmacct;
    }
    
    public void setDmacct(Long dmacct) {
        this.dmacct = dmacct;
    }
    public Integer getDmtodf() {
        return this.dmtodf;
    }
    
    public void setDmtodf(Integer dmtodf) {
        this.dmtodf = dmtodf;
    }
    public Integer getDodate() {
        return this.dodate;
    }
    
    public void setDodate(Integer dodate) {
        this.dodate = dodate;
    }
    public Integer getDotie() {
        return this.dotie;
    }
    
    public void setDotie(Integer dotie) {
        this.dotie = dotie;
    }
    public Integer getDodatc() {
        return this.dodatc;
    }
    
    public void setDodatc(Integer dodatc) {
        this.dodatc = dodatc;
    }
    public Integer getDoindx() {
        return this.doindx;
    }
    
    public void setDoindx(Integer doindx) {
        this.doindx = doindx;
    }
    public BigDecimal getDoavar() {
        return this.doavar;
    }
    
    public void setDoavar(BigDecimal doavar) {
        this.doavar = doavar;
    }
    public String getDoacb() {
        return this.doacb;
    }
    
    public void setDoacb(String doacb) {
        this.doacb = doacb;
    }
    public String getDoyrb() {
        return this.doyrb;
    }
    
    public void setDoyrb(String doyrb) {
        this.doyrb = doyrb;
    }
    public String getDocapc() {
        return this.docapc;
    }
    
    public void setDocapc(String docapc) {
        this.docapc = docapc;
    }
    public String getDooffa() {
        return this.dooffa;
    }
    
    public void setDooffa(String dooffa) {
        this.dooffa = dooffa;
    }
    public BigDecimal getDooint() {
        return this.dooint;
    }
    
    public void setDooint(BigDecimal dooint) {
        this.dooint = dooint;
    }
    public Integer getDorvtm() {
        return this.dorvtm;
    }
    
    public void setDorvtm(Integer dorvtm) {
        this.dorvtm = dorvtm;
    }
    public Integer getDorvld() {
        return this.dorvld;
    }
    
    public void setDorvld(Integer dorvld) {
        this.dorvld = dorvld;
    }
    public Integer getDoamdt() {
        return this.doamdt;
    }
    
    public void setDoamdt(Integer doamdt) {
        this.doamdt = doamdt;
    }
    public Integer getDolamd() {
        return this.dolamd;
    }
    
    public void setDolamd(Integer dolamd) {
        this.dolamd = dolamd;
    }
    public Integer getDoamnd() {
        return this.doamnd;
    }
    
    public void setDoamnd(Integer doamnd) {
        this.doamnd = doamnd;
    }
    public Integer getDoamnx() {
        return this.doamnx;
    }
    
    public void setDoamnx(Integer doamnx) {
        this.doamnx = doamnx;
    }
    public Long getDoaamt() {
        return this.doaamt;
    }
    
    public void setDoaamt(Long doaamt) {
        this.doaamt = doaamt;
    }
    public String getDoawvi() {
        return this.doawvi;
    }
    
    public void setDoawvi(String doawvi) {
        this.doawvi = doawvi;
    }
    public String getDobits() {
        return this.dobits;
    }
    
    public void setDobits(String dobits) {
        this.dobits = dobits;
    }
    public BigDecimal getDocbal() {
        return this.docbal;
    }
    
    public void setDocbal(BigDecimal docbal) {
        this.docbal = docbal;
    }
    public Integer getDolrdt() {
        return this.dolrdt;
    }
    
    public void setDolrdt(Integer dolrdt) {
        this.dolrdt = dolrdt;
    }
    public BigDecimal getDotacc() {
        return this.dotacc;
    }
    
    public void setDotacc(BigDecimal dotacc) {
        this.dotacc = dotacc;
    }
    public BigDecimal getDopacc() {
        return this.dopacc;
    }
    
    public void setDopacc(BigDecimal dopacc) {
        this.dopacc = dopacc;
    }
    public BigDecimal getDoyacc() {
        return this.doyacc;
    }
    
    public void setDoyacc(BigDecimal doyacc) {
        this.doyacc = doyacc;
    }
    public BigDecimal getDomacc() {
        return this.domacc;
    }
    
    public void setDomacc(BigDecimal domacc) {
        this.domacc = domacc;
    }
    public Integer getDoaccr() {
        return this.doaccr;
    }
    
    public void setDoaccr(Integer doaccr) {
        this.doaccr = doaccr;
    }
    public Integer getDoacc5() {
        return this.doacc5;
    }
    
    public void setDoacc5(Integer doacc5) {
        this.doacc5 = doacc5;
    }
    public BigDecimal getDotipd() {
        return this.dotipd;
    }
    
    public void setDotipd(BigDecimal dotipd) {
        this.dotipd = dotipd;
    }
    public BigDecimal getDopipd() {
        return this.dopipd;
    }
    
    public void setDopipd(BigDecimal dopipd) {
        this.dopipd = dopipd;
    }
    public BigDecimal getDoyipd() {
        return this.doyipd;
    }
    
    public void setDoyipd(BigDecimal doyipd) {
        this.doyipd = doyipd;
    }
    public BigDecimal getDoaggi() {
        return this.doaggi;
    }
    
    public void setDoaggi(BigDecimal doaggi) {
        this.doaggi = doaggi;
    }
    public BigDecimal getDomxbl() {
        return this.domxbl;
    }
    
    public void setDomxbl(BigDecimal domxbl) {
        this.domxbl = domxbl;
    }
    public BigDecimal getDohbal() {
        return this.dohbal;
    }
    
    public void setDohbal(BigDecimal dohbal) {
        this.dohbal = dohbal;
    }
    public BigDecimal getDoipdy() {
        return this.doipdy;
    }
    
    public void setDoipdy(BigDecimal doipdy) {
        this.doipdy = doipdy;
    }
    public BigDecimal getDotacw() {
        return this.dotacw;
    }
    
    public void setDotacw(BigDecimal dotacw) {
        this.dotacw = dotacw;
    }
    public BigDecimal getDopacw() {
        return this.dopacw;
    }
    
    public void setDopacw(BigDecimal dopacw) {
        this.dopacw = dopacw;
    }
    public BigDecimal getDoyacw() {
        return this.doyacw;
    }
    
    public void setDoyacw(BigDecimal doyacw) {
        this.doyacw = doyacw;
    }
    public BigDecimal getDomacw() {
        return this.domacw;
    }
    
    public void setDomacw(BigDecimal domacw) {
        this.domacw = domacw;
    }
    public BigDecimal getDocpin() {
        return this.docpin;
    }
    
    public void setDocpin(BigDecimal docpin) {
        this.docpin = docpin;
    }
    public BigDecimal getDocppv() {
        return this.docppv;
    }
    
    public void setDocppv(BigDecimal docppv) {
        this.docppv = docppv;
    }
    public BigDecimal getDocpmt() {
        return this.docpmt;
    }
    
    public void setDocpmt(BigDecimal docpmt) {
        this.docpmt = docpmt;
    }
    public BigDecimal getDocpyt() {
        return this.docpyt;
    }
    
    public void setDocpyt(BigDecimal docpyt) {
        this.docpyt = docpyt;
    }
    public Integer getDocpln() {
        return this.docpln;
    }
    
    public void setDocpln(Integer docpln) {
        this.docpln = docpln;
    }
    public BigDecimal getDobpbl() {
        return this.dobpbl;
    }
    
    public void setDobpbl(BigDecimal dobpbl) {
        this.dobpbl = dobpbl;
    }
    public Integer getDobpdt() {
        return this.dobpdt;
    }
    
    public void setDobpdt(Integer dobpdt) {
        this.dobpdt = dobpdt;
    }
    public BigDecimal getDobprt() {
        return this.dobprt;
    }
    
    public void setDobprt(BigDecimal dobprt) {
        this.dobprt = dobprt;
    }
    public String getDopwvr() {
        return this.dopwvr;
    }
    
    public void setDopwvr(String dopwvr) {
        this.dopwvr = dopwvr;
    }
    public Long getDopamt() {
        return this.dopamt;
    }
    
    public void setDopamt(Long dopamt) {
        this.dopamt = dopamt;
    }
    public BigDecimal getDoaggp() {
        return this.doaggp;
    }
    
    public void setDoaggp(BigDecimal doaggp) {
        this.doaggp = doaggp;
    }
    public BigDecimal getDomaxl() {
        return this.domaxl;
    }
    
    public void setDomaxl(BigDecimal domaxl) {
        this.domaxl = domaxl;
    }
    public BigDecimal getDowkrt() {
        return this.dowkrt;
    }
    
    public void setDowkrt(BigDecimal dowkrt) {
        this.dowkrt = dowkrt;
    }
    public String getCopid() {
        return this.copid;
    }
    
    public void setCopid(String copid) {
        this.copid = copid;
    }
    public Integer getDdingr() {
        return this.ddingr;
    }
    
    public void setDdingr(Integer ddingr) {
        this.ddingr = ddingr;
    }
    public Integer getDmingr() {
        return this.dmingr;
    }
    
    public void setDmingr(Integer dmingr) {
        this.dmingr = dmingr;
    }
    public Integer getDyingr() {
        return this.dyingr;
    }
    
    public void setDyingr(Integer dyingr) {
        this.dyingr = dyingr;
    }
    public String getCautid() {
        return this.cautid;
    }
    
    public void setCautid(String cautid) {
        this.cautid = cautid;
    }
    public Integer getDdauto() {
        return this.ddauto;
    }
    
    public void setDdauto(Integer ddauto) {
        this.ddauto = ddauto;
    }
    public Integer getDmauto() {
        return this.dmauto;
    }
    
    public void setDmauto(Integer dmauto) {
        this.dmauto = dmauto;
    }
    public Integer getDyauto() {
        return this.dyauto;
    }
    
    public void setDyauto(Integer dyauto) {
        this.dyauto = dyauto;
    }
    public String getXstatu() {
        return this.xstatu;
    }
    
    public void setXstatu(String xstatu) {
        this.xstatu = xstatu;
    }
    public String getXstaut() {
        return this.xstaut;
    }
    
    public void setXstaut(String xstaut) {
        this.xstaut = xstaut;
    }
    public String getXliqin() {
        return this.xliqin;
    }
    
    public void setXliqin(String xliqin) {
        this.xliqin = xliqin;
    }
    public String getXalta() {
        return this.xalta;
    }
    
    public void setXalta(String xalta) {
        this.xalta = xalta;
    }
    public String getXvenci() {
        return this.xvenci;
    }
    
    public void setXvenci(String xvenci) {
        this.xvenci = xvenci;
    }
    public String getXsegur() {
        return this.xsegur;
    }
    
    public void setXsegur(String xsegur) {
        this.xsegur = xsegur;
    }
    public String getXcomis() {
        return this.xcomis;
    }
    
    public void setXcomis(String xcomis) {
        this.xcomis = xcomis;
    }
    public Long getDolima() {
        return this.dolima;
    }
    
    public void setDolima(Long dolima) {
        this.dolima = dolima;
    }
    public Long getDolido() {
        return this.dolido;
    }
    
    public void setDolido(Long dolido) {
        this.dolido = dolido;
    }




}


