package com.ciessa.museum.model.legacy;
// Generated Dec 8, 2018 1:27:28 AM by Hibernate Tools 3.2.2.GA



/**
 * Tap001 generated by hbm2java
 */
public class Tap001  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String key;
     private String data;

    public Tap001() {
    }

	
    public Tap001(String pkid) {
        this.pkid = pkid;
    }
    public Tap001(String pkid, String member, String key, String data) {
       this.pkid = pkid;
       this.member = member;
       this.key = key;
       this.data = data;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }




}


