package com.ciessa.museum.model.legacy;
// Generated Sep 10, 2018 9:32:23 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Tap002 generated by hbm2java
 */
public class Tap002  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer dmbk;
     private Integer dmtyp;
     private Long dmacct;
     private String dmtitl;
     private Integer dmctl;
     private String dmshrt;
     private String dmnow;
     private String dmtafg;
     private String dmcorr;
     private String dmpub;
     private String dmgovt;
     private String dmsec;
     private String dmpers;
     private String dmemp;
     private Integer dmbrch;
     private Integer dmtype;
     private Integer dmdopn;
     private String dmoff;
     private String dmlp;
     private String dmmail;
     private String dmclov;
     private String dmnoac;
     private String dmrege;
     private String dmclst;
     private String dmrest;
     private Integer dmsig;
     private Integer dmsiga;
     private String dmspin;
     private Integer dmodl;
     private String dmhist;
     private String dmprvs;
     private String dmbffg;
     private Integer dmcodt;
     private Integer dmlmtn;
     private String dmstat;
     private String dmusr1;
     private String dmusr2;
     private BigDecimal dmcbal;
     private BigDecimal dmybal;
     private Integer dmcmcn;
     private BigDecimal dmlcyb;
     private Long dmhold;
     private Long dmcf1;
     private Long dmcf2;
     private Long dmcf3;
     private Long dmcf4;
     private Long dmcf5;
     private Long dmcf6;
     private Long dmcf7;
     private Long dmcf8;
     private Long dmcf9;
     private BigDecimal dmlnsf;
     private BigDecimal dmlsc;
     private String dmeft;
     private String dmbits;
     private String dmbit2;
     private Integer dmdla;
     private Integer dmdld;
     private BigDecimal dmald;
     private String dmactv;
     private Integer dmttrn;
     private Integer dmmwd;
     private BigDecimal dmnsfa;
     private Integer dmcktd;
     private BigDecimal dmdrt;
     private BigDecimal dmdrtl;
     private Integer dmdrti;
     private BigDecimal dmcrt;
     private BigDecimal dmcrtl;
     private Integer dmcrti;
     private BigDecimal dmexsc;
     private BigDecimal dmnsff;
     private BigDecimal dmccam;
     private BigDecimal dmsofd;
     private BigDecimal dmsofc;
     private Integer dmdtdy;
     private Integer dmctdy;
     private Integer dmfrst;
     private Integer dmfstt;
     private Integer dmlast;
     private String dmstct;
     private Integer dmstcp;
     private String dmstcd;
     private Integer dmstfr;
     private Integer dmstsp;
     private Integer dmstdt;
     private BigDecimal dmpbal;
     private BigDecimal dmcra;
     private BigDecimal dmdra;
     private Integer dmcri;
     private Integer dmdri;
     private Integer dmencc;
     private Integer dmencd;
     private BigDecimal dmscst;
     private BigDecimal dmintc;
     private BigDecimal dmints;
     private BigDecimal dmintp;
     private BigDecimal dminws;
     private Integer dmdlst;
     private String dmefff;
     private String dmscty;
     private Integer dmsccd;
     private String dmscpr;
     private Integer dmscfr;
     private Integer dmscsp;
     private Integer dmscnx;
     private Integer dmscri;
     private Integer dmsdri;
     private Integer dmldi;
     private Integer dmfdi1;
     private Integer dmfdi2;
     private Integer dmfdi3;
     private Integer dmfdi4;
     private BigDecimal dmsoft;
     private Long dmaggb;
     private Long dmagcb;
     private Integer dmaggd;
     private Long dmmbal;
     private Integer dmmbld;
     private Integer dmatm;
     private Integer dmatmc;
     private Integer dmnsf;
     private Integer dmscod;
     private BigDecimal dmsc1a;
     private Integer dmsc1i;
     private BigDecimal dmsc2a;
     private Integer dmsc2i;
     private BigDecimal dmsc3a;
     private Integer dmsc3i;
     private BigDecimal dmsc4a;
     private Integer dmsc4i;
     private BigDecimal dmsc5a;
     private Integer dmsc5i;
     private BigDecimal dmsc6a;
     private Integer dmsc6i;
     private BigDecimal dmsc7a;
     private Integer dmsc7i;
     private BigDecimal dmsc8a;
     private Integer dmsc8i;
     private BigDecimal dmsc9a;
     private Integer dmsc9i;
     private Long dmrela;
     private Integer dmscpt;
     private Integer dmscls;
     private BigDecimal dmscpb;
     private Integer dmlipd;
     private String dmidsp;
     private Integer dmtfap;
     private Long dmtfac;
     private Integer dmdint;
     private String dmwhfg;
     private BigDecimal dmintr;
     private Integer dmlrdt;
     private BigDecimal dmtacc;
     private BigDecimal dmpacc;
     private BigDecimal dmyacc;
     private BigDecimal dmmacc;
     private Integer dmaccr;
     private Integer dmacc5;
     private BigDecimal dmtipd;
     private BigDecimal dmpipd;
     private BigDecimal dmyipd;
     private BigDecimal dmwhty;
     private BigDecimal dmiada;
     private BigDecimal dmiapa;
     private BigDecimal dmaggi;
     private Integer dmagid;
     private Long dmmbli;
     private BigDecimal dmipdy;
     private BigDecimal dmwhly;
     private Integer dmonpp;
     private Integer dmonrp;
     private Integer dmonpw;
     private Integer dmonrw;
     private Long dmccac;
     private Integer dmccin;
     private String dmccfg;
     private Integer dmoddt;
     private Integer dmoddy;
     private BigDecimal dmodiy;
     private Integer dmodly;
     private Integer dmoddp;
     private Integer dmoldy;
     private Integer dmolyd;
     private Integer dmamtn;
     private String dmiovf;
     private String dmiova;
     private Long dmiodl;
     private Integer dmiodd;
     private BigDecimal dmiodc;
     private BigDecimal dmbhbl;
     private Integer dmbhdt;
     private Integer dmbhft;
     private BigDecimal dmbcpn;
     private Long dmmtda;
     private Long dmmtdc;
     private Long dmytda;
     private Long dmytdc;
     private Integer dmmtdd;
     private Integer dmytdd;
     private Long dmlyav;
     private BigDecimal dmsctm;
     private Integer dmmdri;
     private Integer dmmcri;
     private Integer dmmcrd;
     private Integer dmmnsf;
     private Integer dmmnsp;
     private Integer dmmodm;
     private Integer dmkmo;
     private Integer dmkite;
     private Integer dmnsfy;
     private Integer dmnsfp;
     private Integer dmnsfl;
     private BigDecimal dmpsbl;
     private BigDecimal dmpscr;
     private BigDecimal dmpsdr;
     private Integer dmpsci;
     private Integer dmpsdi;
     private BigDecimal dmpssc;
     private BigDecimal dmpsoc;
     private BigDecimal dmpsin;
     private BigDecimal dmpsip;
     private BigDecimal dmpsiw;
     private Integer dmpsls;
     private Integer dmpslt;
     private Integer dmpsft;
     private BigDecimal dmirte;
     private String dmbkcl;
     private BigDecimal dmiavg;
     private Integer dmiday;
     private BigDecimal dmipd1;
     private BigDecimal dmipd2;
     private BigDecimal dmipd3;
     private BigDecimal dmipd4;
     private BigDecimal dmscac;
     private BigDecimal dmscav;
     private Integer dmscdy;
     private BigDecimal dmscbl;
     private Integer dmscpd;
     private Integer dmscpc;
     private Integer dmscli;
     private Integer dmsf1;
     private Integer dmsf2;
     private Integer dmsf3;
     private Integer dmsf4;
     private BigDecimal dmscsf;
     private Integer dmscnf;
     private Integer dmscof;
     private Integer dmscat;
     private Long dmscmb;
     private BigDecimal dmscas;
     private BigDecimal dmscwv;
     private Long dmscrb;
     private Integer dmscah;
     private BigDecimal dmsp1a;
     private Integer dmsp1i;
     private BigDecimal dmsp2a;
     private Integer dmsp2i;
     private BigDecimal dmsp3a;
     private Integer dmsp3i;
     private BigDecimal dmsp4a;
     private Integer dmsp4i;
     private BigDecimal dmsp5a;
     private Integer dmsp5i;
     private BigDecimal dmsp6a;
     private Integer dmsp6i;
     private BigDecimal dmsp7a;
     private Integer dmsp7i;
     private BigDecimal dmsp8a;
     private Integer dmsp8i;
     private BigDecimal dmsp9a;
     private Integer dmsp9i;
     private BigDecimal dmcpin;
     private BigDecimal dmcppv;
     private BigDecimal dmcpmt;
     private BigDecimal dmcpyt;
     private Integer dmcpln;
     private BigDecimal dmcprt;
     private Integer dmcapl;
     private Integer dmcapf;
     private String dmadex;
     private BigDecimal dmadda;
     private BigDecimal dmaddw;
     private BigDecimal dmadde;
     private BigDecimal dmadta;
     private BigDecimal dmadtw;
     private BigDecimal dmadte;
     private BigDecimal dmadtc;
     private BigDecimal dmadas;
     private BigDecimal dmadws;
     private BigDecimal dmmipd;
     private BigDecimal dmwhth;
     private Integer dmntdt;
     private String dmntrq;
     private BigDecimal dmopdp;
     private String dmslpt;
     private BigDecimal dmwhpc;
     private BigDecimal dmwhtm;
     private BigDecimal dmtxex;

    public Tap002() {
    }

	
    public Tap002(String pkid) {
        this.pkid = pkid;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getDmbk() {
        return this.dmbk;
    }
    
    public void setDmbk(Integer dmbk) {
        this.dmbk = dmbk;
    }
    public Integer getDmtyp() {
        return this.dmtyp;
    }
    
    public void setDmtyp(Integer dmtyp) {
        this.dmtyp = dmtyp;
    }
    public Long getDmacct() {
        return this.dmacct;
    }
    
    public void setDmacct(Long dmacct) {
        this.dmacct = dmacct;
    }
    public String getDmtitl() {
        return this.dmtitl;
    }
    
    public void setDmtitl(String dmtitl) {
        this.dmtitl = dmtitl;
    }
    public Integer getDmctl() {
        return this.dmctl;
    }
    
    public void setDmctl(Integer dmctl) {
        this.dmctl = dmctl;
    }
    public String getDmshrt() {
        return this.dmshrt;
    }
    
    public void setDmshrt(String dmshrt) {
        this.dmshrt = dmshrt;
    }
    public String getDmnow() {
        return this.dmnow;
    }
    
    public void setDmnow(String dmnow) {
        this.dmnow = dmnow;
    }
    public String getDmtafg() {
        return this.dmtafg;
    }
    
    public void setDmtafg(String dmtafg) {
        this.dmtafg = dmtafg;
    }
    public String getDmcorr() {
        return this.dmcorr;
    }
    
    public void setDmcorr(String dmcorr) {
        this.dmcorr = dmcorr;
    }
    public String getDmpub() {
        return this.dmpub;
    }
    
    public void setDmpub(String dmpub) {
        this.dmpub = dmpub;
    }
    public String getDmgovt() {
        return this.dmgovt;
    }
    
    public void setDmgovt(String dmgovt) {
        this.dmgovt = dmgovt;
    }
    public String getDmsec() {
        return this.dmsec;
    }
    
    public void setDmsec(String dmsec) {
        this.dmsec = dmsec;
    }
    public String getDmpers() {
        return this.dmpers;
    }
    
    public void setDmpers(String dmpers) {
        this.dmpers = dmpers;
    }
    public String getDmemp() {
        return this.dmemp;
    }
    
    public void setDmemp(String dmemp) {
        this.dmemp = dmemp;
    }
    public Integer getDmbrch() {
        return this.dmbrch;
    }
    
    public void setDmbrch(Integer dmbrch) {
        this.dmbrch = dmbrch;
    }
    public Integer getDmtype() {
        return this.dmtype;
    }
    
    public void setDmtype(Integer dmtype) {
        this.dmtype = dmtype;
    }
    public Integer getDmdopn() {
        return this.dmdopn;
    }
    
    public void setDmdopn(Integer dmdopn) {
        this.dmdopn = dmdopn;
    }
    public String getDmoff() {
        return this.dmoff;
    }
    
    public void setDmoff(String dmoff) {
        this.dmoff = dmoff;
    }
    public String getDmlp() {
        return this.dmlp;
    }
    
    public void setDmlp(String dmlp) {
        this.dmlp = dmlp;
    }
    public String getDmmail() {
        return this.dmmail;
    }
    
    public void setDmmail(String dmmail) {
        this.dmmail = dmmail;
    }
    public String getDmclov() {
        return this.dmclov;
    }
    
    public void setDmclov(String dmclov) {
        this.dmclov = dmclov;
    }
    public String getDmnoac() {
        return this.dmnoac;
    }
    
    public void setDmnoac(String dmnoac) {
        this.dmnoac = dmnoac;
    }
    public String getDmrege() {
        return this.dmrege;
    }
    
    public void setDmrege(String dmrege) {
        this.dmrege = dmrege;
    }
    public String getDmclst() {
        return this.dmclst;
    }
    
    public void setDmclst(String dmclst) {
        this.dmclst = dmclst;
    }
    public String getDmrest() {
        return this.dmrest;
    }
    
    public void setDmrest(String dmrest) {
        this.dmrest = dmrest;
    }
    public Integer getDmsig() {
        return this.dmsig;
    }
    
    public void setDmsig(Integer dmsig) {
        this.dmsig = dmsig;
    }
    public Integer getDmsiga() {
        return this.dmsiga;
    }
    
    public void setDmsiga(Integer dmsiga) {
        this.dmsiga = dmsiga;
    }
    public String getDmspin() {
        return this.dmspin;
    }
    
    public void setDmspin(String dmspin) {
        this.dmspin = dmspin;
    }
    public Integer getDmodl() {
        return this.dmodl;
    }
    
    public void setDmodl(Integer dmodl) {
        this.dmodl = dmodl;
    }
    public String getDmhist() {
        return this.dmhist;
    }
    
    public void setDmhist(String dmhist) {
        this.dmhist = dmhist;
    }
    public String getDmprvs() {
        return this.dmprvs;
    }
    
    public void setDmprvs(String dmprvs) {
        this.dmprvs = dmprvs;
    }
    public String getDmbffg() {
        return this.dmbffg;
    }
    
    public void setDmbffg(String dmbffg) {
        this.dmbffg = dmbffg;
    }
    public Integer getDmcodt() {
        return this.dmcodt;
    }
    
    public void setDmcodt(Integer dmcodt) {
        this.dmcodt = dmcodt;
    }
    public Integer getDmlmtn() {
        return this.dmlmtn;
    }
    
    public void setDmlmtn(Integer dmlmtn) {
        this.dmlmtn = dmlmtn;
    }
    public String getDmstat() {
        return this.dmstat;
    }
    
    public void setDmstat(String dmstat) {
        this.dmstat = dmstat;
    }
    public String getDmusr1() {
        return this.dmusr1;
    }
    
    public void setDmusr1(String dmusr1) {
        this.dmusr1 = dmusr1;
    }
    public String getDmusr2() {
        return this.dmusr2;
    }
    
    public void setDmusr2(String dmusr2) {
        this.dmusr2 = dmusr2;
    }
    public BigDecimal getDmcbal() {
        return this.dmcbal;
    }
    
    public void setDmcbal(BigDecimal dmcbal) {
        this.dmcbal = dmcbal;
    }
    public BigDecimal getDmybal() {
        return this.dmybal;
    }
    
    public void setDmybal(BigDecimal dmybal) {
        this.dmybal = dmybal;
    }
    public Integer getDmcmcn() {
        return this.dmcmcn;
    }
    
    public void setDmcmcn(Integer dmcmcn) {
        this.dmcmcn = dmcmcn;
    }
    public BigDecimal getDmlcyb() {
        return this.dmlcyb;
    }
    
    public void setDmlcyb(BigDecimal dmlcyb) {
        this.dmlcyb = dmlcyb;
    }
    public Long getDmhold() {
        return this.dmhold;
    }
    
    public void setDmhold(Long dmhold) {
        this.dmhold = dmhold;
    }
    public Long getDmcf1() {
        return this.dmcf1;
    }
    
    public void setDmcf1(Long dmcf1) {
        this.dmcf1 = dmcf1;
    }
    public Long getDmcf2() {
        return this.dmcf2;
    }
    
    public void setDmcf2(Long dmcf2) {
        this.dmcf2 = dmcf2;
    }
    public Long getDmcf3() {
        return this.dmcf3;
    }
    
    public void setDmcf3(Long dmcf3) {
        this.dmcf3 = dmcf3;
    }
    public Long getDmcf4() {
        return this.dmcf4;
    }
    
    public void setDmcf4(Long dmcf4) {
        this.dmcf4 = dmcf4;
    }
    public Long getDmcf5() {
        return this.dmcf5;
    }
    
    public void setDmcf5(Long dmcf5) {
        this.dmcf5 = dmcf5;
    }
    public Long getDmcf6() {
        return this.dmcf6;
    }
    
    public void setDmcf6(Long dmcf6) {
        this.dmcf6 = dmcf6;
    }
    public Long getDmcf7() {
        return this.dmcf7;
    }
    
    public void setDmcf7(Long dmcf7) {
        this.dmcf7 = dmcf7;
    }
    public Long getDmcf8() {
        return this.dmcf8;
    }
    
    public void setDmcf8(Long dmcf8) {
        this.dmcf8 = dmcf8;
    }
    public Long getDmcf9() {
        return this.dmcf9;
    }
    
    public void setDmcf9(Long dmcf9) {
        this.dmcf9 = dmcf9;
    }
    public BigDecimal getDmlnsf() {
        return this.dmlnsf;
    }
    
    public void setDmlnsf(BigDecimal dmlnsf) {
        this.dmlnsf = dmlnsf;
    }
    public BigDecimal getDmlsc() {
        return this.dmlsc;
    }
    
    public void setDmlsc(BigDecimal dmlsc) {
        this.dmlsc = dmlsc;
    }
    public String getDmeft() {
        return this.dmeft;
    }
    
    public void setDmeft(String dmeft) {
        this.dmeft = dmeft;
    }
    public String getDmbits() {
        return this.dmbits;
    }
    
    public void setDmbits(String dmbits) {
        this.dmbits = dmbits;
    }
    public String getDmbit2() {
        return this.dmbit2;
    }
    
    public void setDmbit2(String dmbit2) {
        this.dmbit2 = dmbit2;
    }
    public Integer getDmdla() {
        return this.dmdla;
    }
    
    public void setDmdla(Integer dmdla) {
        this.dmdla = dmdla;
    }
    public Integer getDmdld() {
        return this.dmdld;
    }
    
    public void setDmdld(Integer dmdld) {
        this.dmdld = dmdld;
    }
    public BigDecimal getDmald() {
        return this.dmald;
    }
    
    public void setDmald(BigDecimal dmald) {
        this.dmald = dmald;
    }
    public String getDmactv() {
        return this.dmactv;
    }
    
    public void setDmactv(String dmactv) {
        this.dmactv = dmactv;
    }
    public Integer getDmttrn() {
        return this.dmttrn;
    }
    
    public void setDmttrn(Integer dmttrn) {
        this.dmttrn = dmttrn;
    }
    public Integer getDmmwd() {
        return this.dmmwd;
    }
    
    public void setDmmwd(Integer dmmwd) {
        this.dmmwd = dmmwd;
    }
    public BigDecimal getDmnsfa() {
        return this.dmnsfa;
    }
    
    public void setDmnsfa(BigDecimal dmnsfa) {
        this.dmnsfa = dmnsfa;
    }
    public Integer getDmcktd() {
        return this.dmcktd;
    }
    
    public void setDmcktd(Integer dmcktd) {
        this.dmcktd = dmcktd;
    }
    public BigDecimal getDmdrt() {
        return this.dmdrt;
    }
    
    public void setDmdrt(BigDecimal dmdrt) {
        this.dmdrt = dmdrt;
    }
    public BigDecimal getDmdrtl() {
        return this.dmdrtl;
    }
    
    public void setDmdrtl(BigDecimal dmdrtl) {
        this.dmdrtl = dmdrtl;
    }
    public Integer getDmdrti() {
        return this.dmdrti;
    }
    
    public void setDmdrti(Integer dmdrti) {
        this.dmdrti = dmdrti;
    }
    public BigDecimal getDmcrt() {
        return this.dmcrt;
    }
    
    public void setDmcrt(BigDecimal dmcrt) {
        this.dmcrt = dmcrt;
    }
    public BigDecimal getDmcrtl() {
        return this.dmcrtl;
    }
    
    public void setDmcrtl(BigDecimal dmcrtl) {
        this.dmcrtl = dmcrtl;
    }
    public Integer getDmcrti() {
        return this.dmcrti;
    }
    
    public void setDmcrti(Integer dmcrti) {
        this.dmcrti = dmcrti;
    }
    public BigDecimal getDmexsc() {
        return this.dmexsc;
    }
    
    public void setDmexsc(BigDecimal dmexsc) {
        this.dmexsc = dmexsc;
    }
    public BigDecimal getDmnsff() {
        return this.dmnsff;
    }
    
    public void setDmnsff(BigDecimal dmnsff) {
        this.dmnsff = dmnsff;
    }
    public BigDecimal getDmccam() {
        return this.dmccam;
    }
    
    public void setDmccam(BigDecimal dmccam) {
        this.dmccam = dmccam;
    }
    public BigDecimal getDmsofd() {
        return this.dmsofd;
    }
    
    public void setDmsofd(BigDecimal dmsofd) {
        this.dmsofd = dmsofd;
    }
    public BigDecimal getDmsofc() {
        return this.dmsofc;
    }
    
    public void setDmsofc(BigDecimal dmsofc) {
        this.dmsofc = dmsofc;
    }
    public Integer getDmdtdy() {
        return this.dmdtdy;
    }
    
    public void setDmdtdy(Integer dmdtdy) {
        this.dmdtdy = dmdtdy;
    }
    public Integer getDmctdy() {
        return this.dmctdy;
    }
    
    public void setDmctdy(Integer dmctdy) {
        this.dmctdy = dmctdy;
    }
    public Integer getDmfrst() {
        return this.dmfrst;
    }
    
    public void setDmfrst(Integer dmfrst) {
        this.dmfrst = dmfrst;
    }
    public Integer getDmfstt() {
        return this.dmfstt;
    }
    
    public void setDmfstt(Integer dmfstt) {
        this.dmfstt = dmfstt;
    }
    public Integer getDmlast() {
        return this.dmlast;
    }
    
    public void setDmlast(Integer dmlast) {
        this.dmlast = dmlast;
    }
    public String getDmstct() {
        return this.dmstct;
    }
    
    public void setDmstct(String dmstct) {
        this.dmstct = dmstct;
    }
    public Integer getDmstcp() {
        return this.dmstcp;
    }
    
    public void setDmstcp(Integer dmstcp) {
        this.dmstcp = dmstcp;
    }
    public String getDmstcd() {
        return this.dmstcd;
    }
    
    public void setDmstcd(String dmstcd) {
        this.dmstcd = dmstcd;
    }
    public Integer getDmstfr() {
        return this.dmstfr;
    }
    
    public void setDmstfr(Integer dmstfr) {
        this.dmstfr = dmstfr;
    }
    public Integer getDmstsp() {
        return this.dmstsp;
    }
    
    public void setDmstsp(Integer dmstsp) {
        this.dmstsp = dmstsp;
    }
    public Integer getDmstdt() {
        return this.dmstdt;
    }
    
    public void setDmstdt(Integer dmstdt) {
        this.dmstdt = dmstdt;
    }
    public BigDecimal getDmpbal() {
        return this.dmpbal;
    }
    
    public void setDmpbal(BigDecimal dmpbal) {
        this.dmpbal = dmpbal;
    }
    public BigDecimal getDmcra() {
        return this.dmcra;
    }
    
    public void setDmcra(BigDecimal dmcra) {
        this.dmcra = dmcra;
    }
    public BigDecimal getDmdra() {
        return this.dmdra;
    }
    
    public void setDmdra(BigDecimal dmdra) {
        this.dmdra = dmdra;
    }
    public Integer getDmcri() {
        return this.dmcri;
    }
    
    public void setDmcri(Integer dmcri) {
        this.dmcri = dmcri;
    }
    public Integer getDmdri() {
        return this.dmdri;
    }
    
    public void setDmdri(Integer dmdri) {
        this.dmdri = dmdri;
    }
    public Integer getDmencc() {
        return this.dmencc;
    }
    
    public void setDmencc(Integer dmencc) {
        this.dmencc = dmencc;
    }
    public Integer getDmencd() {
        return this.dmencd;
    }
    
    public void setDmencd(Integer dmencd) {
        this.dmencd = dmencd;
    }
    public BigDecimal getDmscst() {
        return this.dmscst;
    }
    
    public void setDmscst(BigDecimal dmscst) {
        this.dmscst = dmscst;
    }
    public BigDecimal getDmintc() {
        return this.dmintc;
    }
    
    public void setDmintc(BigDecimal dmintc) {
        this.dmintc = dmintc;
    }
    public BigDecimal getDmints() {
        return this.dmints;
    }
    
    public void setDmints(BigDecimal dmints) {
        this.dmints = dmints;
    }
    public BigDecimal getDmintp() {
        return this.dmintp;
    }
    
    public void setDmintp(BigDecimal dmintp) {
        this.dmintp = dmintp;
    }
    public BigDecimal getDminws() {
        return this.dminws;
    }
    
    public void setDminws(BigDecimal dminws) {
        this.dminws = dminws;
    }
    public Integer getDmdlst() {
        return this.dmdlst;
    }
    
    public void setDmdlst(Integer dmdlst) {
        this.dmdlst = dmdlst;
    }
    public String getDmefff() {
        return this.dmefff;
    }
    
    public void setDmefff(String dmefff) {
        this.dmefff = dmefff;
    }
    public String getDmscty() {
        return this.dmscty;
    }
    
    public void setDmscty(String dmscty) {
        this.dmscty = dmscty;
    }
    public Integer getDmsccd() {
        return this.dmsccd;
    }
    
    public void setDmsccd(Integer dmsccd) {
        this.dmsccd = dmsccd;
    }
    public String getDmscpr() {
        return this.dmscpr;
    }
    
    public void setDmscpr(String dmscpr) {
        this.dmscpr = dmscpr;
    }
    public Integer getDmscfr() {
        return this.dmscfr;
    }
    
    public void setDmscfr(Integer dmscfr) {
        this.dmscfr = dmscfr;
    }
    public Integer getDmscsp() {
        return this.dmscsp;
    }
    
    public void setDmscsp(Integer dmscsp) {
        this.dmscsp = dmscsp;
    }
    public Integer getDmscnx() {
        return this.dmscnx;
    }
    
    public void setDmscnx(Integer dmscnx) {
        this.dmscnx = dmscnx;
    }
    public Integer getDmscri() {
        return this.dmscri;
    }
    
    public void setDmscri(Integer dmscri) {
        this.dmscri = dmscri;
    }
    public Integer getDmsdri() {
        return this.dmsdri;
    }
    
    public void setDmsdri(Integer dmsdri) {
        this.dmsdri = dmsdri;
    }
    public Integer getDmldi() {
        return this.dmldi;
    }
    
    public void setDmldi(Integer dmldi) {
        this.dmldi = dmldi;
    }
    public Integer getDmfdi1() {
        return this.dmfdi1;
    }
    
    public void setDmfdi1(Integer dmfdi1) {
        this.dmfdi1 = dmfdi1;
    }
    public Integer getDmfdi2() {
        return this.dmfdi2;
    }
    
    public void setDmfdi2(Integer dmfdi2) {
        this.dmfdi2 = dmfdi2;
    }
    public Integer getDmfdi3() {
        return this.dmfdi3;
    }
    
    public void setDmfdi3(Integer dmfdi3) {
        this.dmfdi3 = dmfdi3;
    }
    public Integer getDmfdi4() {
        return this.dmfdi4;
    }
    
    public void setDmfdi4(Integer dmfdi4) {
        this.dmfdi4 = dmfdi4;
    }
    public BigDecimal getDmsoft() {
        return this.dmsoft;
    }
    
    public void setDmsoft(BigDecimal dmsoft) {
        this.dmsoft = dmsoft;
    }
    public Long getDmaggb() {
        return this.dmaggb;
    }
    
    public void setDmaggb(Long dmaggb) {
        this.dmaggb = dmaggb;
    }
    public Long getDmagcb() {
        return this.dmagcb;
    }
    
    public void setDmagcb(Long dmagcb) {
        this.dmagcb = dmagcb;
    }
    public Integer getDmaggd() {
        return this.dmaggd;
    }
    
    public void setDmaggd(Integer dmaggd) {
        this.dmaggd = dmaggd;
    }
    public Long getDmmbal() {
        return this.dmmbal;
    }
    
    public void setDmmbal(Long dmmbal) {
        this.dmmbal = dmmbal;
    }
    public Integer getDmmbld() {
        return this.dmmbld;
    }
    
    public void setDmmbld(Integer dmmbld) {
        this.dmmbld = dmmbld;
    }
    public Integer getDmatm() {
        return this.dmatm;
    }
    
    public void setDmatm(Integer dmatm) {
        this.dmatm = dmatm;
    }
    public Integer getDmatmc() {
        return this.dmatmc;
    }
    
    public void setDmatmc(Integer dmatmc) {
        this.dmatmc = dmatmc;
    }
    public Integer getDmnsf() {
        return this.dmnsf;
    }
    
    public void setDmnsf(Integer dmnsf) {
        this.dmnsf = dmnsf;
    }
    public Integer getDmscod() {
        return this.dmscod;
    }
    
    public void setDmscod(Integer dmscod) {
        this.dmscod = dmscod;
    }
    public BigDecimal getDmsc1a() {
        return this.dmsc1a;
    }
    
    public void setDmsc1a(BigDecimal dmsc1a) {
        this.dmsc1a = dmsc1a;
    }
    public Integer getDmsc1i() {
        return this.dmsc1i;
    }
    
    public void setDmsc1i(Integer dmsc1i) {
        this.dmsc1i = dmsc1i;
    }
    public BigDecimal getDmsc2a() {
        return this.dmsc2a;
    }
    
    public void setDmsc2a(BigDecimal dmsc2a) {
        this.dmsc2a = dmsc2a;
    }
    public Integer getDmsc2i() {
        return this.dmsc2i;
    }
    
    public void setDmsc2i(Integer dmsc2i) {
        this.dmsc2i = dmsc2i;
    }
    public BigDecimal getDmsc3a() {
        return this.dmsc3a;
    }
    
    public void setDmsc3a(BigDecimal dmsc3a) {
        this.dmsc3a = dmsc3a;
    }
    public Integer getDmsc3i() {
        return this.dmsc3i;
    }
    
    public void setDmsc3i(Integer dmsc3i) {
        this.dmsc3i = dmsc3i;
    }
    public BigDecimal getDmsc4a() {
        return this.dmsc4a;
    }
    
    public void setDmsc4a(BigDecimal dmsc4a) {
        this.dmsc4a = dmsc4a;
    }
    public Integer getDmsc4i() {
        return this.dmsc4i;
    }
    
    public void setDmsc4i(Integer dmsc4i) {
        this.dmsc4i = dmsc4i;
    }
    public BigDecimal getDmsc5a() {
        return this.dmsc5a;
    }
    
    public void setDmsc5a(BigDecimal dmsc5a) {
        this.dmsc5a = dmsc5a;
    }
    public Integer getDmsc5i() {
        return this.dmsc5i;
    }
    
    public void setDmsc5i(Integer dmsc5i) {
        this.dmsc5i = dmsc5i;
    }
    public BigDecimal getDmsc6a() {
        return this.dmsc6a;
    }
    
    public void setDmsc6a(BigDecimal dmsc6a) {
        this.dmsc6a = dmsc6a;
    }
    public Integer getDmsc6i() {
        return this.dmsc6i;
    }
    
    public void setDmsc6i(Integer dmsc6i) {
        this.dmsc6i = dmsc6i;
    }
    public BigDecimal getDmsc7a() {
        return this.dmsc7a;
    }
    
    public void setDmsc7a(BigDecimal dmsc7a) {
        this.dmsc7a = dmsc7a;
    }
    public Integer getDmsc7i() {
        return this.dmsc7i;
    }
    
    public void setDmsc7i(Integer dmsc7i) {
        this.dmsc7i = dmsc7i;
    }
    public BigDecimal getDmsc8a() {
        return this.dmsc8a;
    }
    
    public void setDmsc8a(BigDecimal dmsc8a) {
        this.dmsc8a = dmsc8a;
    }
    public Integer getDmsc8i() {
        return this.dmsc8i;
    }
    
    public void setDmsc8i(Integer dmsc8i) {
        this.dmsc8i = dmsc8i;
    }
    public BigDecimal getDmsc9a() {
        return this.dmsc9a;
    }
    
    public void setDmsc9a(BigDecimal dmsc9a) {
        this.dmsc9a = dmsc9a;
    }
    public Integer getDmsc9i() {
        return this.dmsc9i;
    }
    
    public void setDmsc9i(Integer dmsc9i) {
        this.dmsc9i = dmsc9i;
    }
    public Long getDmrela() {
        return this.dmrela;
    }
    
    public void setDmrela(Long dmrela) {
        this.dmrela = dmrela;
    }
    public Integer getDmscpt() {
        return this.dmscpt;
    }
    
    public void setDmscpt(Integer dmscpt) {
        this.dmscpt = dmscpt;
    }
    public Integer getDmscls() {
        return this.dmscls;
    }
    
    public void setDmscls(Integer dmscls) {
        this.dmscls = dmscls;
    }
    public BigDecimal getDmscpb() {
        return this.dmscpb;
    }
    
    public void setDmscpb(BigDecimal dmscpb) {
        this.dmscpb = dmscpb;
    }
    public Integer getDmlipd() {
        return this.dmlipd;
    }
    
    public void setDmlipd(Integer dmlipd) {
        this.dmlipd = dmlipd;
    }
    public String getDmidsp() {
        return this.dmidsp;
    }
    
    public void setDmidsp(String dmidsp) {
        this.dmidsp = dmidsp;
    }
    public Integer getDmtfap() {
        return this.dmtfap;
    }
    
    public void setDmtfap(Integer dmtfap) {
        this.dmtfap = dmtfap;
    }
    public Long getDmtfac() {
        return this.dmtfac;
    }
    
    public void setDmtfac(Long dmtfac) {
        this.dmtfac = dmtfac;
    }
    public Integer getDmdint() {
        return this.dmdint;
    }
    
    public void setDmdint(Integer dmdint) {
        this.dmdint = dmdint;
    }
    public String getDmwhfg() {
        return this.dmwhfg;
    }
    
    public void setDmwhfg(String dmwhfg) {
        this.dmwhfg = dmwhfg;
    }
    public BigDecimal getDmintr() {
        return this.dmintr;
    }
    
    public void setDmintr(BigDecimal dmintr) {
        this.dmintr = dmintr;
    }
    public Integer getDmlrdt() {
        return this.dmlrdt;
    }
    
    public void setDmlrdt(Integer dmlrdt) {
        this.dmlrdt = dmlrdt;
    }
    public BigDecimal getDmtacc() {
        return this.dmtacc;
    }
    
    public void setDmtacc(BigDecimal dmtacc) {
        this.dmtacc = dmtacc;
    }
    public BigDecimal getDmpacc() {
        return this.dmpacc;
    }
    
    public void setDmpacc(BigDecimal dmpacc) {
        this.dmpacc = dmpacc;
    }
    public BigDecimal getDmyacc() {
        return this.dmyacc;
    }
    
    public void setDmyacc(BigDecimal dmyacc) {
        this.dmyacc = dmyacc;
    }
    public BigDecimal getDmmacc() {
        return this.dmmacc;
    }
    
    public void setDmmacc(BigDecimal dmmacc) {
        this.dmmacc = dmmacc;
    }
    public Integer getDmaccr() {
        return this.dmaccr;
    }
    
    public void setDmaccr(Integer dmaccr) {
        this.dmaccr = dmaccr;
    }
    public Integer getDmacc5() {
        return this.dmacc5;
    }
    
    public void setDmacc5(Integer dmacc5) {
        this.dmacc5 = dmacc5;
    }
    public BigDecimal getDmtipd() {
        return this.dmtipd;
    }
    
    public void setDmtipd(BigDecimal dmtipd) {
        this.dmtipd = dmtipd;
    }
    public BigDecimal getDmpipd() {
        return this.dmpipd;
    }
    
    public void setDmpipd(BigDecimal dmpipd) {
        this.dmpipd = dmpipd;
    }
    public BigDecimal getDmyipd() {
        return this.dmyipd;
    }
    
    public void setDmyipd(BigDecimal dmyipd) {
        this.dmyipd = dmyipd;
    }
    public BigDecimal getDmwhty() {
        return this.dmwhty;
    }
    
    public void setDmwhty(BigDecimal dmwhty) {
        this.dmwhty = dmwhty;
    }
    public BigDecimal getDmiada() {
        return this.dmiada;
    }
    
    public void setDmiada(BigDecimal dmiada) {
        this.dmiada = dmiada;
    }
    public BigDecimal getDmiapa() {
        return this.dmiapa;
    }
    
    public void setDmiapa(BigDecimal dmiapa) {
        this.dmiapa = dmiapa;
    }
    public BigDecimal getDmaggi() {
        return this.dmaggi;
    }
    
    public void setDmaggi(BigDecimal dmaggi) {
        this.dmaggi = dmaggi;
    }
    public Integer getDmagid() {
        return this.dmagid;
    }
    
    public void setDmagid(Integer dmagid) {
        this.dmagid = dmagid;
    }
    public Long getDmmbli() {
        return this.dmmbli;
    }
    
    public void setDmmbli(Long dmmbli) {
        this.dmmbli = dmmbli;
    }
    public BigDecimal getDmipdy() {
        return this.dmipdy;
    }
    
    public void setDmipdy(BigDecimal dmipdy) {
        this.dmipdy = dmipdy;
    }
    public BigDecimal getDmwhly() {
        return this.dmwhly;
    }
    
    public void setDmwhly(BigDecimal dmwhly) {
        this.dmwhly = dmwhly;
    }
    public Integer getDmonpp() {
        return this.dmonpp;
    }
    
    public void setDmonpp(Integer dmonpp) {
        this.dmonpp = dmonpp;
    }
    public Integer getDmonrp() {
        return this.dmonrp;
    }
    
    public void setDmonrp(Integer dmonrp) {
        this.dmonrp = dmonrp;
    }
    public Integer getDmonpw() {
        return this.dmonpw;
    }
    
    public void setDmonpw(Integer dmonpw) {
        this.dmonpw = dmonpw;
    }
    public Integer getDmonrw() {
        return this.dmonrw;
    }
    
    public void setDmonrw(Integer dmonrw) {
        this.dmonrw = dmonrw;
    }
    public Long getDmccac() {
        return this.dmccac;
    }
    
    public void setDmccac(Long dmccac) {
        this.dmccac = dmccac;
    }
    public Integer getDmccin() {
        return this.dmccin;
    }
    
    public void setDmccin(Integer dmccin) {
        this.dmccin = dmccin;
    }
    public String getDmccfg() {
        return this.dmccfg;
    }
    
    public void setDmccfg(String dmccfg) {
        this.dmccfg = dmccfg;
    }
    public Integer getDmoddt() {
        return this.dmoddt;
    }
    
    public void setDmoddt(Integer dmoddt) {
        this.dmoddt = dmoddt;
    }
    public Integer getDmoddy() {
        return this.dmoddy;
    }
    
    public void setDmoddy(Integer dmoddy) {
        this.dmoddy = dmoddy;
    }
    public BigDecimal getDmodiy() {
        return this.dmodiy;
    }
    
    public void setDmodiy(BigDecimal dmodiy) {
        this.dmodiy = dmodiy;
    }
    public Integer getDmodly() {
        return this.dmodly;
    }
    
    public void setDmodly(Integer dmodly) {
        this.dmodly = dmodly;
    }
    public Integer getDmoddp() {
        return this.dmoddp;
    }
    
    public void setDmoddp(Integer dmoddp) {
        this.dmoddp = dmoddp;
    }
    public Integer getDmoldy() {
        return this.dmoldy;
    }
    
    public void setDmoldy(Integer dmoldy) {
        this.dmoldy = dmoldy;
    }
    public Integer getDmolyd() {
        return this.dmolyd;
    }
    
    public void setDmolyd(Integer dmolyd) {
        this.dmolyd = dmolyd;
    }
    public Integer getDmamtn() {
        return this.dmamtn;
    }
    
    public void setDmamtn(Integer dmamtn) {
        this.dmamtn = dmamtn;
    }
    public String getDmiovf() {
        return this.dmiovf;
    }
    
    public void setDmiovf(String dmiovf) {
        this.dmiovf = dmiovf;
    }
    public String getDmiova() {
        return this.dmiova;
    }
    
    public void setDmiova(String dmiova) {
        this.dmiova = dmiova;
    }
    public Long getDmiodl() {
        return this.dmiodl;
    }
    
    public void setDmiodl(Long dmiodl) {
        this.dmiodl = dmiodl;
    }
    public Integer getDmiodd() {
        return this.dmiodd;
    }
    
    public void setDmiodd(Integer dmiodd) {
        this.dmiodd = dmiodd;
    }
    public BigDecimal getDmiodc() {
        return this.dmiodc;
    }
    
    public void setDmiodc(BigDecimal dmiodc) {
        this.dmiodc = dmiodc;
    }
    public BigDecimal getDmbhbl() {
        return this.dmbhbl;
    }
    
    public void setDmbhbl(BigDecimal dmbhbl) {
        this.dmbhbl = dmbhbl;
    }
    public Integer getDmbhdt() {
        return this.dmbhdt;
    }
    
    public void setDmbhdt(Integer dmbhdt) {
        this.dmbhdt = dmbhdt;
    }
    public Integer getDmbhft() {
        return this.dmbhft;
    }
    
    public void setDmbhft(Integer dmbhft) {
        this.dmbhft = dmbhft;
    }
    public BigDecimal getDmbcpn() {
        return this.dmbcpn;
    }
    
    public void setDmbcpn(BigDecimal dmbcpn) {
        this.dmbcpn = dmbcpn;
    }
    public Long getDmmtda() {
        return this.dmmtda;
    }
    
    public void setDmmtda(Long dmmtda) {
        this.dmmtda = dmmtda;
    }
    public Long getDmmtdc() {
        return this.dmmtdc;
    }
    
    public void setDmmtdc(Long dmmtdc) {
        this.dmmtdc = dmmtdc;
    }
    public Long getDmytda() {
        return this.dmytda;
    }
    
    public void setDmytda(Long dmytda) {
        this.dmytda = dmytda;
    }
    public Long getDmytdc() {
        return this.dmytdc;
    }
    
    public void setDmytdc(Long dmytdc) {
        this.dmytdc = dmytdc;
    }
    public Integer getDmmtdd() {
        return this.dmmtdd;
    }
    
    public void setDmmtdd(Integer dmmtdd) {
        this.dmmtdd = dmmtdd;
    }
    public Integer getDmytdd() {
        return this.dmytdd;
    }
    
    public void setDmytdd(Integer dmytdd) {
        this.dmytdd = dmytdd;
    }
    public Long getDmlyav() {
        return this.dmlyav;
    }
    
    public void setDmlyav(Long dmlyav) {
        this.dmlyav = dmlyav;
    }
    public BigDecimal getDmsctm() {
        return this.dmsctm;
    }
    
    public void setDmsctm(BigDecimal dmsctm) {
        this.dmsctm = dmsctm;
    }
    public Integer getDmmdri() {
        return this.dmmdri;
    }
    
    public void setDmmdri(Integer dmmdri) {
        this.dmmdri = dmmdri;
    }
    public Integer getDmmcri() {
        return this.dmmcri;
    }
    
    public void setDmmcri(Integer dmmcri) {
        this.dmmcri = dmmcri;
    }
    public Integer getDmmcrd() {
        return this.dmmcrd;
    }
    
    public void setDmmcrd(Integer dmmcrd) {
        this.dmmcrd = dmmcrd;
    }
    public Integer getDmmnsf() {
        return this.dmmnsf;
    }
    
    public void setDmmnsf(Integer dmmnsf) {
        this.dmmnsf = dmmnsf;
    }
    public Integer getDmmnsp() {
        return this.dmmnsp;
    }
    
    public void setDmmnsp(Integer dmmnsp) {
        this.dmmnsp = dmmnsp;
    }
    public Integer getDmmodm() {
        return this.dmmodm;
    }
    
    public void setDmmodm(Integer dmmodm) {
        this.dmmodm = dmmodm;
    }
    public Integer getDmkmo() {
        return this.dmkmo;
    }
    
    public void setDmkmo(Integer dmkmo) {
        this.dmkmo = dmkmo;
    }
    public Integer getDmkite() {
        return this.dmkite;
    }
    
    public void setDmkite(Integer dmkite) {
        this.dmkite = dmkite;
    }
    public Integer getDmnsfy() {
        return this.dmnsfy;
    }
    
    public void setDmnsfy(Integer dmnsfy) {
        this.dmnsfy = dmnsfy;
    }
    public Integer getDmnsfp() {
        return this.dmnsfp;
    }
    
    public void setDmnsfp(Integer dmnsfp) {
        this.dmnsfp = dmnsfp;
    }
    public Integer getDmnsfl() {
        return this.dmnsfl;
    }
    
    public void setDmnsfl(Integer dmnsfl) {
        this.dmnsfl = dmnsfl;
    }
    public BigDecimal getDmpsbl() {
        return this.dmpsbl;
    }
    
    public void setDmpsbl(BigDecimal dmpsbl) {
        this.dmpsbl = dmpsbl;
    }
    public BigDecimal getDmpscr() {
        return this.dmpscr;
    }
    
    public void setDmpscr(BigDecimal dmpscr) {
        this.dmpscr = dmpscr;
    }
    public BigDecimal getDmpsdr() {
        return this.dmpsdr;
    }
    
    public void setDmpsdr(BigDecimal dmpsdr) {
        this.dmpsdr = dmpsdr;
    }
    public Integer getDmpsci() {
        return this.dmpsci;
    }
    
    public void setDmpsci(Integer dmpsci) {
        this.dmpsci = dmpsci;
    }
    public Integer getDmpsdi() {
        return this.dmpsdi;
    }
    
    public void setDmpsdi(Integer dmpsdi) {
        this.dmpsdi = dmpsdi;
    }
    public BigDecimal getDmpssc() {
        return this.dmpssc;
    }
    
    public void setDmpssc(BigDecimal dmpssc) {
        this.dmpssc = dmpssc;
    }
    public BigDecimal getDmpsoc() {
        return this.dmpsoc;
    }
    
    public void setDmpsoc(BigDecimal dmpsoc) {
        this.dmpsoc = dmpsoc;
    }
    public BigDecimal getDmpsin() {
        return this.dmpsin;
    }
    
    public void setDmpsin(BigDecimal dmpsin) {
        this.dmpsin = dmpsin;
    }
    public BigDecimal getDmpsip() {
        return this.dmpsip;
    }
    
    public void setDmpsip(BigDecimal dmpsip) {
        this.dmpsip = dmpsip;
    }
    public BigDecimal getDmpsiw() {
        return this.dmpsiw;
    }
    
    public void setDmpsiw(BigDecimal dmpsiw) {
        this.dmpsiw = dmpsiw;
    }
    public Integer getDmpsls() {
        return this.dmpsls;
    }
    
    public void setDmpsls(Integer dmpsls) {
        this.dmpsls = dmpsls;
    }
    public Integer getDmpslt() {
        return this.dmpslt;
    }
    
    public void setDmpslt(Integer dmpslt) {
        this.dmpslt = dmpslt;
    }
    public Integer getDmpsft() {
        return this.dmpsft;
    }
    
    public void setDmpsft(Integer dmpsft) {
        this.dmpsft = dmpsft;
    }
    public BigDecimal getDmirte() {
        return this.dmirte;
    }
    
    public void setDmirte(BigDecimal dmirte) {
        this.dmirte = dmirte;
    }
    public String getDmbkcl() {
        return this.dmbkcl;
    }
    
    public void setDmbkcl(String dmbkcl) {
        this.dmbkcl = dmbkcl;
    }
    public BigDecimal getDmiavg() {
        return this.dmiavg;
    }
    
    public void setDmiavg(BigDecimal dmiavg) {
        this.dmiavg = dmiavg;
    }
    public Integer getDmiday() {
        return this.dmiday;
    }
    
    public void setDmiday(Integer dmiday) {
        this.dmiday = dmiday;
    }
    public BigDecimal getDmipd1() {
        return this.dmipd1;
    }
    
    public void setDmipd1(BigDecimal dmipd1) {
        this.dmipd1 = dmipd1;
    }
    public BigDecimal getDmipd2() {
        return this.dmipd2;
    }
    
    public void setDmipd2(BigDecimal dmipd2) {
        this.dmipd2 = dmipd2;
    }
    public BigDecimal getDmipd3() {
        return this.dmipd3;
    }
    
    public void setDmipd3(BigDecimal dmipd3) {
        this.dmipd3 = dmipd3;
    }
    public BigDecimal getDmipd4() {
        return this.dmipd4;
    }
    
    public void setDmipd4(BigDecimal dmipd4) {
        this.dmipd4 = dmipd4;
    }
    public BigDecimal getDmscac() {
        return this.dmscac;
    }
    
    public void setDmscac(BigDecimal dmscac) {
        this.dmscac = dmscac;
    }
    public BigDecimal getDmscav() {
        return this.dmscav;
    }
    
    public void setDmscav(BigDecimal dmscav) {
        this.dmscav = dmscav;
    }
    public Integer getDmscdy() {
        return this.dmscdy;
    }
    
    public void setDmscdy(Integer dmscdy) {
        this.dmscdy = dmscdy;
    }
    public BigDecimal getDmscbl() {
        return this.dmscbl;
    }
    
    public void setDmscbl(BigDecimal dmscbl) {
        this.dmscbl = dmscbl;
    }
    public Integer getDmscpd() {
        return this.dmscpd;
    }
    
    public void setDmscpd(Integer dmscpd) {
        this.dmscpd = dmscpd;
    }
    public Integer getDmscpc() {
        return this.dmscpc;
    }
    
    public void setDmscpc(Integer dmscpc) {
        this.dmscpc = dmscpc;
    }
    public Integer getDmscli() {
        return this.dmscli;
    }
    
    public void setDmscli(Integer dmscli) {
        this.dmscli = dmscli;
    }
    public Integer getDmsf1() {
        return this.dmsf1;
    }
    
    public void setDmsf1(Integer dmsf1) {
        this.dmsf1 = dmsf1;
    }
    public Integer getDmsf2() {
        return this.dmsf2;
    }
    
    public void setDmsf2(Integer dmsf2) {
        this.dmsf2 = dmsf2;
    }
    public Integer getDmsf3() {
        return this.dmsf3;
    }
    
    public void setDmsf3(Integer dmsf3) {
        this.dmsf3 = dmsf3;
    }
    public Integer getDmsf4() {
        return this.dmsf4;
    }
    
    public void setDmsf4(Integer dmsf4) {
        this.dmsf4 = dmsf4;
    }
    public BigDecimal getDmscsf() {
        return this.dmscsf;
    }
    
    public void setDmscsf(BigDecimal dmscsf) {
        this.dmscsf = dmscsf;
    }
    public Integer getDmscnf() {
        return this.dmscnf;
    }
    
    public void setDmscnf(Integer dmscnf) {
        this.dmscnf = dmscnf;
    }
    public Integer getDmscof() {
        return this.dmscof;
    }
    
    public void setDmscof(Integer dmscof) {
        this.dmscof = dmscof;
    }
    public Integer getDmscat() {
        return this.dmscat;
    }
    
    public void setDmscat(Integer dmscat) {
        this.dmscat = dmscat;
    }
    public Long getDmscmb() {
        return this.dmscmb;
    }
    
    public void setDmscmb(Long dmscmb) {
        this.dmscmb = dmscmb;
    }
    public BigDecimal getDmscas() {
        return this.dmscas;
    }
    
    public void setDmscas(BigDecimal dmscas) {
        this.dmscas = dmscas;
    }
    public BigDecimal getDmscwv() {
        return this.dmscwv;
    }
    
    public void setDmscwv(BigDecimal dmscwv) {
        this.dmscwv = dmscwv;
    }
    public Long getDmscrb() {
        return this.dmscrb;
    }
    
    public void setDmscrb(Long dmscrb) {
        this.dmscrb = dmscrb;
    }
    public Integer getDmscah() {
        return this.dmscah;
    }
    
    public void setDmscah(Integer dmscah) {
        this.dmscah = dmscah;
    }
    public BigDecimal getDmsp1a() {
        return this.dmsp1a;
    }
    
    public void setDmsp1a(BigDecimal dmsp1a) {
        this.dmsp1a = dmsp1a;
    }
    public Integer getDmsp1i() {
        return this.dmsp1i;
    }
    
    public void setDmsp1i(Integer dmsp1i) {
        this.dmsp1i = dmsp1i;
    }
    public BigDecimal getDmsp2a() {
        return this.dmsp2a;
    }
    
    public void setDmsp2a(BigDecimal dmsp2a) {
        this.dmsp2a = dmsp2a;
    }
    public Integer getDmsp2i() {
        return this.dmsp2i;
    }
    
    public void setDmsp2i(Integer dmsp2i) {
        this.dmsp2i = dmsp2i;
    }
    public BigDecimal getDmsp3a() {
        return this.dmsp3a;
    }
    
    public void setDmsp3a(BigDecimal dmsp3a) {
        this.dmsp3a = dmsp3a;
    }
    public Integer getDmsp3i() {
        return this.dmsp3i;
    }
    
    public void setDmsp3i(Integer dmsp3i) {
        this.dmsp3i = dmsp3i;
    }
    public BigDecimal getDmsp4a() {
        return this.dmsp4a;
    }
    
    public void setDmsp4a(BigDecimal dmsp4a) {
        this.dmsp4a = dmsp4a;
    }
    public Integer getDmsp4i() {
        return this.dmsp4i;
    }
    
    public void setDmsp4i(Integer dmsp4i) {
        this.dmsp4i = dmsp4i;
    }
    public BigDecimal getDmsp5a() {
        return this.dmsp5a;
    }
    
    public void setDmsp5a(BigDecimal dmsp5a) {
        this.dmsp5a = dmsp5a;
    }
    public Integer getDmsp5i() {
        return this.dmsp5i;
    }
    
    public void setDmsp5i(Integer dmsp5i) {
        this.dmsp5i = dmsp5i;
    }
    public BigDecimal getDmsp6a() {
        return this.dmsp6a;
    }
    
    public void setDmsp6a(BigDecimal dmsp6a) {
        this.dmsp6a = dmsp6a;
    }
    public Integer getDmsp6i() {
        return this.dmsp6i;
    }
    
    public void setDmsp6i(Integer dmsp6i) {
        this.dmsp6i = dmsp6i;
    }
    public BigDecimal getDmsp7a() {
        return this.dmsp7a;
    }
    
    public void setDmsp7a(BigDecimal dmsp7a) {
        this.dmsp7a = dmsp7a;
    }
    public Integer getDmsp7i() {
        return this.dmsp7i;
    }
    
    public void setDmsp7i(Integer dmsp7i) {
        this.dmsp7i = dmsp7i;
    }
    public BigDecimal getDmsp8a() {
        return this.dmsp8a;
    }
    
    public void setDmsp8a(BigDecimal dmsp8a) {
        this.dmsp8a = dmsp8a;
    }
    public Integer getDmsp8i() {
        return this.dmsp8i;
    }
    
    public void setDmsp8i(Integer dmsp8i) {
        this.dmsp8i = dmsp8i;
    }
    public BigDecimal getDmsp9a() {
        return this.dmsp9a;
    }
    
    public void setDmsp9a(BigDecimal dmsp9a) {
        this.dmsp9a = dmsp9a;
    }
    public Integer getDmsp9i() {
        return this.dmsp9i;
    }
    
    public void setDmsp9i(Integer dmsp9i) {
        this.dmsp9i = dmsp9i;
    }
    public BigDecimal getDmcpin() {
        return this.dmcpin;
    }
    
    public void setDmcpin(BigDecimal dmcpin) {
        this.dmcpin = dmcpin;
    }
    public BigDecimal getDmcppv() {
        return this.dmcppv;
    }
    
    public void setDmcppv(BigDecimal dmcppv) {
        this.dmcppv = dmcppv;
    }
    public BigDecimal getDmcpmt() {
        return this.dmcpmt;
    }
    
    public void setDmcpmt(BigDecimal dmcpmt) {
        this.dmcpmt = dmcpmt;
    }
    public BigDecimal getDmcpyt() {
        return this.dmcpyt;
    }
    
    public void setDmcpyt(BigDecimal dmcpyt) {
        this.dmcpyt = dmcpyt;
    }
    public Integer getDmcpln() {
        return this.dmcpln;
    }
    
    public void setDmcpln(Integer dmcpln) {
        this.dmcpln = dmcpln;
    }
    public BigDecimal getDmcprt() {
        return this.dmcprt;
    }
    
    public void setDmcprt(BigDecimal dmcprt) {
        this.dmcprt = dmcprt;
    }
    public Integer getDmcapl() {
        return this.dmcapl;
    }
    
    public void setDmcapl(Integer dmcapl) {
        this.dmcapl = dmcapl;
    }
    public Integer getDmcapf() {
        return this.dmcapf;
    }
    
    public void setDmcapf(Integer dmcapf) {
        this.dmcapf = dmcapf;
    }
    public String getDmadex() {
        return this.dmadex;
    }
    
    public void setDmadex(String dmadex) {
        this.dmadex = dmadex;
    }
    public BigDecimal getDmadda() {
        return this.dmadda;
    }
    
    public void setDmadda(BigDecimal dmadda) {
        this.dmadda = dmadda;
    }
    public BigDecimal getDmaddw() {
        return this.dmaddw;
    }
    
    public void setDmaddw(BigDecimal dmaddw) {
        this.dmaddw = dmaddw;
    }
    public BigDecimal getDmadde() {
        return this.dmadde;
    }
    
    public void setDmadde(BigDecimal dmadde) {
        this.dmadde = dmadde;
    }
    public BigDecimal getDmadta() {
        return this.dmadta;
    }
    
    public void setDmadta(BigDecimal dmadta) {
        this.dmadta = dmadta;
    }
    public BigDecimal getDmadtw() {
        return this.dmadtw;
    }
    
    public void setDmadtw(BigDecimal dmadtw) {
        this.dmadtw = dmadtw;
    }
    public BigDecimal getDmadte() {
        return this.dmadte;
    }
    
    public void setDmadte(BigDecimal dmadte) {
        this.dmadte = dmadte;
    }
    public BigDecimal getDmadtc() {
        return this.dmadtc;
    }
    
    public void setDmadtc(BigDecimal dmadtc) {
        this.dmadtc = dmadtc;
    }
    public BigDecimal getDmadas() {
        return this.dmadas;
    }
    
    public void setDmadas(BigDecimal dmadas) {
        this.dmadas = dmadas;
    }
    public BigDecimal getDmadws() {
        return this.dmadws;
    }
    
    public void setDmadws(BigDecimal dmadws) {
        this.dmadws = dmadws;
    }
    public BigDecimal getDmmipd() {
        return this.dmmipd;
    }
    
    public void setDmmipd(BigDecimal dmmipd) {
        this.dmmipd = dmmipd;
    }
    public BigDecimal getDmwhth() {
        return this.dmwhth;
    }
    
    public void setDmwhth(BigDecimal dmwhth) {
        this.dmwhth = dmwhth;
    }
    public Integer getDmntdt() {
        return this.dmntdt;
    }
    
    public void setDmntdt(Integer dmntdt) {
        this.dmntdt = dmntdt;
    }
    public String getDmntrq() {
        return this.dmntrq;
    }
    
    public void setDmntrq(String dmntrq) {
        this.dmntrq = dmntrq;
    }
    public BigDecimal getDmopdp() {
        return this.dmopdp;
    }
    
    public void setDmopdp(BigDecimal dmopdp) {
        this.dmopdp = dmopdp;
    }
    public String getDmslpt() {
        return this.dmslpt;
    }
    
    public void setDmslpt(String dmslpt) {
        this.dmslpt = dmslpt;
    }
    public BigDecimal getDmwhpc() {
        return this.dmwhpc;
    }
    
    public void setDmwhpc(BigDecimal dmwhpc) {
        this.dmwhpc = dmwhpc;
    }
    public BigDecimal getDmwhtm() {
        return this.dmwhtm;
    }
    
    public void setDmwhtm(BigDecimal dmwhtm) {
        this.dmwhtm = dmwhtm;
    }
    public BigDecimal getDmtxex() {
        return this.dmtxex;
    }
    
    public void setDmtxex(BigDecimal dmtxex) {
        this.dmtxex = dmtxex;
    }




}


