package com.ciessa.museum.model.legacy;
// Generated Mar 7, 2018 5:59:21 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * Tap902 generated by hbm2java
 */
public class Tap902 implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 7554839415906577566L;

	private String pkid;
	private String member;
	private Integer cbnk;
	private Integer crel;
	private Integer caplp;
	private Long Òctap;
	private Integer caplv;
	private Long Òctav;
	private BigDecimal ssalmn;
	private BigDecimal ssalmx;
	private String xmarc;

	public Tap902() {
	}

	public Tap902(String pkid) {
		this.pkid = pkid;
	}

	public Tap902(String pkid, String member, Integer cbnk, Integer crel, Integer caplp, Long Òctap, Integer caplv,
			Long Òctav, BigDecimal ssalmn, BigDecimal ssalmx, String xmarc) {
		this.pkid = pkid;
		this.member = member;
		this.cbnk = cbnk;
		this.crel = crel;
		this.caplp = caplp;
		this.Òctap = Òctap;
		this.caplv = caplv;
		this.Òctav = Òctav;
		this.ssalmn = ssalmn;
		this.ssalmx = ssalmx;
		this.xmarc = xmarc;
	}

	public String getPkid() {
		return this.pkid;
	}

	public void setPkid(String pkid) {
		this.pkid = pkid;
	}

	public String getMember() {
		return this.member;
	}

	public void setMember(String member) {
		this.member = member;
	}

	public Integer getCbnk() {
		return this.cbnk;
	}

	public void setCbnk(Integer cbnk) {
		this.cbnk = cbnk;
	}

	public Integer getCrel() {
		return this.crel;
	}

	public void setCrel(Integer crel) {
		this.crel = crel;
	}

	public Integer getCaplp() {
		return this.caplp;
	}

	public void setCaplp(Integer caplp) {
		this.caplp = caplp;
	}

	public Long get—ctap() {
		return this.Òctap;
	}

	public void set—ctap(Long Òctap) {
		this.Òctap = Òctap;
	}

	public Integer getCaplv() {
		return this.caplv;
	}

	public void setCaplv(Integer caplv) {
		this.caplv = caplv;
	}

	public Long get—ctav() {
		return this.Òctav;
	}

	public void set—ctav(Long Òctav) {
		this.Òctav = Òctav;
	}

	public BigDecimal getSsalmn() {
		return this.ssalmn;
	}

	public void setSsalmn(BigDecimal ssalmn) {
		this.ssalmn = ssalmn;
	}

	public BigDecimal getSsalmx() {
		return this.ssalmx;
	}

	public void setSsalmx(BigDecimal ssalmx) {
		this.ssalmx = ssalmx;
	}

	public String getXmarc() {
		return this.xmarc;
	}

	public void setXmarc(String xmarc) {
		this.xmarc = xmarc;
	}

}
