package com.ciessa.museum.model.legacy;
// Generated Sep 10, 2018 9:32:23 PM by Hibernate Tools 3.2.2.GA



/**
 * Tgpp632 generated by hbm2java
 */
public class Tgpp632  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer ceelem;
     private Integer ceintv;
     private Integer celudt;
     private Integer cetlup;
     private Integer ceolud;
     private String cewlud;
     private Integer ceflst;
     private String cecode;
     private String celtxt;
     private String cestxt;
     private Integer cey2id;
     private String cey2ty;
     private String cey2tx;
     private String cey2ev;
     private String cey2iv;
     private String cey2um;
     private String cey2vm;
     private Integer cegpsg;
     private Integer cecpsg;
     private Integer ceessg;

    public Tgpp632() {
    }

	
    public Tgpp632(String pkid) {
        this.pkid = pkid;
    }
    public Tgpp632(String pkid, String member, Integer ceelem, Integer ceintv, Integer celudt, Integer cetlup, Integer ceolud, String cewlud, Integer ceflst, String cecode, String celtxt, String cestxt, Integer cey2id, String cey2ty, String cey2tx, String cey2ev, String cey2iv, String cey2um, String cey2vm, Integer cegpsg, Integer cecpsg, Integer ceessg) {
       this.pkid = pkid;
       this.member = member;
       this.ceelem = ceelem;
       this.ceintv = ceintv;
       this.celudt = celudt;
       this.cetlup = cetlup;
       this.ceolud = ceolud;
       this.cewlud = cewlud;
       this.ceflst = ceflst;
       this.cecode = cecode;
       this.celtxt = celtxt;
       this.cestxt = cestxt;
       this.cey2id = cey2id;
       this.cey2ty = cey2ty;
       this.cey2tx = cey2tx;
       this.cey2ev = cey2ev;
       this.cey2iv = cey2iv;
       this.cey2um = cey2um;
       this.cey2vm = cey2vm;
       this.cegpsg = cegpsg;
       this.cecpsg = cecpsg;
       this.ceessg = ceessg;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getCeelem() {
        return this.ceelem;
    }
    
    public void setCeelem(Integer ceelem) {
        this.ceelem = ceelem;
    }
    public Integer getCeintv() {
        return this.ceintv;
    }
    
    public void setCeintv(Integer ceintv) {
        this.ceintv = ceintv;
    }
    public Integer getCeludt() {
        return this.celudt;
    }
    
    public void setCeludt(Integer celudt) {
        this.celudt = celudt;
    }
    public Integer getCetlup() {
        return this.cetlup;
    }
    
    public void setCetlup(Integer cetlup) {
        this.cetlup = cetlup;
    }
    public Integer getCeolud() {
        return this.ceolud;
    }
    
    public void setCeolud(Integer ceolud) {
        this.ceolud = ceolud;
    }
    public String getCewlud() {
        return this.cewlud;
    }
    
    public void setCewlud(String cewlud) {
        this.cewlud = cewlud;
    }
    public Integer getCeflst() {
        return this.ceflst;
    }
    
    public void setCeflst(Integer ceflst) {
        this.ceflst = ceflst;
    }
    public String getCecode() {
        return this.cecode;
    }
    
    public void setCecode(String cecode) {
        this.cecode = cecode;
    }
    public String getCeltxt() {
        return this.celtxt;
    }
    
    public void setCeltxt(String celtxt) {
        this.celtxt = celtxt;
    }
    public String getCestxt() {
        return this.cestxt;
    }
    
    public void setCestxt(String cestxt) {
        this.cestxt = cestxt;
    }
    public Integer getCey2id() {
        return this.cey2id;
    }
    
    public void setCey2id(Integer cey2id) {
        this.cey2id = cey2id;
    }
    public String getCey2ty() {
        return this.cey2ty;
    }
    
    public void setCey2ty(String cey2ty) {
        this.cey2ty = cey2ty;
    }
    public String getCey2tx() {
        return this.cey2tx;
    }
    
    public void setCey2tx(String cey2tx) {
        this.cey2tx = cey2tx;
    }
    public String getCey2ev() {
        return this.cey2ev;
    }
    
    public void setCey2ev(String cey2ev) {
        this.cey2ev = cey2ev;
    }
    public String getCey2iv() {
        return this.cey2iv;
    }
    
    public void setCey2iv(String cey2iv) {
        this.cey2iv = cey2iv;
    }
    public String getCey2um() {
        return this.cey2um;
    }
    
    public void setCey2um(String cey2um) {
        this.cey2um = cey2um;
    }
    public String getCey2vm() {
        return this.cey2vm;
    }
    
    public void setCey2vm(String cey2vm) {
        this.cey2vm = cey2vm;
    }
    public Integer getCegpsg() {
        return this.cegpsg;
    }
    
    public void setCegpsg(Integer cegpsg) {
        this.cegpsg = cegpsg;
    }
    public Integer getCecpsg() {
        return this.cecpsg;
    }
    
    public void setCecpsg(Integer cecpsg) {
        this.cecpsg = cecpsg;
    }
    public Integer getCeessg() {
        return this.ceessg;
    }
    
    public void setCeessg(Integer ceessg) {
        this.ceessg = ceessg;
    }




}


