package com.ciessa.museum.model.legacy;
// Generated Jan 28, 2019 1:33:59 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Tranem generated by hbm2java
 */
public class Tranem  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer cbanco;
     private Integer csucur;
     private String cbat;
     private Integer nbat;
     private Integer nsec;
     private String codop;
     private Integer daain;
     private Integer dmmin;
     private Integer dddin;
     private Integer daava;
     private Integer dmmva;
     private Integer dddva;
     private String covrfe;
     private String aopid;
     private String aopia;
     private String xstat;
     private Long ncta;
     private BigDecimal simloc;
     private Integer ctraex;
     private Integer ctrain;
     private Integer cdbcr;
     private Integer caplic;
     private Integer fcomtr;
     private String cref;
     private Integer qoper;
     private Integer cmonex;
     private BigDecimal simpex;
     private BigDecimal stpcan;
     private String cposcm;
     private Integer cccost;
     private String covrtr;
     private String xerror;
     private String cerror;
     private String awrkst;
     private Integer ahora;
     private String capint;
     private String xvalid;
     private String ctcta;
     private String cctaco;
     private String ctrsim;
     private String ctrdct;
     private String cbatco;
     private String trreun;
     private String tridcp;
     private String trfgtr;

    public Tranem() {
    }

	
    public Tranem(String pkid) {
        this.pkid = pkid;
    }
    public Tranem(String pkid, String member, Integer cbanco, Integer csucur, String cbat, Integer nbat, Integer nsec, String codop, Integer daain, Integer dmmin, Integer dddin, Integer daava, Integer dmmva, Integer dddva, String covrfe, String aopid, String aopia, String xstat, Long ncta, BigDecimal simloc, Integer ctraex, Integer ctrain, Integer cdbcr, Integer caplic, Integer fcomtr, String cref, Integer qoper, Integer cmonex, BigDecimal simpex, BigDecimal stpcan, String cposcm, Integer cccost, String covrtr, String xerror, String cerror, String awrkst, Integer ahora, String capint, String xvalid, String ctcta, String cctaco, String ctrsim, String ctrdct, String cbatco, String trreun, String tridcp, String trfgtr) {
       this.pkid = pkid;
       this.member = member;
       this.cbanco = cbanco;
       this.csucur = csucur;
       this.cbat = cbat;
       this.nbat = nbat;
       this.nsec = nsec;
       this.codop = codop;
       this.daain = daain;
       this.dmmin = dmmin;
       this.dddin = dddin;
       this.daava = daava;
       this.dmmva = dmmva;
       this.dddva = dddva;
       this.covrfe = covrfe;
       this.aopid = aopid;
       this.aopia = aopia;
       this.xstat = xstat;
       this.ncta = ncta;
       this.simloc = simloc;
       this.ctraex = ctraex;
       this.ctrain = ctrain;
       this.cdbcr = cdbcr;
       this.caplic = caplic;
       this.fcomtr = fcomtr;
       this.cref = cref;
       this.qoper = qoper;
       this.cmonex = cmonex;
       this.simpex = simpex;
       this.stpcan = stpcan;
       this.cposcm = cposcm;
       this.cccost = cccost;
       this.covrtr = covrtr;
       this.xerror = xerror;
       this.cerror = cerror;
       this.awrkst = awrkst;
       this.ahora = ahora;
       this.capint = capint;
       this.xvalid = xvalid;
       this.ctcta = ctcta;
       this.cctaco = cctaco;
       this.ctrsim = ctrsim;
       this.ctrdct = ctrdct;
       this.cbatco = cbatco;
       this.trreun = trreun;
       this.tridcp = tridcp;
       this.trfgtr = trfgtr;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getCbanco() {
        return this.cbanco;
    }
    
    public void setCbanco(Integer cbanco) {
        this.cbanco = cbanco;
    }
    public Integer getCsucur() {
        return this.csucur;
    }
    
    public void setCsucur(Integer csucur) {
        this.csucur = csucur;
    }
    public String getCbat() {
        return this.cbat;
    }
    
    public void setCbat(String cbat) {
        this.cbat = cbat;
    }
    public Integer getNbat() {
        return this.nbat;
    }
    
    public void setNbat(Integer nbat) {
        this.nbat = nbat;
    }
    public Integer getNsec() {
        return this.nsec;
    }
    
    public void setNsec(Integer nsec) {
        this.nsec = nsec;
    }
    public String getCodop() {
        return this.codop;
    }
    
    public void setCodop(String codop) {
        this.codop = codop;
    }
    public Integer getDaain() {
        return this.daain;
    }
    
    public void setDaain(Integer daain) {
        this.daain = daain;
    }
    public Integer getDmmin() {
        return this.dmmin;
    }
    
    public void setDmmin(Integer dmmin) {
        this.dmmin = dmmin;
    }
    public Integer getDddin() {
        return this.dddin;
    }
    
    public void setDddin(Integer dddin) {
        this.dddin = dddin;
    }
    public Integer getDaava() {
        return this.daava;
    }
    
    public void setDaava(Integer daava) {
        this.daava = daava;
    }
    public Integer getDmmva() {
        return this.dmmva;
    }
    
    public void setDmmva(Integer dmmva) {
        this.dmmva = dmmva;
    }
    public Integer getDddva() {
        return this.dddva;
    }
    
    public void setDddva(Integer dddva) {
        this.dddva = dddva;
    }
    public String getCovrfe() {
        return this.covrfe;
    }
    
    public void setCovrfe(String covrfe) {
        this.covrfe = covrfe;
    }
    public String getAopid() {
        return this.aopid;
    }
    
    public void setAopid(String aopid) {
        this.aopid = aopid;
    }
    public String getAopia() {
        return this.aopia;
    }
    
    public void setAopia(String aopia) {
        this.aopia = aopia;
    }
    public String getXstat() {
        return this.xstat;
    }
    
    public void setXstat(String xstat) {
        this.xstat = xstat;
    }
    public Long getNcta() {
        return this.ncta;
    }
    
    public void setNcta(Long ncta) {
        this.ncta = ncta;
    }
    public BigDecimal getSimloc() {
        return this.simloc;
    }
    
    public void setSimloc(BigDecimal simloc) {
        this.simloc = simloc;
    }
    public Integer getCtraex() {
        return this.ctraex;
    }
    
    public void setCtraex(Integer ctraex) {
        this.ctraex = ctraex;
    }
    public Integer getCtrain() {
        return this.ctrain;
    }
    
    public void setCtrain(Integer ctrain) {
        this.ctrain = ctrain;
    }
    public Integer getCdbcr() {
        return this.cdbcr;
    }
    
    public void setCdbcr(Integer cdbcr) {
        this.cdbcr = cdbcr;
    }
    public Integer getCaplic() {
        return this.caplic;
    }
    
    public void setCaplic(Integer caplic) {
        this.caplic = caplic;
    }
    public Integer getFcomtr() {
        return this.fcomtr;
    }
    
    public void setFcomtr(Integer fcomtr) {
        this.fcomtr = fcomtr;
    }
    public String getCref() {
        return this.cref;
    }
    
    public void setCref(String cref) {
        this.cref = cref;
    }
    public Integer getQoper() {
        return this.qoper;
    }
    
    public void setQoper(Integer qoper) {
        this.qoper = qoper;
    }
    public Integer getCmonex() {
        return this.cmonex;
    }
    
    public void setCmonex(Integer cmonex) {
        this.cmonex = cmonex;
    }
    public BigDecimal getSimpex() {
        return this.simpex;
    }
    
    public void setSimpex(BigDecimal simpex) {
        this.simpex = simpex;
    }
    public BigDecimal getStpcan() {
        return this.stpcan;
    }
    
    public void setStpcan(BigDecimal stpcan) {
        this.stpcan = stpcan;
    }
    public String getCposcm() {
        return this.cposcm;
    }
    
    public void setCposcm(String cposcm) {
        this.cposcm = cposcm;
    }
    public Integer getCccost() {
        return this.cccost;
    }
    
    public void setCccost(Integer cccost) {
        this.cccost = cccost;
    }
    public String getCovrtr() {
        return this.covrtr;
    }
    
    public void setCovrtr(String covrtr) {
        this.covrtr = covrtr;
    }
    public String getXerror() {
        return this.xerror;
    }
    
    public void setXerror(String xerror) {
        this.xerror = xerror;
    }
    public String getCerror() {
        return this.cerror;
    }
    
    public void setCerror(String cerror) {
        this.cerror = cerror;
    }
    public String getAwrkst() {
        return this.awrkst;
    }
    
    public void setAwrkst(String awrkst) {
        this.awrkst = awrkst;
    }
    public Integer getAhora() {
        return this.ahora;
    }
    
    public void setAhora(Integer ahora) {
        this.ahora = ahora;
    }
    public String getCapint() {
        return this.capint;
    }
    
    public void setCapint(String capint) {
        this.capint = capint;
    }
    public String getXvalid() {
        return this.xvalid;
    }
    
    public void setXvalid(String xvalid) {
        this.xvalid = xvalid;
    }
    public String getCtcta() {
        return this.ctcta;
    }
    
    public void setCtcta(String ctcta) {
        this.ctcta = ctcta;
    }
    public String getCctaco() {
        return this.cctaco;
    }
    
    public void setCctaco(String cctaco) {
        this.cctaco = cctaco;
    }
    public String getCtrsim() {
        return this.ctrsim;
    }
    
    public void setCtrsim(String ctrsim) {
        this.ctrsim = ctrsim;
    }
    public String getCtrdct() {
        return this.ctrdct;
    }
    
    public void setCtrdct(String ctrdct) {
        this.ctrdct = ctrdct;
    }
    public String getCbatco() {
        return this.cbatco;
    }
    
    public void setCbatco(String cbatco) {
        this.cbatco = cbatco;
    }
    public String getTrreun() {
        return this.trreun;
    }
    
    public void setTrreun(String trreun) {
        this.trreun = trreun;
    }
    public String getTridcp() {
        return this.tridcp;
    }
    
    public void setTridcp(String tridcp) {
        this.tridcp = tridcp;
    }
    public String getTrfgtr() {
        return this.trfgtr;
    }
    
    public void setTrfgtr(String trfgtr) {
        this.trfgtr = trfgtr;
    }




}


