package com.ciessa.museum.model.legacy;
// Generated Dec 8, 2018 1:27:28 AM by Hibernate Tools 3.2.2.GA



/**
 * Zbhpvrz generated by hbm2java
 */
public class Zbhpvrz  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Long vzrmcn;
     private Long vznrvz;
     private Integer vzscor;
     private Integer vzfrsc;
     private Integer vzasco;
     private Integer vzfsco;
     private Integer vzrgo6;
     private Integer vzpmin;
     private Integer vzqtar;
     private Integer vzsatr;
     private Integer vzalcr;
     private Integer vzapmi;
     private Integer vzpuu3;
     private Integer vzpuu6;
     private Integer vzlmax;
     private Integer vzqcta;
     private Integer vzsacc;
     private Integer vzalds;
     private Integer vzaipv;
     private Integer vzpua3;
     private Integer vzpua6;
     private Integer vzlmcc;
     private Integer vzqpsg;
     private Integer vzassg;
     private Integer vzmpsg;
     private Integer vzmcsg;
     private Integer vzqpgp;
     private Integer vzasgp;
     private Integer vzmpgp;
     private Integer vzmcgp;
     private Integer vzqpgh;
     private Integer vzasgh;
     private Integer vzmngh;
     private Integer vzscgh;
     private Integer vzmatc;
     private Integer vzmacc;
     private Integer vzqta6;
     private Integer vzqca6;
     private Integer vzqsa6;
     private Integer vzqpa6;
     private Integer vzqha6;
     private Integer vzmput;
     private Integer vzmsg6;
     private Integer vzsvtc;
     private Integer vzsvcc;
     private Integer vzsvsg;
     private Integer vzsvgp;
     private Integer vzsvgh;
     private String vzclvz;
     private String vzcltc;
     private String vzclcc;
     private String vzclgh;
     private String vzclgp;
     private String vzclsg;
     private String vzclot;
     private String vzdisa;
     private String vzmhit;

    public Zbhpvrz() {
    }

	
    public Zbhpvrz(String pkid) {
        this.pkid = pkid;
    }
    public Zbhpvrz(String pkid, String member, Long vzrmcn, Long vznrvz, Integer vzscor, Integer vzfrsc, Integer vzasco, Integer vzfsco, Integer vzrgo6, Integer vzpmin, Integer vzqtar, Integer vzsatr, Integer vzalcr, Integer vzapmi, Integer vzpuu3, Integer vzpuu6, Integer vzlmax, Integer vzqcta, Integer vzsacc, Integer vzalds, Integer vzaipv, Integer vzpua3, Integer vzpua6, Integer vzlmcc, Integer vzqpsg, Integer vzassg, Integer vzmpsg, Integer vzmcsg, Integer vzqpgp, Integer vzasgp, Integer vzmpgp, Integer vzmcgp, Integer vzqpgh, Integer vzasgh, Integer vzmngh, Integer vzscgh, Integer vzmatc, Integer vzmacc, Integer vzqta6, Integer vzqca6, Integer vzqsa6, Integer vzqpa6, Integer vzqha6, Integer vzmput, Integer vzmsg6, Integer vzsvtc, Integer vzsvcc, Integer vzsvsg, Integer vzsvgp, Integer vzsvgh, String vzclvz, String vzcltc, String vzclcc, String vzclgh, String vzclgp, String vzclsg, String vzclot, String vzdisa, String vzmhit) {
       this.pkid = pkid;
       this.member = member;
       this.vzrmcn = vzrmcn;
       this.vznrvz = vznrvz;
       this.vzscor = vzscor;
       this.vzfrsc = vzfrsc;
       this.vzasco = vzasco;
       this.vzfsco = vzfsco;
       this.vzrgo6 = vzrgo6;
       this.vzpmin = vzpmin;
       this.vzqtar = vzqtar;
       this.vzsatr = vzsatr;
       this.vzalcr = vzalcr;
       this.vzapmi = vzapmi;
       this.vzpuu3 = vzpuu3;
       this.vzpuu6 = vzpuu6;
       this.vzlmax = vzlmax;
       this.vzqcta = vzqcta;
       this.vzsacc = vzsacc;
       this.vzalds = vzalds;
       this.vzaipv = vzaipv;
       this.vzpua3 = vzpua3;
       this.vzpua6 = vzpua6;
       this.vzlmcc = vzlmcc;
       this.vzqpsg = vzqpsg;
       this.vzassg = vzassg;
       this.vzmpsg = vzmpsg;
       this.vzmcsg = vzmcsg;
       this.vzqpgp = vzqpgp;
       this.vzasgp = vzasgp;
       this.vzmpgp = vzmpgp;
       this.vzmcgp = vzmcgp;
       this.vzqpgh = vzqpgh;
       this.vzasgh = vzasgh;
       this.vzmngh = vzmngh;
       this.vzscgh = vzscgh;
       this.vzmatc = vzmatc;
       this.vzmacc = vzmacc;
       this.vzqta6 = vzqta6;
       this.vzqca6 = vzqca6;
       this.vzqsa6 = vzqsa6;
       this.vzqpa6 = vzqpa6;
       this.vzqha6 = vzqha6;
       this.vzmput = vzmput;
       this.vzmsg6 = vzmsg6;
       this.vzsvtc = vzsvtc;
       this.vzsvcc = vzsvcc;
       this.vzsvsg = vzsvsg;
       this.vzsvgp = vzsvgp;
       this.vzsvgh = vzsvgh;
       this.vzclvz = vzclvz;
       this.vzcltc = vzcltc;
       this.vzclcc = vzclcc;
       this.vzclgh = vzclgh;
       this.vzclgp = vzclgp;
       this.vzclsg = vzclsg;
       this.vzclot = vzclot;
       this.vzdisa = vzdisa;
       this.vzmhit = vzmhit;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Long getVzrmcn() {
        return this.vzrmcn;
    }
    
    public void setVzrmcn(Long vzrmcn) {
        this.vzrmcn = vzrmcn;
    }
    public Long getVznrvz() {
        return this.vznrvz;
    }
    
    public void setVznrvz(Long vznrvz) {
        this.vznrvz = vznrvz;
    }
    public Integer getVzscor() {
        return this.vzscor;
    }
    
    public void setVzscor(Integer vzscor) {
        this.vzscor = vzscor;
    }
    public Integer getVzfrsc() {
        return this.vzfrsc;
    }
    
    public void setVzfrsc(Integer vzfrsc) {
        this.vzfrsc = vzfrsc;
    }
    public Integer getVzasco() {
        return this.vzasco;
    }
    
    public void setVzasco(Integer vzasco) {
        this.vzasco = vzasco;
    }
    public Integer getVzfsco() {
        return this.vzfsco;
    }
    
    public void setVzfsco(Integer vzfsco) {
        this.vzfsco = vzfsco;
    }
    public Integer getVzrgo6() {
        return this.vzrgo6;
    }
    
    public void setVzrgo6(Integer vzrgo6) {
        this.vzrgo6 = vzrgo6;
    }
    public Integer getVzpmin() {
        return this.vzpmin;
    }
    
    public void setVzpmin(Integer vzpmin) {
        this.vzpmin = vzpmin;
    }
    public Integer getVzqtar() {
        return this.vzqtar;
    }
    
    public void setVzqtar(Integer vzqtar) {
        this.vzqtar = vzqtar;
    }
    public Integer getVzsatr() {
        return this.vzsatr;
    }
    
    public void setVzsatr(Integer vzsatr) {
        this.vzsatr = vzsatr;
    }
    public Integer getVzalcr() {
        return this.vzalcr;
    }
    
    public void setVzalcr(Integer vzalcr) {
        this.vzalcr = vzalcr;
    }
    public Integer getVzapmi() {
        return this.vzapmi;
    }
    
    public void setVzapmi(Integer vzapmi) {
        this.vzapmi = vzapmi;
    }
    public Integer getVzpuu3() {
        return this.vzpuu3;
    }
    
    public void setVzpuu3(Integer vzpuu3) {
        this.vzpuu3 = vzpuu3;
    }
    public Integer getVzpuu6() {
        return this.vzpuu6;
    }
    
    public void setVzpuu6(Integer vzpuu6) {
        this.vzpuu6 = vzpuu6;
    }
    public Integer getVzlmax() {
        return this.vzlmax;
    }
    
    public void setVzlmax(Integer vzlmax) {
        this.vzlmax = vzlmax;
    }
    public Integer getVzqcta() {
        return this.vzqcta;
    }
    
    public void setVzqcta(Integer vzqcta) {
        this.vzqcta = vzqcta;
    }
    public Integer getVzsacc() {
        return this.vzsacc;
    }
    
    public void setVzsacc(Integer vzsacc) {
        this.vzsacc = vzsacc;
    }
    public Integer getVzalds() {
        return this.vzalds;
    }
    
    public void setVzalds(Integer vzalds) {
        this.vzalds = vzalds;
    }
    public Integer getVzaipv() {
        return this.vzaipv;
    }
    
    public void setVzaipv(Integer vzaipv) {
        this.vzaipv = vzaipv;
    }
    public Integer getVzpua3() {
        return this.vzpua3;
    }
    
    public void setVzpua3(Integer vzpua3) {
        this.vzpua3 = vzpua3;
    }
    public Integer getVzpua6() {
        return this.vzpua6;
    }
    
    public void setVzpua6(Integer vzpua6) {
        this.vzpua6 = vzpua6;
    }
    public Integer getVzlmcc() {
        return this.vzlmcc;
    }
    
    public void setVzlmcc(Integer vzlmcc) {
        this.vzlmcc = vzlmcc;
    }
    public Integer getVzqpsg() {
        return this.vzqpsg;
    }
    
    public void setVzqpsg(Integer vzqpsg) {
        this.vzqpsg = vzqpsg;
    }
    public Integer getVzassg() {
        return this.vzassg;
    }
    
    public void setVzassg(Integer vzassg) {
        this.vzassg = vzassg;
    }
    public Integer getVzmpsg() {
        return this.vzmpsg;
    }
    
    public void setVzmpsg(Integer vzmpsg) {
        this.vzmpsg = vzmpsg;
    }
    public Integer getVzmcsg() {
        return this.vzmcsg;
    }
    
    public void setVzmcsg(Integer vzmcsg) {
        this.vzmcsg = vzmcsg;
    }
    public Integer getVzqpgp() {
        return this.vzqpgp;
    }
    
    public void setVzqpgp(Integer vzqpgp) {
        this.vzqpgp = vzqpgp;
    }
    public Integer getVzasgp() {
        return this.vzasgp;
    }
    
    public void setVzasgp(Integer vzasgp) {
        this.vzasgp = vzasgp;
    }
    public Integer getVzmpgp() {
        return this.vzmpgp;
    }
    
    public void setVzmpgp(Integer vzmpgp) {
        this.vzmpgp = vzmpgp;
    }
    public Integer getVzmcgp() {
        return this.vzmcgp;
    }
    
    public void setVzmcgp(Integer vzmcgp) {
        this.vzmcgp = vzmcgp;
    }
    public Integer getVzqpgh() {
        return this.vzqpgh;
    }
    
    public void setVzqpgh(Integer vzqpgh) {
        this.vzqpgh = vzqpgh;
    }
    public Integer getVzasgh() {
        return this.vzasgh;
    }
    
    public void setVzasgh(Integer vzasgh) {
        this.vzasgh = vzasgh;
    }
    public Integer getVzmngh() {
        return this.vzmngh;
    }
    
    public void setVzmngh(Integer vzmngh) {
        this.vzmngh = vzmngh;
    }
    public Integer getVzscgh() {
        return this.vzscgh;
    }
    
    public void setVzscgh(Integer vzscgh) {
        this.vzscgh = vzscgh;
    }
    public Integer getVzmatc() {
        return this.vzmatc;
    }
    
    public void setVzmatc(Integer vzmatc) {
        this.vzmatc = vzmatc;
    }
    public Integer getVzmacc() {
        return this.vzmacc;
    }
    
    public void setVzmacc(Integer vzmacc) {
        this.vzmacc = vzmacc;
    }
    public Integer getVzqta6() {
        return this.vzqta6;
    }
    
    public void setVzqta6(Integer vzqta6) {
        this.vzqta6 = vzqta6;
    }
    public Integer getVzqca6() {
        return this.vzqca6;
    }
    
    public void setVzqca6(Integer vzqca6) {
        this.vzqca6 = vzqca6;
    }
    public Integer getVzqsa6() {
        return this.vzqsa6;
    }
    
    public void setVzqsa6(Integer vzqsa6) {
        this.vzqsa6 = vzqsa6;
    }
    public Integer getVzqpa6() {
        return this.vzqpa6;
    }
    
    public void setVzqpa6(Integer vzqpa6) {
        this.vzqpa6 = vzqpa6;
    }
    public Integer getVzqha6() {
        return this.vzqha6;
    }
    
    public void setVzqha6(Integer vzqha6) {
        this.vzqha6 = vzqha6;
    }
    public Integer getVzmput() {
        return this.vzmput;
    }
    
    public void setVzmput(Integer vzmput) {
        this.vzmput = vzmput;
    }
    public Integer getVzmsg6() {
        return this.vzmsg6;
    }
    
    public void setVzmsg6(Integer vzmsg6) {
        this.vzmsg6 = vzmsg6;
    }
    public Integer getVzsvtc() {
        return this.vzsvtc;
    }
    
    public void setVzsvtc(Integer vzsvtc) {
        this.vzsvtc = vzsvtc;
    }
    public Integer getVzsvcc() {
        return this.vzsvcc;
    }
    
    public void setVzsvcc(Integer vzsvcc) {
        this.vzsvcc = vzsvcc;
    }
    public Integer getVzsvsg() {
        return this.vzsvsg;
    }
    
    public void setVzsvsg(Integer vzsvsg) {
        this.vzsvsg = vzsvsg;
    }
    public Integer getVzsvgp() {
        return this.vzsvgp;
    }
    
    public void setVzsvgp(Integer vzsvgp) {
        this.vzsvgp = vzsvgp;
    }
    public Integer getVzsvgh() {
        return this.vzsvgh;
    }
    
    public void setVzsvgh(Integer vzsvgh) {
        this.vzsvgh = vzsvgh;
    }
    public String getVzclvz() {
        return this.vzclvz;
    }
    
    public void setVzclvz(String vzclvz) {
        this.vzclvz = vzclvz;
    }
    public String getVzcltc() {
        return this.vzcltc;
    }
    
    public void setVzcltc(String vzcltc) {
        this.vzcltc = vzcltc;
    }
    public String getVzclcc() {
        return this.vzclcc;
    }
    
    public void setVzclcc(String vzclcc) {
        this.vzclcc = vzclcc;
    }
    public String getVzclgh() {
        return this.vzclgh;
    }
    
    public void setVzclgh(String vzclgh) {
        this.vzclgh = vzclgh;
    }
    public String getVzclgp() {
        return this.vzclgp;
    }
    
    public void setVzclgp(String vzclgp) {
        this.vzclgp = vzclgp;
    }
    public String getVzclsg() {
        return this.vzclsg;
    }
    
    public void setVzclsg(String vzclsg) {
        this.vzclsg = vzclsg;
    }
    public String getVzclot() {
        return this.vzclot;
    }
    
    public void setVzclot(String vzclot) {
        this.vzclot = vzclot;
    }
    public String getVzdisa() {
        return this.vzdisa;
    }
    
    public void setVzdisa(String vzdisa) {
        this.vzdisa = vzdisa;
    }
    public String getVzmhit() {
        return this.vzmhit;
    }
    
    public void setVzmhit(String vzmhit) {
        this.vzmhit = vzmhit;
    }




}


