package com.ciessa.museum.model.legacy;
// Generated Dec 8, 2018 1:27:28 AM by Hibernate Tools 3.2.2.GA



/**
 * Zpcpclr generated by hbm2java
 */
public class Zpcpclr  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer clco;
     private String clno;
     private String clabrv;
     private String clesco;
     private Integer cluaaa;
     private Integer cluamm;
     private Integer cluadd;
     private Integer cluahr;
     private String cluaop;

    public Zpcpclr() {
    }

	
    public Zpcpclr(String pkid) {
        this.pkid = pkid;
    }
    public Zpcpclr(String pkid, String member, Integer clco, String clno, String clabrv, String clesco, Integer cluaaa, Integer cluamm, Integer cluadd, Integer cluahr, String cluaop) {
       this.pkid = pkid;
       this.member = member;
       this.clco = clco;
       this.clno = clno;
       this.clabrv = clabrv;
       this.clesco = clesco;
       this.cluaaa = cluaaa;
       this.cluamm = cluamm;
       this.cluadd = cluadd;
       this.cluahr = cluahr;
       this.cluaop = cluaop;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getClco() {
        return this.clco;
    }
    
    public void setClco(Integer clco) {
        this.clco = clco;
    }
    public String getClno() {
        return this.clno;
    }
    
    public void setClno(String clno) {
        this.clno = clno;
    }
    public String getClabrv() {
        return this.clabrv;
    }
    
    public void setClabrv(String clabrv) {
        this.clabrv = clabrv;
    }
    public String getClesco() {
        return this.clesco;
    }
    
    public void setClesco(String clesco) {
        this.clesco = clesco;
    }
    public Integer getCluaaa() {
        return this.cluaaa;
    }
    
    public void setCluaaa(Integer cluaaa) {
        this.cluaaa = cluaaa;
    }
    public Integer getCluamm() {
        return this.cluamm;
    }
    
    public void setCluamm(Integer cluamm) {
        this.cluamm = cluamm;
    }
    public Integer getCluadd() {
        return this.cluadd;
    }
    
    public void setCluadd(Integer cluadd) {
        this.cluadd = cluadd;
    }
    public Integer getCluahr() {
        return this.cluahr;
    }
    
    public void setCluahr(Integer cluahr) {
        this.cluahr = cluahr;
    }
    public String getCluaop() {
        return this.cluaop;
    }
    
    public void setCluaop(String cluaop) {
        this.cluaop = cluaop;
    }




}


