package com.ciessa.museum.model.legacy;
// Generated Jul 13, 2018 12:00:44 PM by Hibernate Tools 3.2.2.GA



/**
 * Zrsplem generated by hbm2java
 */
public class Zrsplem  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String amtmai;
     private Integer amnmai;
     private Integer amnuli;
     private Integer amlcs1;
     private Integer amlcs2;
     private Integer amlcs3;
     private Integer amlcs4;
     private Integer amlcs5;
     private String amltxc;
     private String amemai;
     private String amus01;
     private String amus02;
     private String amus03;
     private String amus04;
     private String amus05;
     private String amus06;
     private String amus07;
     private String amus08;
     private String amus09;
     private String amus10;
     private String amus11;
     private String amus12;
     private String amus13;
     private String amus14;
     private String amus15;
     private String amus16;
     private String amus17;
     private String amus18;
     private String amus19;
     private String amus20;
     private String amus21;
     private String amus22;
     private String amprcd;
     private Integer amiddp;
     private String amubdg;
     private String amcope;
     private Integer amfac8;
     private Integer amhact;

    public Zrsplem() {
    }

	
    public Zrsplem(String pkid) {
        this.pkid = pkid;
    }
    public Zrsplem(String pkid, String member, String amtmai, Integer amnmai, Integer amnuli, Integer amlcs1, Integer amlcs2, Integer amlcs3, Integer amlcs4, Integer amlcs5, String amltxc, String amemai, String amus01, String amus02, String amus03, String amus04, String amus05, String amus06, String amus07, String amus08, String amus09, String amus10, String amus11, String amus12, String amus13, String amus14, String amus15, String amus16, String amus17, String amus18, String amus19, String amus20, String amus21, String amus22, String amprcd, Integer amiddp, String amubdg, String amcope, Integer amfac8, Integer amhact) {
       this.pkid = pkid;
       this.member = member;
       this.amtmai = amtmai;
       this.amnmai = amnmai;
       this.amnuli = amnuli;
       this.amlcs1 = amlcs1;
       this.amlcs2 = amlcs2;
       this.amlcs3 = amlcs3;
       this.amlcs4 = amlcs4;
       this.amlcs5 = amlcs5;
       this.amltxc = amltxc;
       this.amemai = amemai;
       this.amus01 = amus01;
       this.amus02 = amus02;
       this.amus03 = amus03;
       this.amus04 = amus04;
       this.amus05 = amus05;
       this.amus06 = amus06;
       this.amus07 = amus07;
       this.amus08 = amus08;
       this.amus09 = amus09;
       this.amus10 = amus10;
       this.amus11 = amus11;
       this.amus12 = amus12;
       this.amus13 = amus13;
       this.amus14 = amus14;
       this.amus15 = amus15;
       this.amus16 = amus16;
       this.amus17 = amus17;
       this.amus18 = amus18;
       this.amus19 = amus19;
       this.amus20 = amus20;
       this.amus21 = amus21;
       this.amus22 = amus22;
       this.amprcd = amprcd;
       this.amiddp = amiddp;
       this.amubdg = amubdg;
       this.amcope = amcope;
       this.amfac8 = amfac8;
       this.amhact = amhact;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getAmtmai() {
        return this.amtmai;
    }
    
    public void setAmtmai(String amtmai) {
        this.amtmai = amtmai;
    }
    public Integer getAmnmai() {
        return this.amnmai;
    }
    
    public void setAmnmai(Integer amnmai) {
        this.amnmai = amnmai;
    }
    public Integer getAmnuli() {
        return this.amnuli;
    }
    
    public void setAmnuli(Integer amnuli) {
        this.amnuli = amnuli;
    }
    public Integer getAmlcs1() {
        return this.amlcs1;
    }
    
    public void setAmlcs1(Integer amlcs1) {
        this.amlcs1 = amlcs1;
    }
    public Integer getAmlcs2() {
        return this.amlcs2;
    }
    
    public void setAmlcs2(Integer amlcs2) {
        this.amlcs2 = amlcs2;
    }
    public Integer getAmlcs3() {
        return this.amlcs3;
    }
    
    public void setAmlcs3(Integer amlcs3) {
        this.amlcs3 = amlcs3;
    }
    public Integer getAmlcs4() {
        return this.amlcs4;
    }
    
    public void setAmlcs4(Integer amlcs4) {
        this.amlcs4 = amlcs4;
    }
    public Integer getAmlcs5() {
        return this.amlcs5;
    }
    
    public void setAmlcs5(Integer amlcs5) {
        this.amlcs5 = amlcs5;
    }
    public String getAmltxc() {
        return this.amltxc;
    }
    
    public void setAmltxc(String amltxc) {
        this.amltxc = amltxc;
    }
    public String getAmemai() {
        return this.amemai;
    }
    
    public void setAmemai(String amemai) {
        this.amemai = amemai;
    }
    public String getAmus01() {
        return this.amus01;
    }
    
    public void setAmus01(String amus01) {
        this.amus01 = amus01;
    }
    public String getAmus02() {
        return this.amus02;
    }
    
    public void setAmus02(String amus02) {
        this.amus02 = amus02;
    }
    public String getAmus03() {
        return this.amus03;
    }
    
    public void setAmus03(String amus03) {
        this.amus03 = amus03;
    }
    public String getAmus04() {
        return this.amus04;
    }
    
    public void setAmus04(String amus04) {
        this.amus04 = amus04;
    }
    public String getAmus05() {
        return this.amus05;
    }
    
    public void setAmus05(String amus05) {
        this.amus05 = amus05;
    }
    public String getAmus06() {
        return this.amus06;
    }
    
    public void setAmus06(String amus06) {
        this.amus06 = amus06;
    }
    public String getAmus07() {
        return this.amus07;
    }
    
    public void setAmus07(String amus07) {
        this.amus07 = amus07;
    }
    public String getAmus08() {
        return this.amus08;
    }
    
    public void setAmus08(String amus08) {
        this.amus08 = amus08;
    }
    public String getAmus09() {
        return this.amus09;
    }
    
    public void setAmus09(String amus09) {
        this.amus09 = amus09;
    }
    public String getAmus10() {
        return this.amus10;
    }
    
    public void setAmus10(String amus10) {
        this.amus10 = amus10;
    }
    public String getAmus11() {
        return this.amus11;
    }
    
    public void setAmus11(String amus11) {
        this.amus11 = amus11;
    }
    public String getAmus12() {
        return this.amus12;
    }
    
    public void setAmus12(String amus12) {
        this.amus12 = amus12;
    }
    public String getAmus13() {
        return this.amus13;
    }
    
    public void setAmus13(String amus13) {
        this.amus13 = amus13;
    }
    public String getAmus14() {
        return this.amus14;
    }
    
    public void setAmus14(String amus14) {
        this.amus14 = amus14;
    }
    public String getAmus15() {
        return this.amus15;
    }
    
    public void setAmus15(String amus15) {
        this.amus15 = amus15;
    }
    public String getAmus16() {
        return this.amus16;
    }
    
    public void setAmus16(String amus16) {
        this.amus16 = amus16;
    }
    public String getAmus17() {
        return this.amus17;
    }
    
    public void setAmus17(String amus17) {
        this.amus17 = amus17;
    }
    public String getAmus18() {
        return this.amus18;
    }
    
    public void setAmus18(String amus18) {
        this.amus18 = amus18;
    }
    public String getAmus19() {
        return this.amus19;
    }
    
    public void setAmus19(String amus19) {
        this.amus19 = amus19;
    }
    public String getAmus20() {
        return this.amus20;
    }
    
    public void setAmus20(String amus20) {
        this.amus20 = amus20;
    }
    public String getAmus21() {
        return this.amus21;
    }
    
    public void setAmus21(String amus21) {
        this.amus21 = amus21;
    }
    public String getAmus22() {
        return this.amus22;
    }
    
    public void setAmus22(String amus22) {
        this.amus22 = amus22;
    }
    public String getAmprcd() {
        return this.amprcd;
    }
    
    public void setAmprcd(String amprcd) {
        this.amprcd = amprcd;
    }
    public Integer getAmiddp() {
        return this.amiddp;
    }
    
    public void setAmiddp(Integer amiddp) {
        this.amiddp = amiddp;
    }
    public String getAmubdg() {
        return this.amubdg;
    }
    
    public void setAmubdg(String amubdg) {
        this.amubdg = amubdg;
    }
    public String getAmcope() {
        return this.amcope;
    }
    
    public void setAmcope(String amcope) {
        this.amcope = amcope;
    }
    public Integer getAmfac8() {
        return this.amfac8;
    }
    
    public void setAmfac8(Integer amfac8) {
        this.amfac8 = amfac8;
    }
    public Integer getAmhact() {
        return this.amhact;
    }
    
    public void setAmhact(Integer amhact) {
        this.amhact = amhact;
    }




}


