package com.ciessa.museum.model.legacy;
// Generated Jan 28, 2019 1:33:59 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Zrspilr generated by hbm2java
 */
public class Zrspilr  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer ilyfac;
     private Integer ilaafc;
     private String ilcifa;
     private String ilagig;
     private Integer ilorg;
     private Integer illogo;
     private String ilncct;
     private String ilncrd;
     private Integer ilptnr;
     private Integer ilncax;
     private String ilntal;
     private Integer ilcori;
     private Integer ilcmov;
     private Integer ilcsmv;
     private Integer ilnsem;
     private Integer ilymov;
     private Integer ilamov;
     private Integer ilmmov;
     private Integer ildmov;
     private Integer ilcdin;
     private Integer iladin;
     private Integer ilmdin;
     private Integer ilddin;
     private Integer ilchin;
     private Integer ilahin;
     private Integer ilmhin;
     private Integer ildhin;
     private BigDecimal ilibci;
     private Integer ildiin;
     private BigDecimal iltidd;
     private BigDecimal iltidh;
     private BigDecimal iltipr;
     private BigDecimal ilicpm;
     private String ilubir;
     private String ilmini;
     private Integer ilfact;
     private Integer ilhact;
     private String ilcope;
     private String ilxtrf;
     private Integer ilccyc;
     private String ilctrs;
     private Integer ilecsl;
     private Integer ilnpla;
     private String ilprmi;

    public Zrspilr() {
    }

	
    public Zrspilr(String pkid) {
        this.pkid = pkid;
    }
    public Zrspilr(String pkid, String member, Integer ilyfac, Integer ilaafc, String ilcifa, String ilagig, Integer ilorg, Integer illogo, String ilncct, String ilncrd, Integer ilptnr, Integer ilncax, String ilntal, Integer ilcori, Integer ilcmov, Integer ilcsmv, Integer ilnsem, Integer ilymov, Integer ilamov, Integer ilmmov, Integer ildmov, Integer ilcdin, Integer iladin, Integer ilmdin, Integer ilddin, Integer ilchin, Integer ilahin, Integer ilmhin, Integer ildhin, BigDecimal ilibci, Integer ildiin, BigDecimal iltidd, BigDecimal iltidh, BigDecimal iltipr, BigDecimal ilicpm, String ilubir, String ilmini, Integer ilfact, Integer ilhact, String ilcope, String ilxtrf, Integer ilccyc, String ilctrs, Integer ilecsl, Integer ilnpla, String ilprmi) {
       this.pkid = pkid;
       this.member = member;
       this.ilyfac = ilyfac;
       this.ilaafc = ilaafc;
       this.ilcifa = ilcifa;
       this.ilagig = ilagig;
       this.ilorg = ilorg;
       this.illogo = illogo;
       this.ilncct = ilncct;
       this.ilncrd = ilncrd;
       this.ilptnr = ilptnr;
       this.ilncax = ilncax;
       this.ilntal = ilntal;
       this.ilcori = ilcori;
       this.ilcmov = ilcmov;
       this.ilcsmv = ilcsmv;
       this.ilnsem = ilnsem;
       this.ilymov = ilymov;
       this.ilamov = ilamov;
       this.ilmmov = ilmmov;
       this.ildmov = ildmov;
       this.ilcdin = ilcdin;
       this.iladin = iladin;
       this.ilmdin = ilmdin;
       this.ilddin = ilddin;
       this.ilchin = ilchin;
       this.ilahin = ilahin;
       this.ilmhin = ilmhin;
       this.ildhin = ildhin;
       this.ilibci = ilibci;
       this.ildiin = ildiin;
       this.iltidd = iltidd;
       this.iltidh = iltidh;
       this.iltipr = iltipr;
       this.ilicpm = ilicpm;
       this.ilubir = ilubir;
       this.ilmini = ilmini;
       this.ilfact = ilfact;
       this.ilhact = ilhact;
       this.ilcope = ilcope;
       this.ilxtrf = ilxtrf;
       this.ilccyc = ilccyc;
       this.ilctrs = ilctrs;
       this.ilecsl = ilecsl;
       this.ilnpla = ilnpla;
       this.ilprmi = ilprmi;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getIlyfac() {
        return this.ilyfac;
    }
    
    public void setIlyfac(Integer ilyfac) {
        this.ilyfac = ilyfac;
    }
    public Integer getIlaafc() {
        return this.ilaafc;
    }
    
    public void setIlaafc(Integer ilaafc) {
        this.ilaafc = ilaafc;
    }
    public String getIlcifa() {
        return this.ilcifa;
    }
    
    public void setIlcifa(String ilcifa) {
        this.ilcifa = ilcifa;
    }
    public String getIlagig() {
        return this.ilagig;
    }
    
    public void setIlagig(String ilagig) {
        this.ilagig = ilagig;
    }
    public Integer getIlorg() {
        return this.ilorg;
    }
    
    public void setIlorg(Integer ilorg) {
        this.ilorg = ilorg;
    }
    public Integer getIllogo() {
        return this.illogo;
    }
    
    public void setIllogo(Integer illogo) {
        this.illogo = illogo;
    }
    public String getIlncct() {
        return this.ilncct;
    }
    
    public void setIlncct(String ilncct) {
        this.ilncct = ilncct;
    }
    public String getIlncrd() {
        return this.ilncrd;
    }
    
    public void setIlncrd(String ilncrd) {
        this.ilncrd = ilncrd;
    }
    public Integer getIlptnr() {
        return this.ilptnr;
    }
    
    public void setIlptnr(Integer ilptnr) {
        this.ilptnr = ilptnr;
    }
    public Integer getIlncax() {
        return this.ilncax;
    }
    
    public void setIlncax(Integer ilncax) {
        this.ilncax = ilncax;
    }
    public String getIlntal() {
        return this.ilntal;
    }
    
    public void setIlntal(String ilntal) {
        this.ilntal = ilntal;
    }
    public Integer getIlcori() {
        return this.ilcori;
    }
    
    public void setIlcori(Integer ilcori) {
        this.ilcori = ilcori;
    }
    public Integer getIlcmov() {
        return this.ilcmov;
    }
    
    public void setIlcmov(Integer ilcmov) {
        this.ilcmov = ilcmov;
    }
    public Integer getIlcsmv() {
        return this.ilcsmv;
    }
    
    public void setIlcsmv(Integer ilcsmv) {
        this.ilcsmv = ilcsmv;
    }
    public Integer getIlnsem() {
        return this.ilnsem;
    }
    
    public void setIlnsem(Integer ilnsem) {
        this.ilnsem = ilnsem;
    }
    public Integer getIlymov() {
        return this.ilymov;
    }
    
    public void setIlymov(Integer ilymov) {
        this.ilymov = ilymov;
    }
    public Integer getIlamov() {
        return this.ilamov;
    }
    
    public void setIlamov(Integer ilamov) {
        this.ilamov = ilamov;
    }
    public Integer getIlmmov() {
        return this.ilmmov;
    }
    
    public void setIlmmov(Integer ilmmov) {
        this.ilmmov = ilmmov;
    }
    public Integer getIldmov() {
        return this.ildmov;
    }
    
    public void setIldmov(Integer ildmov) {
        this.ildmov = ildmov;
    }
    public Integer getIlcdin() {
        return this.ilcdin;
    }
    
    public void setIlcdin(Integer ilcdin) {
        this.ilcdin = ilcdin;
    }
    public Integer getIladin() {
        return this.iladin;
    }
    
    public void setIladin(Integer iladin) {
        this.iladin = iladin;
    }
    public Integer getIlmdin() {
        return this.ilmdin;
    }
    
    public void setIlmdin(Integer ilmdin) {
        this.ilmdin = ilmdin;
    }
    public Integer getIlddin() {
        return this.ilddin;
    }
    
    public void setIlddin(Integer ilddin) {
        this.ilddin = ilddin;
    }
    public Integer getIlchin() {
        return this.ilchin;
    }
    
    public void setIlchin(Integer ilchin) {
        this.ilchin = ilchin;
    }
    public Integer getIlahin() {
        return this.ilahin;
    }
    
    public void setIlahin(Integer ilahin) {
        this.ilahin = ilahin;
    }
    public Integer getIlmhin() {
        return this.ilmhin;
    }
    
    public void setIlmhin(Integer ilmhin) {
        this.ilmhin = ilmhin;
    }
    public Integer getIldhin() {
        return this.ildhin;
    }
    
    public void setIldhin(Integer ildhin) {
        this.ildhin = ildhin;
    }
    public BigDecimal getIlibci() {
        return this.ilibci;
    }
    
    public void setIlibci(BigDecimal ilibci) {
        this.ilibci = ilibci;
    }
    public Integer getIldiin() {
        return this.ildiin;
    }
    
    public void setIldiin(Integer ildiin) {
        this.ildiin = ildiin;
    }
    public BigDecimal getIltidd() {
        return this.iltidd;
    }
    
    public void setIltidd(BigDecimal iltidd) {
        this.iltidd = iltidd;
    }
    public BigDecimal getIltidh() {
        return this.iltidh;
    }
    
    public void setIltidh(BigDecimal iltidh) {
        this.iltidh = iltidh;
    }
    public BigDecimal getIltipr() {
        return this.iltipr;
    }
    
    public void setIltipr(BigDecimal iltipr) {
        this.iltipr = iltipr;
    }
    public BigDecimal getIlicpm() {
        return this.ilicpm;
    }
    
    public void setIlicpm(BigDecimal ilicpm) {
        this.ilicpm = ilicpm;
    }
    public String getIlubir() {
        return this.ilubir;
    }
    
    public void setIlubir(String ilubir) {
        this.ilubir = ilubir;
    }
    public String getIlmini() {
        return this.ilmini;
    }
    
    public void setIlmini(String ilmini) {
        this.ilmini = ilmini;
    }
    public Integer getIlfact() {
        return this.ilfact;
    }
    
    public void setIlfact(Integer ilfact) {
        this.ilfact = ilfact;
    }
    public Integer getIlhact() {
        return this.ilhact;
    }
    
    public void setIlhact(Integer ilhact) {
        this.ilhact = ilhact;
    }
    public String getIlcope() {
        return this.ilcope;
    }
    
    public void setIlcope(String ilcope) {
        this.ilcope = ilcope;
    }
    public String getIlxtrf() {
        return this.ilxtrf;
    }
    
    public void setIlxtrf(String ilxtrf) {
        this.ilxtrf = ilxtrf;
    }
    public Integer getIlccyc() {
        return this.ilccyc;
    }
    
    public void setIlccyc(Integer ilccyc) {
        this.ilccyc = ilccyc;
    }
    public String getIlctrs() {
        return this.ilctrs;
    }
    
    public void setIlctrs(String ilctrs) {
        this.ilctrs = ilctrs;
    }
    public Integer getIlecsl() {
        return this.ilecsl;
    }
    
    public void setIlecsl(Integer ilecsl) {
        this.ilecsl = ilecsl;
    }
    public Integer getIlnpla() {
        return this.ilnpla;
    }
    
    public void setIlnpla(Integer ilnpla) {
        this.ilnpla = ilnpla;
    }
    public String getIlprmi() {
        return this.ilprmi;
    }
    
    public void setIlprmi(String ilprmi) {
        this.ilprmi = ilprmi;
    }




}


