package com.ciessa.museum.model.legacy;
// Generated Jul 30, 2018 8:24:30 PM by Hibernate Tools 3.2.2.GA



/**
 * Zrsplen generated by hbm2java
 */
public class Zrsplen  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String lrtile;
     private Integer lridln;
     private Integer lrnuli;
     private Integer lrlcs1;
     private Integer lrlcs2;
     private Integer lrlcs3;
     private Integer lrlcs4;
     private Integer lrlcs5;
     private String lrlipc;
     private String lrlisc;
     private String lrcope;
     private Integer lrfac8;
     private Integer lrhact;
     private String lreley;
     private String lrus01;
     private String lrus02;
     private String lrus03;
     private String lrus04;
     private String lrus05;
     private String lrus06;
     private String lrus07;
     private String lrus08;
     private String lrus09;
     private String lrus10;
     private String lrus11;
     private String lrus12;
     private String lrus13;
     private String lrus14;
     private String lrus15;
     private String lrus16;
     private String lrus17;
     private String lrus18;
     private String lrus19;
     private String lrus20;
     private String lrus21;
     private String lrubdg;
     private Integer lrqlin;
     private String lrprcd;
     private Integer lrqcar;
     private Integer lriddp;
     private String lrfrdg;

    public Zrsplen() {
    }

	
    public Zrsplen(String pkid) {
        this.pkid = pkid;
    }
    public Zrsplen(String pkid, String member, String lrtile, Integer lridln, Integer lrnuli, Integer lrlcs1, Integer lrlcs2, Integer lrlcs3, Integer lrlcs4, Integer lrlcs5, String lrlipc, String lrlisc, String lrcope, Integer lrfac8, Integer lrhact, String lreley, String lrus01, String lrus02, String lrus03, String lrus04, String lrus05, String lrus06, String lrus07, String lrus08, String lrus09, String lrus10, String lrus11, String lrus12, String lrus13, String lrus14, String lrus15, String lrus16, String lrus17, String lrus18, String lrus19, String lrus20, String lrus21, String lrubdg, Integer lrqlin, String lrprcd, Integer lrqcar, Integer lriddp, String lrfrdg) {
       this.pkid = pkid;
       this.member = member;
       this.lrtile = lrtile;
       this.lridln = lridln;
       this.lrnuli = lrnuli;
       this.lrlcs1 = lrlcs1;
       this.lrlcs2 = lrlcs2;
       this.lrlcs3 = lrlcs3;
       this.lrlcs4 = lrlcs4;
       this.lrlcs5 = lrlcs5;
       this.lrlipc = lrlipc;
       this.lrlisc = lrlisc;
       this.lrcope = lrcope;
       this.lrfac8 = lrfac8;
       this.lrhact = lrhact;
       this.lreley = lreley;
       this.lrus01 = lrus01;
       this.lrus02 = lrus02;
       this.lrus03 = lrus03;
       this.lrus04 = lrus04;
       this.lrus05 = lrus05;
       this.lrus06 = lrus06;
       this.lrus07 = lrus07;
       this.lrus08 = lrus08;
       this.lrus09 = lrus09;
       this.lrus10 = lrus10;
       this.lrus11 = lrus11;
       this.lrus12 = lrus12;
       this.lrus13 = lrus13;
       this.lrus14 = lrus14;
       this.lrus15 = lrus15;
       this.lrus16 = lrus16;
       this.lrus17 = lrus17;
       this.lrus18 = lrus18;
       this.lrus19 = lrus19;
       this.lrus20 = lrus20;
       this.lrus21 = lrus21;
       this.lrubdg = lrubdg;
       this.lrqlin = lrqlin;
       this.lrprcd = lrprcd;
       this.lrqcar = lrqcar;
       this.lriddp = lriddp;
       this.lrfrdg = lrfrdg;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getLrtile() {
        return this.lrtile;
    }
    
    public void setLrtile(String lrtile) {
        this.lrtile = lrtile;
    }
    public Integer getLridln() {
        return this.lridln;
    }
    
    public void setLridln(Integer lridln) {
        this.lridln = lridln;
    }
    public Integer getLrnuli() {
        return this.lrnuli;
    }
    
    public void setLrnuli(Integer lrnuli) {
        this.lrnuli = lrnuli;
    }
    public Integer getLrlcs1() {
        return this.lrlcs1;
    }
    
    public void setLrlcs1(Integer lrlcs1) {
        this.lrlcs1 = lrlcs1;
    }
    public Integer getLrlcs2() {
        return this.lrlcs2;
    }
    
    public void setLrlcs2(Integer lrlcs2) {
        this.lrlcs2 = lrlcs2;
    }
    public Integer getLrlcs3() {
        return this.lrlcs3;
    }
    
    public void setLrlcs3(Integer lrlcs3) {
        this.lrlcs3 = lrlcs3;
    }
    public Integer getLrlcs4() {
        return this.lrlcs4;
    }
    
    public void setLrlcs4(Integer lrlcs4) {
        this.lrlcs4 = lrlcs4;
    }
    public Integer getLrlcs5() {
        return this.lrlcs5;
    }
    
    public void setLrlcs5(Integer lrlcs5) {
        this.lrlcs5 = lrlcs5;
    }
    public String getLrlipc() {
        return this.lrlipc;
    }
    
    public void setLrlipc(String lrlipc) {
        this.lrlipc = lrlipc;
    }
    public String getLrlisc() {
        return this.lrlisc;
    }
    
    public void setLrlisc(String lrlisc) {
        this.lrlisc = lrlisc;
    }
    public String getLrcope() {
        return this.lrcope;
    }
    
    public void setLrcope(String lrcope) {
        this.lrcope = lrcope;
    }
    public Integer getLrfac8() {
        return this.lrfac8;
    }
    
    public void setLrfac8(Integer lrfac8) {
        this.lrfac8 = lrfac8;
    }
    public Integer getLrhact() {
        return this.lrhact;
    }
    
    public void setLrhact(Integer lrhact) {
        this.lrhact = lrhact;
    }
    public String getLreley() {
        return this.lreley;
    }
    
    public void setLreley(String lreley) {
        this.lreley = lreley;
    }
    public String getLrus01() {
        return this.lrus01;
    }
    
    public void setLrus01(String lrus01) {
        this.lrus01 = lrus01;
    }
    public String getLrus02() {
        return this.lrus02;
    }
    
    public void setLrus02(String lrus02) {
        this.lrus02 = lrus02;
    }
    public String getLrus03() {
        return this.lrus03;
    }
    
    public void setLrus03(String lrus03) {
        this.lrus03 = lrus03;
    }
    public String getLrus04() {
        return this.lrus04;
    }
    
    public void setLrus04(String lrus04) {
        this.lrus04 = lrus04;
    }
    public String getLrus05() {
        return this.lrus05;
    }
    
    public void setLrus05(String lrus05) {
        this.lrus05 = lrus05;
    }
    public String getLrus06() {
        return this.lrus06;
    }
    
    public void setLrus06(String lrus06) {
        this.lrus06 = lrus06;
    }
    public String getLrus07() {
        return this.lrus07;
    }
    
    public void setLrus07(String lrus07) {
        this.lrus07 = lrus07;
    }
    public String getLrus08() {
        return this.lrus08;
    }
    
    public void setLrus08(String lrus08) {
        this.lrus08 = lrus08;
    }
    public String getLrus09() {
        return this.lrus09;
    }
    
    public void setLrus09(String lrus09) {
        this.lrus09 = lrus09;
    }
    public String getLrus10() {
        return this.lrus10;
    }
    
    public void setLrus10(String lrus10) {
        this.lrus10 = lrus10;
    }
    public String getLrus11() {
        return this.lrus11;
    }
    
    public void setLrus11(String lrus11) {
        this.lrus11 = lrus11;
    }
    public String getLrus12() {
        return this.lrus12;
    }
    
    public void setLrus12(String lrus12) {
        this.lrus12 = lrus12;
    }
    public String getLrus13() {
        return this.lrus13;
    }
    
    public void setLrus13(String lrus13) {
        this.lrus13 = lrus13;
    }
    public String getLrus14() {
        return this.lrus14;
    }
    
    public void setLrus14(String lrus14) {
        this.lrus14 = lrus14;
    }
    public String getLrus15() {
        return this.lrus15;
    }
    
    public void setLrus15(String lrus15) {
        this.lrus15 = lrus15;
    }
    public String getLrus16() {
        return this.lrus16;
    }
    
    public void setLrus16(String lrus16) {
        this.lrus16 = lrus16;
    }
    public String getLrus17() {
        return this.lrus17;
    }
    
    public void setLrus17(String lrus17) {
        this.lrus17 = lrus17;
    }
    public String getLrus18() {
        return this.lrus18;
    }
    
    public void setLrus18(String lrus18) {
        this.lrus18 = lrus18;
    }
    public String getLrus19() {
        return this.lrus19;
    }
    
    public void setLrus19(String lrus19) {
        this.lrus19 = lrus19;
    }
    public String getLrus20() {
        return this.lrus20;
    }
    
    public void setLrus20(String lrus20) {
        this.lrus20 = lrus20;
    }
    public String getLrus21() {
        return this.lrus21;
    }
    
    public void setLrus21(String lrus21) {
        this.lrus21 = lrus21;
    }
    public String getLrubdg() {
        return this.lrubdg;
    }
    
    public void setLrubdg(String lrubdg) {
        this.lrubdg = lrubdg;
    }
    public Integer getLrqlin() {
        return this.lrqlin;
    }
    
    public void setLrqlin(Integer lrqlin) {
        this.lrqlin = lrqlin;
    }
    public String getLrprcd() {
        return this.lrprcd;
    }
    
    public void setLrprcd(String lrprcd) {
        this.lrprcd = lrprcd;
    }
    public Integer getLrqcar() {
        return this.lrqcar;
    }
    
    public void setLrqcar(Integer lrqcar) {
        this.lrqcar = lrqcar;
    }
    public Integer getLriddp() {
        return this.lriddp;
    }
    
    public void setLriddp(Integer lriddp) {
        this.lriddp = lriddp;
    }
    public String getLrfrdg() {
        return this.lrfrdg;
    }
    
    public void setLrfrdg(String lrfrdg) {
        this.lrfrdg = lrfrdg;
    }




}


