package com.ciessa.museum.model.legacy;
// Generated Jan 28, 2019 1:33:59 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Zrsppir generated by hbm2java
 */
public class Zrsppir  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer tiyfac;
     private Integer tiaafc;
     private String ticifa;
     private String tiagig;
     private Integer tiorg;
     private Integer tilogo;
     private String tincct;
     private String tincrd;
     private Integer tiptnr;
     private Integer tincax;
     private Integer tiscax;
     private Integer tinsem;
     private Integer tiavto;
     private Integer timvto;
     private Integer tidvto;
     private Integer titcco;
     private Integer ticlco;
     private Integer ticcnr;
     private String ticacl;
     private Long tiscli;
     private Integer ticori;
     private Integer ticmov;
     private Integer ticsmv;
     private Integer ticpag;
     private Integer tiapag;
     private Integer timpag;
     private Integer tidpag;
     private Integer ticrcc;
     private Integer ticraa;
     private Integer ticrmm;
     private Integer ticrdd;
     private BigDecimal tiimpo;
     private BigDecimal ticoti;
     private String tiubir;
     private String timini;
     private Integer tifact;
     private Integer tihact;
     private String ticope;
     private Integer tibonr;
     private Integer tinrtr;
     private String titetr;
     private Integer tiapdt;
     private Integer tiadtm;
     private String tixtrf;
     private Integer ticcyc;
     private String tide40;
     private String tictrs;
     private Integer tiecsl;
     private Integer tinpla;
     private String tiprmi;

    public Zrsppir() {
    }

	
    public Zrsppir(String pkid) {
        this.pkid = pkid;
    }
    public Zrsppir(String pkid, String member, Integer tiyfac, Integer tiaafc, String ticifa, String tiagig, Integer tiorg, Integer tilogo, String tincct, String tincrd, Integer tiptnr, Integer tincax, Integer tiscax, Integer tinsem, Integer tiavto, Integer timvto, Integer tidvto, Integer titcco, Integer ticlco, Integer ticcnr, String ticacl, Long tiscli, Integer ticori, Integer ticmov, Integer ticsmv, Integer ticpag, Integer tiapag, Integer timpag, Integer tidpag, Integer ticrcc, Integer ticraa, Integer ticrmm, Integer ticrdd, BigDecimal tiimpo, BigDecimal ticoti, String tiubir, String timini, Integer tifact, Integer tihact, String ticope, Integer tibonr, Integer tinrtr, String titetr, Integer tiapdt, Integer tiadtm, String tixtrf, Integer ticcyc, String tide40, String tictrs, Integer tiecsl, Integer tinpla, String tiprmi) {
       this.pkid = pkid;
       this.member = member;
       this.tiyfac = tiyfac;
       this.tiaafc = tiaafc;
       this.ticifa = ticifa;
       this.tiagig = tiagig;
       this.tiorg = tiorg;
       this.tilogo = tilogo;
       this.tincct = tincct;
       this.tincrd = tincrd;
       this.tiptnr = tiptnr;
       this.tincax = tincax;
       this.tiscax = tiscax;
       this.tinsem = tinsem;
       this.tiavto = tiavto;
       this.timvto = timvto;
       this.tidvto = tidvto;
       this.titcco = titcco;
       this.ticlco = ticlco;
       this.ticcnr = ticcnr;
       this.ticacl = ticacl;
       this.tiscli = tiscli;
       this.ticori = ticori;
       this.ticmov = ticmov;
       this.ticsmv = ticsmv;
       this.ticpag = ticpag;
       this.tiapag = tiapag;
       this.timpag = timpag;
       this.tidpag = tidpag;
       this.ticrcc = ticrcc;
       this.ticraa = ticraa;
       this.ticrmm = ticrmm;
       this.ticrdd = ticrdd;
       this.tiimpo = tiimpo;
       this.ticoti = ticoti;
       this.tiubir = tiubir;
       this.timini = timini;
       this.tifact = tifact;
       this.tihact = tihact;
       this.ticope = ticope;
       this.tibonr = tibonr;
       this.tinrtr = tinrtr;
       this.titetr = titetr;
       this.tiapdt = tiapdt;
       this.tiadtm = tiadtm;
       this.tixtrf = tixtrf;
       this.ticcyc = ticcyc;
       this.tide40 = tide40;
       this.tictrs = tictrs;
       this.tiecsl = tiecsl;
       this.tinpla = tinpla;
       this.tiprmi = tiprmi;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getTiyfac() {
        return this.tiyfac;
    }
    
    public void setTiyfac(Integer tiyfac) {
        this.tiyfac = tiyfac;
    }
    public Integer getTiaafc() {
        return this.tiaafc;
    }
    
    public void setTiaafc(Integer tiaafc) {
        this.tiaafc = tiaafc;
    }
    public String getTicifa() {
        return this.ticifa;
    }
    
    public void setTicifa(String ticifa) {
        this.ticifa = ticifa;
    }
    public String getTiagig() {
        return this.tiagig;
    }
    
    public void setTiagig(String tiagig) {
        this.tiagig = tiagig;
    }
    public Integer getTiorg() {
        return this.tiorg;
    }
    
    public void setTiorg(Integer tiorg) {
        this.tiorg = tiorg;
    }
    public Integer getTilogo() {
        return this.tilogo;
    }
    
    public void setTilogo(Integer tilogo) {
        this.tilogo = tilogo;
    }
    public String getTincct() {
        return this.tincct;
    }
    
    public void setTincct(String tincct) {
        this.tincct = tincct;
    }
    public String getTincrd() {
        return this.tincrd;
    }
    
    public void setTincrd(String tincrd) {
        this.tincrd = tincrd;
    }
    public Integer getTiptnr() {
        return this.tiptnr;
    }
    
    public void setTiptnr(Integer tiptnr) {
        this.tiptnr = tiptnr;
    }
    public Integer getTincax() {
        return this.tincax;
    }
    
    public void setTincax(Integer tincax) {
        this.tincax = tincax;
    }
    public Integer getTiscax() {
        return this.tiscax;
    }
    
    public void setTiscax(Integer tiscax) {
        this.tiscax = tiscax;
    }
    public Integer getTinsem() {
        return this.tinsem;
    }
    
    public void setTinsem(Integer tinsem) {
        this.tinsem = tinsem;
    }
    public Integer getTiavto() {
        return this.tiavto;
    }
    
    public void setTiavto(Integer tiavto) {
        this.tiavto = tiavto;
    }
    public Integer getTimvto() {
        return this.timvto;
    }
    
    public void setTimvto(Integer timvto) {
        this.timvto = timvto;
    }
    public Integer getTidvto() {
        return this.tidvto;
    }
    
    public void setTidvto(Integer tidvto) {
        this.tidvto = tidvto;
    }
    public Integer getTitcco() {
        return this.titcco;
    }
    
    public void setTitcco(Integer titcco) {
        this.titcco = titcco;
    }
    public Integer getTiclco() {
        return this.ticlco;
    }
    
    public void setTiclco(Integer ticlco) {
        this.ticlco = ticlco;
    }
    public Integer getTiccnr() {
        return this.ticcnr;
    }
    
    public void setTiccnr(Integer ticcnr) {
        this.ticcnr = ticcnr;
    }
    public String getTicacl() {
        return this.ticacl;
    }
    
    public void setTicacl(String ticacl) {
        this.ticacl = ticacl;
    }
    public Long getTiscli() {
        return this.tiscli;
    }
    
    public void setTiscli(Long tiscli) {
        this.tiscli = tiscli;
    }
    public Integer getTicori() {
        return this.ticori;
    }
    
    public void setTicori(Integer ticori) {
        this.ticori = ticori;
    }
    public Integer getTicmov() {
        return this.ticmov;
    }
    
    public void setTicmov(Integer ticmov) {
        this.ticmov = ticmov;
    }
    public Integer getTicsmv() {
        return this.ticsmv;
    }
    
    public void setTicsmv(Integer ticsmv) {
        this.ticsmv = ticsmv;
    }
    public Integer getTicpag() {
        return this.ticpag;
    }
    
    public void setTicpag(Integer ticpag) {
        this.ticpag = ticpag;
    }
    public Integer getTiapag() {
        return this.tiapag;
    }
    
    public void setTiapag(Integer tiapag) {
        this.tiapag = tiapag;
    }
    public Integer getTimpag() {
        return this.timpag;
    }
    
    public void setTimpag(Integer timpag) {
        this.timpag = timpag;
    }
    public Integer getTidpag() {
        return this.tidpag;
    }
    
    public void setTidpag(Integer tidpag) {
        this.tidpag = tidpag;
    }
    public Integer getTicrcc() {
        return this.ticrcc;
    }
    
    public void setTicrcc(Integer ticrcc) {
        this.ticrcc = ticrcc;
    }
    public Integer getTicraa() {
        return this.ticraa;
    }
    
    public void setTicraa(Integer ticraa) {
        this.ticraa = ticraa;
    }
    public Integer getTicrmm() {
        return this.ticrmm;
    }
    
    public void setTicrmm(Integer ticrmm) {
        this.ticrmm = ticrmm;
    }
    public Integer getTicrdd() {
        return this.ticrdd;
    }
    
    public void setTicrdd(Integer ticrdd) {
        this.ticrdd = ticrdd;
    }
    public BigDecimal getTiimpo() {
        return this.tiimpo;
    }
    
    public void setTiimpo(BigDecimal tiimpo) {
        this.tiimpo = tiimpo;
    }
    public BigDecimal getTicoti() {
        return this.ticoti;
    }
    
    public void setTicoti(BigDecimal ticoti) {
        this.ticoti = ticoti;
    }
    public String getTiubir() {
        return this.tiubir;
    }
    
    public void setTiubir(String tiubir) {
        this.tiubir = tiubir;
    }
    public String getTimini() {
        return this.timini;
    }
    
    public void setTimini(String timini) {
        this.timini = timini;
    }
    public Integer getTifact() {
        return this.tifact;
    }
    
    public void setTifact(Integer tifact) {
        this.tifact = tifact;
    }
    public Integer getTihact() {
        return this.tihact;
    }
    
    public void setTihact(Integer tihact) {
        this.tihact = tihact;
    }
    public String getTicope() {
        return this.ticope;
    }
    
    public void setTicope(String ticope) {
        this.ticope = ticope;
    }
    public Integer getTibonr() {
        return this.tibonr;
    }
    
    public void setTibonr(Integer tibonr) {
        this.tibonr = tibonr;
    }
    public Integer getTinrtr() {
        return this.tinrtr;
    }
    
    public void setTinrtr(Integer tinrtr) {
        this.tinrtr = tinrtr;
    }
    public String getTitetr() {
        return this.titetr;
    }
    
    public void setTitetr(String titetr) {
        this.titetr = titetr;
    }
    public Integer getTiapdt() {
        return this.tiapdt;
    }
    
    public void setTiapdt(Integer tiapdt) {
        this.tiapdt = tiapdt;
    }
    public Integer getTiadtm() {
        return this.tiadtm;
    }
    
    public void setTiadtm(Integer tiadtm) {
        this.tiadtm = tiadtm;
    }
    public String getTixtrf() {
        return this.tixtrf;
    }
    
    public void setTixtrf(String tixtrf) {
        this.tixtrf = tixtrf;
    }
    public Integer getTiccyc() {
        return this.ticcyc;
    }
    
    public void setTiccyc(Integer ticcyc) {
        this.ticcyc = ticcyc;
    }
    public String getTide40() {
        return this.tide40;
    }
    
    public void setTide40(String tide40) {
        this.tide40 = tide40;
    }
    public String getTictrs() {
        return this.tictrs;
    }
    
    public void setTictrs(String tictrs) {
        this.tictrs = tictrs;
    }
    public Integer getTiecsl() {
        return this.tiecsl;
    }
    
    public void setTiecsl(Integer tiecsl) {
        this.tiecsl = tiecsl;
    }
    public Integer getTinpla() {
        return this.tinpla;
    }
    
    public void setTinpla(Integer tinpla) {
        this.tinpla = tinpla;
    }
    public String getTiprmi() {
        return this.tiprmi;
    }
    
    public void setTiprmi(String tiprmi) {
        this.tiprmi = tiprmi;
    }




}


