package com.ciessa.museum.model.legacy;
// Generated Sep 13, 2018 8:37:56 PM by Hibernate Tools 3.2.2.GA



/**
 * Zrspmss generated by hbm2java
 */
public class Zrspmss  implements java.io.Serializable {


     private String pkid;
     private String member;
     private Integer msyfac;
     private Integer msaafc;
     private String mscifa;
     private Integer msccyc;
     private Integer msorg;
     private Integer mslogo;
     private String msmgcd;
     private Integer msvrsn;
     private String msclge;
     private String msmgds;

    public Zrspmss() {
    }

	
    public Zrspmss(String pkid) {
        this.pkid = pkid;
    }
    public Zrspmss(String pkid, String member, Integer msyfac, Integer msaafc, String mscifa, Integer msccyc, Integer msorg, Integer mslogo, String msmgcd, Integer msvrsn, String msclge, String msmgds) {
       this.pkid = pkid;
       this.member = member;
       this.msyfac = msyfac;
       this.msaafc = msaafc;
       this.mscifa = mscifa;
       this.msccyc = msccyc;
       this.msorg = msorg;
       this.mslogo = mslogo;
       this.msmgcd = msmgcd;
       this.msvrsn = msvrsn;
       this.msclge = msclge;
       this.msmgds = msmgds;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public Integer getMsyfac() {
        return this.msyfac;
    }
    
    public void setMsyfac(Integer msyfac) {
        this.msyfac = msyfac;
    }
    public Integer getMsaafc() {
        return this.msaafc;
    }
    
    public void setMsaafc(Integer msaafc) {
        this.msaafc = msaafc;
    }
    public String getMscifa() {
        return this.mscifa;
    }
    
    public void setMscifa(String mscifa) {
        this.mscifa = mscifa;
    }
    public Integer getMsccyc() {
        return this.msccyc;
    }
    
    public void setMsccyc(Integer msccyc) {
        this.msccyc = msccyc;
    }
    public Integer getMsorg() {
        return this.msorg;
    }
    
    public void setMsorg(Integer msorg) {
        this.msorg = msorg;
    }
    public Integer getMslogo() {
        return this.mslogo;
    }
    
    public void setMslogo(Integer mslogo) {
        this.mslogo = mslogo;
    }
    public String getMsmgcd() {
        return this.msmgcd;
    }
    
    public void setMsmgcd(String msmgcd) {
        this.msmgcd = msmgcd;
    }
    public Integer getMsvrsn() {
        return this.msvrsn;
    }
    
    public void setMsvrsn(Integer msvrsn) {
        this.msvrsn = msvrsn;
    }
    public String getMsclge() {
        return this.msclge;
    }
    
    public void setMsclge(String msclge) {
        this.msclge = msclge;
    }
    public String getMsmgds() {
        return this.msmgds;
    }
    
    public void setMsmgds(String msmgds) {
        this.msmgds = msmgds;
    }




}


