package com.ciessa.museum.model.legacy;
// Generated Jan 28, 2019 1:33:59 PM by Hibernate Tools 3.2.2.GA



/**
 * Zrspdmr generated by hbm2java
 */
public class Zrspdmr  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String drcmon;
     private String drctrs;
     private Integer drecsl;
     private Integer drnpla;
     private String drprmi;
     private Integer drcori;
     private Integer drcmov;
     private Integer drcsmv;
     private String drdesc;
     private String drdimp;
     private String drmini;
     private String drubir;
     private Integer drclmo;
     private String drmmdt;
     private String drmmrr;
     private Integer drrega;
     private Integer drregi;
     private Integer drfact;
     private Integer drhact;
     private String drcope;
     private String drcidw;
     private String drcmty;
     private String drfile;
     private String drpryn;
     private String dracpf;
     private String drdsfc;
     private String drmgrv;
     private Integer drfamg;
     private String droamg;

    public Zrspdmr() {
    }

	
    public Zrspdmr(String pkid) {
        this.pkid = pkid;
    }
    public Zrspdmr(String pkid, String member, String drcmon, String drctrs, Integer drecsl, Integer drnpla, String drprmi, Integer drcori, Integer drcmov, Integer drcsmv, String drdesc, String drdimp, String drmini, String drubir, Integer drclmo, String drmmdt, String drmmrr, Integer drrega, Integer drregi, Integer drfact, Integer drhact, String drcope, String drcidw, String drcmty, String drfile, String drpryn, String dracpf, String drdsfc, String drmgrv, Integer drfamg, String droamg) {
       this.pkid = pkid;
       this.member = member;
       this.drcmon = drcmon;
       this.drctrs = drctrs;
       this.drecsl = drecsl;
       this.drnpla = drnpla;
       this.drprmi = drprmi;
       this.drcori = drcori;
       this.drcmov = drcmov;
       this.drcsmv = drcsmv;
       this.drdesc = drdesc;
       this.drdimp = drdimp;
       this.drmini = drmini;
       this.drubir = drubir;
       this.drclmo = drclmo;
       this.drmmdt = drmmdt;
       this.drmmrr = drmmrr;
       this.drrega = drrega;
       this.drregi = drregi;
       this.drfact = drfact;
       this.drhact = drhact;
       this.drcope = drcope;
       this.drcidw = drcidw;
       this.drcmty = drcmty;
       this.drfile = drfile;
       this.drpryn = drpryn;
       this.dracpf = dracpf;
       this.drdsfc = drdsfc;
       this.drmgrv = drmgrv;
       this.drfamg = drfamg;
       this.droamg = droamg;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getDrcmon() {
        return this.drcmon;
    }
    
    public void setDrcmon(String drcmon) {
        this.drcmon = drcmon;
    }
    public String getDrctrs() {
        return this.drctrs;
    }
    
    public void setDrctrs(String drctrs) {
        this.drctrs = drctrs;
    }
    public Integer getDrecsl() {
        return this.drecsl;
    }
    
    public void setDrecsl(Integer drecsl) {
        this.drecsl = drecsl;
    }
    public Integer getDrnpla() {
        return this.drnpla;
    }
    
    public void setDrnpla(Integer drnpla) {
        this.drnpla = drnpla;
    }
    public String getDrprmi() {
        return this.drprmi;
    }
    
    public void setDrprmi(String drprmi) {
        this.drprmi = drprmi;
    }
    public Integer getDrcori() {
        return this.drcori;
    }
    
    public void setDrcori(Integer drcori) {
        this.drcori = drcori;
    }
    public Integer getDrcmov() {
        return this.drcmov;
    }
    
    public void setDrcmov(Integer drcmov) {
        this.drcmov = drcmov;
    }
    public Integer getDrcsmv() {
        return this.drcsmv;
    }
    
    public void setDrcsmv(Integer drcsmv) {
        this.drcsmv = drcsmv;
    }
    public String getDrdesc() {
        return this.drdesc;
    }
    
    public void setDrdesc(String drdesc) {
        this.drdesc = drdesc;
    }
    public String getDrdimp() {
        return this.drdimp;
    }
    
    public void setDrdimp(String drdimp) {
        this.drdimp = drdimp;
    }
    public String getDrmini() {
        return this.drmini;
    }
    
    public void setDrmini(String drmini) {
        this.drmini = drmini;
    }
    public String getDrubir() {
        return this.drubir;
    }
    
    public void setDrubir(String drubir) {
        this.drubir = drubir;
    }
    public Integer getDrclmo() {
        return this.drclmo;
    }
    
    public void setDrclmo(Integer drclmo) {
        this.drclmo = drclmo;
    }
    public String getDrmmdt() {
        return this.drmmdt;
    }
    
    public void setDrmmdt(String drmmdt) {
        this.drmmdt = drmmdt;
    }
    public String getDrmmrr() {
        return this.drmmrr;
    }
    
    public void setDrmmrr(String drmmrr) {
        this.drmmrr = drmmrr;
    }
    public Integer getDrrega() {
        return this.drrega;
    }
    
    public void setDrrega(Integer drrega) {
        this.drrega = drrega;
    }
    public Integer getDrregi() {
        return this.drregi;
    }
    
    public void setDrregi(Integer drregi) {
        this.drregi = drregi;
    }
    public Integer getDrfact() {
        return this.drfact;
    }
    
    public void setDrfact(Integer drfact) {
        this.drfact = drfact;
    }
    public Integer getDrhact() {
        return this.drhact;
    }
    
    public void setDrhact(Integer drhact) {
        this.drhact = drhact;
    }
    public String getDrcope() {
        return this.drcope;
    }
    
    public void setDrcope(String drcope) {
        this.drcope = drcope;
    }
    public String getDrcidw() {
        return this.drcidw;
    }
    
    public void setDrcidw(String drcidw) {
        this.drcidw = drcidw;
    }
    public String getDrcmty() {
        return this.drcmty;
    }
    
    public void setDrcmty(String drcmty) {
        this.drcmty = drcmty;
    }
    public String getDrfile() {
        return this.drfile;
    }
    
    public void setDrfile(String drfile) {
        this.drfile = drfile;
    }
    public String getDrpryn() {
        return this.drpryn;
    }
    
    public void setDrpryn(String drpryn) {
        this.drpryn = drpryn;
    }
    public String getDracpf() {
        return this.dracpf;
    }
    
    public void setDracpf(String dracpf) {
        this.dracpf = dracpf;
    }
    public String getDrdsfc() {
        return this.drdsfc;
    }
    
    public void setDrdsfc(String drdsfc) {
        this.drdsfc = drdsfc;
    }
    public String getDrmgrv() {
        return this.drmgrv;
    }
    
    public void setDrmgrv(String drmgrv) {
        this.drmgrv = drmgrv;
    }
    public Integer getDrfamg() {
        return this.drfamg;
    }
    
    public void setDrfamg(Integer drfamg) {
        this.drfamg = drfamg;
    }
    public String getDroamg() {
        return this.droamg;
    }
    
    public void setDroamg(String droamg) {
        this.droamg = droamg;
    }




}


