package com.ciessa.museum.model.legacy;
// Generated Dec 11, 2018 7:50:29 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Zvrpfrq generated by hbm2java
 */
public class Zvrpfrq  implements java.io.Serializable {


     private String pkid;
     private String member;
     private String fr1066;
     private String fr1069;
     private String fr3013;
     private String fr3018;
     private String fr8165;
     private String fr3022;
     private String fr1150;
     private BigDecimal fr4264;
     private Integer fr6302;
     private Integer fr8170;
     private Integer fr8175;
     private Integer fr8180;
     private Integer fr8185;
     private Integer fr2848;
     private String fr3476;
     private Integer fr8190;
     private Integer fr4430;
     private Integer fr8195;
     private Integer fr8200;
     private Integer fr8197;
     private Integer fr8202;
     private BigDecimal fr9999;
     private String fr9969;

    public Zvrpfrq() {
    }

	
    public Zvrpfrq(String pkid) {
        this.pkid = pkid;
    }
    public Zvrpfrq(String pkid, String member, String fr1066, String fr1069, String fr3013, String fr3018, String fr8165, String fr3022, String fr1150, BigDecimal fr4264, Integer fr6302, Integer fr8170, Integer fr8175, Integer fr8180, Integer fr8185, Integer fr2848, String fr3476, Integer fr8190, Integer fr4430, Integer fr8195, Integer fr8200, Integer fr8197, Integer fr8202, BigDecimal fr9999, String fr9969) {
       this.pkid = pkid;
       this.member = member;
       this.fr1066 = fr1066;
       this.fr1069 = fr1069;
       this.fr3013 = fr3013;
       this.fr3018 = fr3018;
       this.fr8165 = fr8165;
       this.fr3022 = fr3022;
       this.fr1150 = fr1150;
       this.fr4264 = fr4264;
       this.fr6302 = fr6302;
       this.fr8170 = fr8170;
       this.fr8175 = fr8175;
       this.fr8180 = fr8180;
       this.fr8185 = fr8185;
       this.fr2848 = fr2848;
       this.fr3476 = fr3476;
       this.fr8190 = fr8190;
       this.fr4430 = fr4430;
       this.fr8195 = fr8195;
       this.fr8200 = fr8200;
       this.fr8197 = fr8197;
       this.fr8202 = fr8202;
       this.fr9999 = fr9999;
       this.fr9969 = fr9969;
    }
   
    public String getPkid() {
        return this.pkid;
    }
    
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getFr1066() {
        return this.fr1066;
    }
    
    public void setFr1066(String fr1066) {
        this.fr1066 = fr1066;
    }
    public String getFr1069() {
        return this.fr1069;
    }
    
    public void setFr1069(String fr1069) {
        this.fr1069 = fr1069;
    }
    public String getFr3013() {
        return this.fr3013;
    }
    
    public void setFr3013(String fr3013) {
        this.fr3013 = fr3013;
    }
    public String getFr3018() {
        return this.fr3018;
    }
    
    public void setFr3018(String fr3018) {
        this.fr3018 = fr3018;
    }
    public String getFr8165() {
        return this.fr8165;
    }
    
    public void setFr8165(String fr8165) {
        this.fr8165 = fr8165;
    }
    public String getFr3022() {
        return this.fr3022;
    }
    
    public void setFr3022(String fr3022) {
        this.fr3022 = fr3022;
    }
    public String getFr1150() {
        return this.fr1150;
    }
    
    public void setFr1150(String fr1150) {
        this.fr1150 = fr1150;
    }
    public BigDecimal getFr4264() {
        return this.fr4264;
    }
    
    public void setFr4264(BigDecimal fr4264) {
        this.fr4264 = fr4264;
    }
    public Integer getFr6302() {
        return this.fr6302;
    }
    
    public void setFr6302(Integer fr6302) {
        this.fr6302 = fr6302;
    }
    public Integer getFr8170() {
        return this.fr8170;
    }
    
    public void setFr8170(Integer fr8170) {
        this.fr8170 = fr8170;
    }
    public Integer getFr8175() {
        return this.fr8175;
    }
    
    public void setFr8175(Integer fr8175) {
        this.fr8175 = fr8175;
    }
    public Integer getFr8180() {
        return this.fr8180;
    }
    
    public void setFr8180(Integer fr8180) {
        this.fr8180 = fr8180;
    }
    public Integer getFr8185() {
        return this.fr8185;
    }
    
    public void setFr8185(Integer fr8185) {
        this.fr8185 = fr8185;
    }
    public Integer getFr2848() {
        return this.fr2848;
    }
    
    public void setFr2848(Integer fr2848) {
        this.fr2848 = fr2848;
    }
    public String getFr3476() {
        return this.fr3476;
    }
    
    public void setFr3476(String fr3476) {
        this.fr3476 = fr3476;
    }
    public Integer getFr8190() {
        return this.fr8190;
    }
    
    public void setFr8190(Integer fr8190) {
        this.fr8190 = fr8190;
    }
    public Integer getFr4430() {
        return this.fr4430;
    }
    
    public void setFr4430(Integer fr4430) {
        this.fr4430 = fr4430;
    }
    public Integer getFr8195() {
        return this.fr8195;
    }
    
    public void setFr8195(Integer fr8195) {
        this.fr8195 = fr8195;
    }
    public Integer getFr8200() {
        return this.fr8200;
    }
    
    public void setFr8200(Integer fr8200) {
        this.fr8200 = fr8200;
    }
    public Integer getFr8197() {
        return this.fr8197;
    }
    
    public void setFr8197(Integer fr8197) {
        this.fr8197 = fr8197;
    }
    public Integer getFr8202() {
        return this.fr8202;
    }
    
    public void setFr8202(Integer fr8202) {
        this.fr8202 = fr8202;
    }
    public BigDecimal getFr9999() {
        return this.fr9999;
    }
    
    public void setFr9999(BigDecimal fr9999) {
        this.fr9999 = fr9999;
    }
    public String getFr9969() {
        return this.fr9969;
    }
    
    public void setFr9969(String fr9969) {
        this.fr9969 = fr9969;
    }




}


